In [1]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("data/inline_pins.csv")
data.head()

,Connector Name,Connector PartNumber,Pin Name,Pin PreferredSignal,Signal Name,MulticoreInnerToOutter1,MulticoreInnerToOutter2,MulticoreInnerToOutter4,MulticoreInnerToOutter3,MulticoreInnerToOutter5,MulticoreInnerToOutter6,MulticoreInnerToOutter7,MulticoreInnerToOutter8,MulticoreInnerToOutter9
0,TO_141_LH_LHD_F/111_LH_LHD,NaN,19,NaN,EQ_METER_LL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TO_141_LH_LHD_F/111_LH_LHD,NaN,39,NaN,SHIFT_ECU_1604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,TO_141_LH_LHD_F/111_LH_LHD,NaN,35,NaN,EQ_F:SBW_IGCT-HV_L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,TO_141_LH_LHD_F/111_LH_LHD,NaN,16,NaN,EQ_FUEL_LID_OPNR_SW_IG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,TO_141_LH_LHD_F/111_LH_LHD,NaN,48,NaN,H/P_ECU_1431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
data["Signal Name"].fillna("na", inplace=True)
data["Pin PreferredSignal"].fillna("na", inplace=True)

In [5]:
def signal_equal(row):
    if (row["Pin PreferredSignal"]== "na" and row["Signal Name"]== "na") :
        return 2
    elif row["Pin PreferredSignal"]==row["Signal Name"]:
        return 1
    else:
        return 0

In [6]:
data['check_signal']=data.apply(lambda row:signal_equal(row),axis=1)

In [7]:
connector_view=data.groupby(["Connector Name",'Pin Name']).agg({ "Pin PreferredSignal":['nunique','count'] })
connector_view.head(10)

                         Pin PreferredSignal
                                     nunique count
Connector Name  Pin Name
TO_111_LH_F/113 1                          1     1
                2                          1     1
                3                          1     1
                4                          1     1
                5                          1     1
                6                          1     1
                7                          1     1
                8                          1     1
                9                          1     1
                10                         1     1

In [8]:
levels=connector_view.index.nlevels
for i in reversed(range(0,levels)):
    connector_view.reset_index(level=i, inplace=True)

In [9]:
connector_view.columns=['Connector Name','Pin Name','Pin Name nunique',"Pin Name count"]
connector_view.tail(10)

             Connector Name  Pin Name  Pin Name nunique  Pin Name count
1708  TO_219_F/121_TNGA_13P         4                 1               1
1709  TO_219_F/121_TNGA_13P         5                 1               1
1710  TO_219_F/121_TNGA_13P         6                 1               1
1711  TO_219_F/121_TNGA_13P         7                 1               1
1712  TO_219_F/121_TNGA_13P         8                 1               1
1713  TO_219_F/121_TNGA_13P         9                 1               1
1714  TO_219_F/121_TNGA_13P        10                 1               1
1715  TO_219_F/121_TNGA_13P        11                 1               1
1716  TO_219_F/121_TNGA_13P        12                 1               1
1717  TO_219_F/121_TNGA_13P        13                 1               1

In [10]:
groupped= pd.merge(connector_view,data, on=['Connector Name','Pin Name'], how='inner')
len(connector_view),len(data),len(groupped)

(1718, 1718, 1718)

In [11]:
connector_view2=data.groupby(["Connector Name"]).agg({ 'Pin Name':['nunique','count'] })
connector_view2.head()

                           Pin Name
                            nunique count
Connector Name
TO_111_LH_F/113                  17    17
TO_111_LH_F/121                  28    28
TO_111_LH_F/143_3P                3     3
TO_111_LH_F/161_LH               53    53
TO_111_LH_LHD_F/141_LH_LHD       49    49

In [12]:
levels=connector_view2.index.nlevels
for i in reversed(range(0,levels)):
    connector_view2.reset_index(level=i, inplace=True)

In [13]:
connector_view2.columns=['Connector Name','Num_Pin_unique','Num_Pins']

In [14]:
connector_view2['more_signal_in_pin']=connector_view2["Num_Pin_unique"]!=connector_view2["Num_Pins"]
connector_view2.head(25)

                Connector Name  Num_Pin_unique  Num_Pins  more_signal_in_pin
0              TO_111_LH_F/113              17        17               False
1              TO_111_LH_F/121              28        28               False
2           TO_111_LH_F/143_3P               3         3               False
3           TO_111_LH_F/161_LH              53        53               False
4   TO_111_LH_LHD_F/141_LH_LHD              49        49               False
5   TO_111_LH_RHD_F/141_LH_RHD              50        50               False
6           TO_111_RH_F/161_RH              41        41               False
7   TO_111_RH_LHD_F/141_RH_LHD              35        35               False
8   TO_111_RH_RHD_F/141_RH_RHD              42        42               False
9              TO_113_F/111_LH              17        17               False
10             TO_121_F/111_LH              28        28               False
11           TO_121_TNGA_F/125              10        10               False
12           TO_121_TNGA_F/126               8         8               False
13       TO_121_TNGA_F/219_13P              13        13               False
14             TO_121_ZR_F/124               2         2               False
15             TO_124_F/121_ZR               2         2               False
16           TO_125_F/121_TNGA              10        10               False
17           TO_126_F/121_TNGA               8         8               False
18         TO_141_LH_F/142_18P              18        18               False
19             TO_141_LH_F/152              28        28               False
20          TO_141_LH_F/161_LH              55        55               False
21             TO_141_LH_F/171              53        53               False
22  TO_141_LH_LHD_F/111_LH_LHD              49        49               False
23  TO_141_LH_RHD_F/111_LH_RHD              50        50               False
24             TO_141_RH_F/151              31        31               False

In [15]:
groupped2= pd.merge(groupped,connector_view2, on=['Connector Name'], how='inner')
len(groupped2),len(groupped)

(1718, 1718)

In [16]:
groupped2.head(15)

,Connector Name,Pin Name,Pin Name nunique,Pin Name count,Connector PartNumber,Pin PreferredSignal,Signal Name,MulticoreInnerToOutter1,MulticoreInnerToOutter2,MulticoreInnerToOutter4,MulticoreInnerToOutter3,MulticoreInnerToOutter5,MulticoreInnerToOutter6,MulticoreInnerToOutter7,MulticoreInnerToOutter8,MulticoreInnerToOutter9,check_signal,Num_Pin_unique,Num_Pins,more_signal_in_pin
0,TO_111_LH_F/113,1,1,1,NaN,na,EMB_PVM_ECU_064,MC137112,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,17,17,False
1,TO_111_LH_F/113,2,1,1,NaN,na,EMB_PVM_ECU_065,MC137112,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,17,17,False
2,TO_111_LH_F/113,3,1,1,NaN,na,EMB_PVM_ECU_066,MC137112,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,17,17,False
3,TO_111_LH_F/113,4,1,1,NaN,na,EMB_PVM_ECU_067,MC137112,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,17,17,False
4,TO_111_LH_F/113,5,1,1,NaN,na,EMB_FRONT_CAMERA-PVM_063,MC137112,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,17,17,False
5,TO_111_LH_F/113,6,1,1,NaN,na,TW_CLEARANCE_SNR_ECU_075,MC137529,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,17,17,False
6,TO_111_LH_F/113,7,1,1,NaN,na,TW_CLEARANCE_SNR_ECU_076,MC137529,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,17,17,False
7,TO_111_LH_F/113,8,1,1,NaN,na,TW_CLEARANCE_SNR_ECU_077,MC137533,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,17,17,False
8,TO_111_LH_F/113,9,1,1,NaN,na,TW_CLEARANCE_SNR_ECU_078,MC137533,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,17,17,False
9,TO_111_LH_F/113,10,1,1,NaN,na,TW_CERTIFICATION_ECU_278,MC137622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,17,17,False
10,TO_111_LH_F/113,11,1,1,NaN,na,TW_CERTIFICATION_ECU_279,MC137622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,17,17,False
11,TO_111_LH_F/113,12,1,1,NaN,na,CLEARANCE_SNR_ECU_1444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,17,17,False
12,TO_111_LH_F/113,13,1,1,NaN,na,CLEARANCE_SNR_ECU_1456,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,17,17,False
13,TO_111_LH_F/113,14,1,1,NaN,na,EQ_PDB_TAIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,17,17,False
14,TO_111_LH_F/113,15,1,1,NaN,na,GND_ACC_LP_LH_E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,17,17,False

In [24]:
def category_signal(row):
    if row["Signal Name"][:5]=='BATT_':
        return 1
    elif row["Signal Name"][:4]=='CAN_':
        return 2
    elif row["Signal Name"][:6]=='CANFD_':
        return 3
    elif row["Signal Name"][:4]=='GND_':
        return 4
    elif row["Signal Name"][:9]=='GNDR_GND_':
        return 5
    else:
        return 6

In [25]:
groupped2["signal_cat"]= groupped2.apply(lambda row:category_signal(row), axis=1 )

In [32]:
def category_signal2(row):
    if row["Signal Name"][-3:]=='_HI' or row["Signal Name"][-3:]=='_LO':
        return 1
    else:
        return 0

In [33]:
groupped2["signal_multicore"]= groupped2.apply(lambda row:category_signal2(row), axis=1 )

In [35]:
groupped2[["Signal Name","signal_cat","signal_multicore"]].tail(25)

                         Signal Name  signal_cat  signal_multicore
1693                 EQ_F:PHV_BATT_L           6                 0
1694           GND_CHG_INDICATOR_GND           4                 0
1695               GND_HV_BAT_JB_GND           4                 0
1696            GND_PHV_BAT_SYS_GND3           4                 0
1697           GND_PHV_BAT_SYS_HGND0           4                 0
1698           GND_PHV_BAT_SYS_HGND1           4                 0
1699                 HV_ECU-PHV_0059           6                 0
1700                 HV_ECU-PHV_2347           6                 0
1701                 HV_ECU-PHV_2355           6                 0
1702                 HV_ECU-PHV_2357           6                 0
1703           GND_CHG_INDICATOR_GND           4                 0
1704          EQ_F:IGCT_SCENE_NO.3_L           6                 0
1705  SLD_EFI_ECU-TNGA_KNOCK_SSR_101           6                 0
1706  SLD_EFI_ECU-TNGA_KNOCK_SSR_102           6                 0
1707                              na           6                 0
1708              EQ_NE_SSR-TNGA_NEP           6                 0
1709              EQ_NE_SSR-TNGA_NE-           6                 0
1710             EQ_NE_SSR-TNGA_VCNE           6                 0
1711    EQ_FUEL_PRESS_SSR_HI-TNGA_E2           6                 0
1712    EQ_FUEL_PRESS_SSR_HI-TNGA_PR           6                 0
1713    EQ_FUEL_PRESS_SSR_HI-TNGA_VC           6                 0
1714                              na           6                 0
1715                              na           6                 0
1716                              na           6                 0
1717                              na           6                 0

In [16]:
groupped2['Cat_Signal Name'] = groupped2["Signal Name"].astype('category').cat.codes
c = groupped2["Signal Name"].astype('category')
d = dict(enumerate(c.cat.categories))

In [17]:
def get_key(x,d):
    key_list=list(d.keys())
    val_list=list(d.values())
    ind=val_list.index(x["Pin PreferredSignal"])
    return key_list[ind]

In [18]:
groupped2['Cat_PreferredSignal']= groupped2.apply(lambda row: get_key(row,d),axis=1)

In [19]:
max_categories = groupped2['Cat_Signal Name'].max()

In [20]:
connectors={}
conn_to_save=""
for i, row in groupped2.iterrows():
    connector=groupped2.loc[i,"Connector Name"]
    pin=groupped2.loc[i,'Pin Name']
    
    if conn_to_save=="" or groupped2.loc[i-1,"Connector Name"]==connector:
        try:
        
            connectors[connector][pin]={}
        except:
            connectors[connector]={}
            connectors[connector][pin]={}
            
        
        conn_to_save="NO"
    else:
        conn_to_save=""
        try:
        
            connectors[connector][pin]={}
        except:
            connectors[connector]={}
            connectors[connector][pin]={}
    
    #Part Number at level of PIN
    PartNumber =groupped2.loc[i,'Connector PartNumber']
    connectors[connector]["PartNumber"]=PartNumber
    #prefered Signal
    PreferredSignal=groupped2.loc[i,'Pin PreferredSignal']
    connectors[connector][pin]['PreferredSignal']=PreferredSignal
    Cat_PreferredSignal=groupped2.loc[i,'Cat_PreferredSignal']
    connectors[connector][pin]['Cat_PreferredSignal']=Cat_PreferredSignal
    
    # Signal in that pin
    Signal =groupped2.loc[i,'Signal Name']
    connectors[connector][pin]['Signal']=Signal
    Cat_Signal =groupped2.loc[i,'Cat_Signal Name']
    connectors[connector][pin]['Cat_Signal']=Cat_Signal
    #Check Signal 1 preferred = Signal, 0 1 preferred != Signal, 2 both NaN 
    check_signal=groupped2.loc[i,'check_signal']
    connectors[connector][pin]['check_signal']=check_signal
    #Number of pins connector
    Num_Pins =groupped2.loc[i,'Num_Pins']
    connectors[connector][pin]['Num_Pins']=Num_Pins
    #Number of unique Pins in this connector
    Num_Pin_unique=groupped2.loc[i,'Num_Pin_unique']
    connectors[connector][pin]['Num_Pin_unique']=Num_Pin_unique
    #True if number of Pins is not the same of number of unique Pins
    more_signal_in_pin =groupped2.loc[i,'more_signal_in_pin']
    connectors[connector][pin]['more_signal_in_pin']=more_signal_in_pin

In [21]:
len(connectors['TO_111_LH_(121)'].keys())-1

40

In [22]:
connectors['TO_111_LH_(121)'][1]['Cat_Signal']

122

In [23]:
Cat_PreferredSignals=[]
for key in connectors['TO_111_LH_(121)'].keys():
    if key != 'PartNumber':
        Cat_PreferredSignals.append(connectors['TO_111_LH_(121)'][key]['Cat_PreferredSignal'])

In [24]:
Cat_PreferredSignals

[122,
 112,
 21,
 22,
 0,
 85,
 87,
 101,
 104,
 105,
 106,
 109,
 110,
 168,
 113,
 13,
 123,
 141,
 145,
 154,
 14,
 170,
 183,
 185,
 186,
 187,
 188,
 192,
 198,
 200,
 363,
 364,
 365,
 371,
 372,
 411,
 436,
 437,
 438,
 439]

In [26]:
import random

print(random.randint(0, max_categories ))

328

In [29]:
for i in range(10):
    print(random.random())

0.19390860591352121
0.4117601342592766
0.2341051535164067
0.5987311999011811
0.5406309364633021
0.45307958300608286
0.37384514556694515
0.9742615190244572
0.09579578478316053
0.3496493517997701

In [68]:
len(connectors.keys())

54

In [71]:
len(data['Signal Name'].unique()),len(data['Pin PreferredSignal'].unique())

(511, 393)

In [22]:
signal_view=data.groupby(["Pin PreferredSignal"]).agg({"Pin Name":[ "count", 'nunique'], "Connector Name":'nunique' })
signal_view.head(10)

                       Pin Name         Connector Name
                          count nunique        nunique
Pin PreferredSignal
BATT_ENG_E_W/P-ZR_+B          2       1              2
CANFD_ADS_C1_BUS_HI           8       4              4
CANFD_ADS_C1_BUS_LO           8       4              4
CANFD_DS_BUS_HI              14       6             10
CANFD_DS_BUS_LO              12       6              8
CANFD_DS_LOCAL1_BUS_HI        4       2              4
CANFD_DS_LOCAL1_BUS_LO        6       3              6
CANFD_DS_LOCAL3_BUS_HI        6       3              6
CANFD_DS_LOCAL3_BUS_LO        6       3              6
CANFD_PL_BUS_HI               4       1              4

In [23]:
groupped.to_csv("data/connectors.csv", index=False)

In [27]:
groupped['Connector PartNumber'].fillna("NOPARTNUMBER", inplace=True)
groupped.head(20)

,Connector Name,Pin Name,Pin Name nunique,Pin Name count,Connector PartNumber,Pin PreferredSignal,Signal Name,check_signal
0,TO_111_LH_(113),1,1,1,KANGO-12326,TW_S_CLEARANCE_SNR_002,TW_S_CLEARANCE_SNR_002,1
1,TO_111_LH_(113),2,1,1,KANGO-12326,TW_S_CLEARANCE_SNR_003,TW_S_CLEARANCE_SNR_003,1
2,TO_111_LH_(113),3,1,1,KANGO-12326,TW_S_CLEARANCE_SNR_017,TW_S_CLEARANCE_SNR_017,1
3,TO_111_LH_(113),4,1,1,KANGO-12326,TW_S_CLEARANCE_SNR_018,TW_S_CLEARANCE_SNR_018,1
4,TO_111_LH_(113),5,1,1,KANGO-12326,TW_S_REMOTE_ANT_001,TW_S_REMOTE_ANT_001,1
5,TO_111_LH_(113),6,1,1,KANGO-12326,TW_S_REMOTE_ANT_002,TW_S_REMOTE_ANT_002,1
6,TO_111_LH_(113),7,1,1,KANGO-12326,S_CLEARANCE_SNR_001,S_CLEARANCE_SNR_001,1
7,TO_111_LH_(113),8,1,1,KANGO-12326,S_CLEARANCE_SNR_016,S_CLEARANCE_SNR_016,1
8,TO_111_LH_(113),9,1,1,KANGO-12326,na,na,2
9,TO_111_LH_(113),10,1,1,KANGO-12326,na,na,2
10,TO_111_LH_(113),11,1,1,KANGO-12326,na,na,2
11,TO_111_LH_(113),12,1,1,KANGO-12326,na,na,2
12,TO_111_LH_(113),13,1,1,KANGO-12326,na,na,2
13,TO_111_LH_(121),1,1,1,NOPARTNUMBER,EQ_F:SBW_IGCT-HV_L,EQ_F:SBW_IGCT-HV_L,1
14,TO_111_LH_(121),2,1,1,NOPARTNUMBER,EQ_F:P-CON_MTR_NO.1_L,EQ_F:P-CON_MTR_NO.1_L,1
15,TO_111_LH_(121),3,1,1,NOPARTNUMBER,CAN_SBW_BUS_HI,CAN_SBW_BUS_HI,1
16,TO_111_LH_(121),4,1,1,NOPARTNUMBER,CAN_SBW_BUS_LO,CAN_SBW_BUS_LO,1
17,TO_111_LH_(121),5,1,1,NOPARTNUMBER,BATT_ENG_E_W/P-ZR_+B,BATT_ENG_E_W/P-ZR_+B,1
18,TO_111_LH_(121),6,1,1,NOPARTNUMBER,EQ_EFI_ECU-TNGA_LIN,EQ_EFI_ECU-TNGA_LIN,1
19,TO_111_LH_(121),7,1,1,NOPARTNUMBER,EQ_ENG_E_W/P-TNGA_PLUSB,EQ_ENG_E_W/P-TNGA_PLUSB,1