In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("data/inline_pins.csv")
data.head()

,Connector Name,Connector PartNumber,Pin Name,Pin PreferredSignal,Signal Name
0,TO_161_RH_(111_RH),NaN,30,EQ_F:PLUG_LOCK_L,EQ_F:PLUG_LOCK_L
1,TO_161_RH_(111_RH),NaN,35,S_AHB_G_ECU#2_024,S_AHB_G_ECU#2_024
2,TO_161_RH_(111_RH),NaN,36,S_AHB_G_ECU#2_025,S_AHB_G_ECU#2_025
3,TO_161_RH_(111_RH),NaN,11,EMB_S_PVM_APP-21CY_007,EMB_S_PVM_APP-21CY_007
4,TO_161_RH_(111_RH),NaN,24,EQ_F:AMD2_L,EQ_F:AMD2_L

In [3]:
data["Signal Name"].fillna("na", inplace=True)
data["Pin PreferredSignal"].fillna("na", inplace=True)

In [4]:
def signal_equal(row):
    if (row["Pin PreferredSignal"]== "na" and row["Signal Name"]== "na") :
        return 2
    elif row["Pin PreferredSignal"]==row["Signal Name"]:
        return 1
    else:
        return 0

In [5]:
data['check_signal']=data.apply(lambda row:signal_equal(row),axis=1)

In [6]:
connector_view=data.groupby(["Connector Name",'Pin Name']).agg({ "Pin PreferredSignal":['nunique','count'] })
connector_view.head(10)

                         Pin PreferredSignal
                                     nunique count
Connector Name  Pin Name
TO_111_LH_(113) 1                          1     1
                2                          1     1
                3                          1     1
                4                          1     1
                5                          1     1
                6                          1     1
                7                          1     1
                8                          1     1
                9                          1     1
                10                         1     1

In [7]:
levels=connector_view.index.nlevels
for i in reversed(range(0,levels)):
    connector_view.reset_index(level=i, inplace=True)

In [8]:
connector_view.columns=['Connector Name','Pin Name','Pin Name nunique',"Pin Name count"]
connector_view.tail(10)

         Connector Name  Pin Name  Pin Name nunique  Pin Name count
1806  TO_219_(121_TNGA)         4                 1               1
1807  TO_219_(121_TNGA)         5                 1               1
1808  TO_219_(121_TNGA)         6                 1               1
1809  TO_219_(121_TNGA)         7                 1               1
1810  TO_219_(121_TNGA)         8                 1               1
1811  TO_219_(121_TNGA)         9                 1               1
1812  TO_219_(121_TNGA)        10                 1               1
1813  TO_219_(121_TNGA)        11                 1               1
1814  TO_219_(121_TNGA)        12                 1               1
1815  TO_219_(121_TNGA)        13                 1               1

In [9]:
groupped= pd.merge(connector_view,data, on=['Connector Name','Pin Name'], how='inner')
len(connector_view),len(data),len(groupped)

(1816, 1816, 1816)

In [10]:
connector_view2=data.groupby(["Connector Name"]).agg({ 'Pin Name':['nunique','count'] })
connector_view2.head()

                           Pin Name
                            nunique count
Connector Name
TO_111_LH_(113)                  13    13
TO_111_LH_(121)                  40    40
TO_111_LH_(143)                   3     3
TO_111_LH_(161_LH)               50    50
TO_111_LH_LHD_(141_LH_LHD)       24    24

In [11]:
levels=connector_view2.index.nlevels
for i in reversed(range(0,levels)):
    connector_view2.reset_index(level=i, inplace=True)

In [12]:
connector_view2.columns=['Connector Name','Num_Pin_unique','Num_Pins']

In [13]:
connector_view2['more_signal_in_pin']=connector_view2["Num_Pin_unique"]!=connector_view2["Num_Pins"]
connector_view2.head(25)

                Connector Name  Num_Pin_unique  Num_Pins  more_signal_in_pin
0              TO_111_LH_(113)              13        13               False
1              TO_111_LH_(121)              40        40               False
2              TO_111_LH_(143)               3         3               False
3           TO_111_LH_(161_LH)              50        50               False
4   TO_111_LH_LHD_(141_LH_LHD)              24        24               False
5   TO_111_LH_RHD_(141_LH_RHD)              49        49               False
6           TO_111_RH_(161_RH)              44        44               False
7   TO_111_RH_LHD_(141_RH_LHD)              70        70               False
8   TO_111_RH_RHD_(141_RH_RHD)              46        46               False
9              TO_113_(111_LH)              13        13               False
10             TO_121_(111_LH)              40        40               False
11           TO_121_TNGA_(125)              10        10               False
12           TO_121_TNGA_(126)               8         8               False
13           TO_121_TNGA_(219)              13        13               False
14             TO_121_ZR_(124)               2         2               False
15             TO_124_(121_ZR)               2         2               False
16           TO_125_(121_TNGA)              10        10               False
17           TO_126_(121_TNGA)               8         8               False
18         TO_141_LH_(142)_18P              18        18               False
19             TO_141_LH_(152)              37        37               False
20      TO_141_LH_(161_LH)_62P              62        62               False
21             TO_141_LH_(171)              66        66               False
22  TO_141_LH_LHD_(111_LH_LHD)              24        24               False
23  TO_141_LH_RHD_(111_LH_RHD)              49        49               False
24             TO_141_RH_(151)              46        46               False

In [14]:
groupped2= pd.merge(groupped,connector_view2, on=['Connector Name'], how='inner')
len(groupped2),len(groupped)

(1816, 1816)

In [15]:
groupped2.head(15)

,Connector Name,Pin Name,Pin Name nunique,Pin Name count,Connector PartNumber,Pin PreferredSignal,Signal Name,check_signal,Num_Pin_unique,Num_Pins,more_signal_in_pin
0,TO_111_LH_(113),1,1,1,KANGO-12326,TW_S_CLEARANCE_SNR_002,TW_S_CLEARANCE_SNR_002,1,13,13,False
1,TO_111_LH_(113),2,1,1,KANGO-12326,TW_S_CLEARANCE_SNR_003,TW_S_CLEARANCE_SNR_003,1,13,13,False
2,TO_111_LH_(113),3,1,1,KANGO-12326,TW_S_CLEARANCE_SNR_017,TW_S_CLEARANCE_SNR_017,1,13,13,False
3,TO_111_LH_(113),4,1,1,KANGO-12326,TW_S_CLEARANCE_SNR_018,TW_S_CLEARANCE_SNR_018,1,13,13,False
4,TO_111_LH_(113),5,1,1,KANGO-12326,TW_S_REMOTE_ANT_001,TW_S_REMOTE_ANT_001,1,13,13,False
5,TO_111_LH_(113),6,1,1,KANGO-12326,TW_S_REMOTE_ANT_002,TW_S_REMOTE_ANT_002,1,13,13,False
6,TO_111_LH_(113),7,1,1,KANGO-12326,S_CLEARANCE_SNR_001,S_CLEARANCE_SNR_001,1,13,13,False
7,TO_111_LH_(113),8,1,1,KANGO-12326,S_CLEARANCE_SNR_016,S_CLEARANCE_SNR_016,1,13,13,False
8,TO_111_LH_(113),9,1,1,KANGO-12326,na,na,2,13,13,False
9,TO_111_LH_(113),10,1,1,KANGO-12326,na,na,2,13,13,False
10,TO_111_LH_(113),11,1,1,KANGO-12326,na,na,2,13,13,False
11,TO_111_LH_(113),12,1,1,KANGO-12326,na,na,2,13,13,False
12,TO_111_LH_(113),13,1,1,KANGO-12326,na,na,2,13,13,False
13,TO_111_LH_(121),1,1,1,NaN,EQ_F:SBW_IGCT-HV_L,EQ_F:SBW_IGCT-HV_L,1,40,40,False
14,TO_111_LH_(121),2,1,1,NaN,EQ_F:P-CON_MTR_NO.1_L,EQ_F:P-CON_MTR_NO.1_L,1,40,40,False

In [16]:
groupped2['Cat_Signal Name'] = groupped2["Signal Name"].astype('category').cat.codes
c = groupped2["Signal Name"].astype('category')
d = dict(enumerate(c.cat.categories))

In [17]:
def get_key(x,d):
    key_list=list(d.keys())
    val_list=list(d.values())
    ind=val_list.index(x["Pin PreferredSignal"])
    return key_list[ind]

In [18]:
groupped2['Cat_PreferredSignal']= groupped2.apply(lambda row: get_key(row,d),axis=1)

In [19]:
max_categories = groupped2['Cat_Signal Name'].max()

In [20]:
connectors={}
conn_to_save=""
for i, row in groupped2.iterrows():
    connector=groupped2.loc[i,"Connector Name"]
    pin=groupped2.loc[i,'Pin Name']
    
    if conn_to_save=="" or groupped2.loc[i-1,"Connector Name"]==connector:
        try:
        
            connectors[connector][pin]={}
        except:
            connectors[connector]={}
            connectors[connector][pin]={}
            
        
        conn_to_save="NO"
    else:
        conn_to_save=""
        try:
        
            connectors[connector][pin]={}
        except:
            connectors[connector]={}
            connectors[connector][pin]={}
    
    #Part Number at level of PIN
    PartNumber =groupped2.loc[i,'Connector PartNumber']
    connectors[connector]["PartNumber"]=PartNumber
    #prefered Signal
    PreferredSignal=groupped2.loc[i,'Pin PreferredSignal']
    connectors[connector][pin]['PreferredSignal']=PreferredSignal
    Cat_PreferredSignal=groupped2.loc[i,'Cat_PreferredSignal']
    connectors[connector][pin]['Cat_PreferredSignal']=Cat_PreferredSignal
    
    # Signal in that pin
    Signal =groupped2.loc[i,'Signal Name']
    connectors[connector][pin]['Signal']=Signal
    Cat_Signal =groupped2.loc[i,'Cat_Signal Name']
    connectors[connector][pin]['Cat_Signal']=Cat_Signal
    #Check Signal 1 preferred = Signal, 0 1 preferred != Signal, 2 both NaN 
    check_signal=groupped2.loc[i,'check_signal']
    connectors[connector][pin]['check_signal']=check_signal
    #Number of pins connector
    Num_Pins =groupped2.loc[i,'Num_Pins']
    connectors[connector][pin]['Num_Pins']=Num_Pins
    #Number of unique Pins in this connector
    Num_Pin_unique=groupped2.loc[i,'Num_Pin_unique']
    connectors[connector][pin]['Num_Pin_unique']=Num_Pin_unique
    #True if number of Pins is not the same of number of unique Pins
    more_signal_in_pin =groupped2.loc[i,'more_signal_in_pin']
    connectors[connector][pin]['more_signal_in_pin']=more_signal_in_pin

In [21]:
len(connectors['TO_111_LH_(121)'].keys())-1

40

In [22]:
connectors['TO_111_LH_(121)'][1]['Cat_Signal']

122

In [23]:
Cat_PreferredSignals=[]
for key in connectors['TO_111_LH_(121)'].keys():
    if key != 'PartNumber':
        Cat_PreferredSignals.append(connectors['TO_111_LH_(121)'][key]['Cat_PreferredSignal'])

In [24]:
Cat_PreferredSignals

[122,
 112,
 21,
 22,
 0,
 85,
 87,
 101,
 104,
 105,
 106,
 109,
 110,
 168,
 113,
 13,
 123,
 141,
 145,
 154,
 14,
 170,
 183,
 185,
 186,
 187,
 188,
 192,
 198,
 200,
 363,
 364,
 365,
 371,
 372,
 411,
 436,
 437,
 438,
 439]

In [26]:
import random

print(random.randint(0, max_categories ))

328

In [29]:
for i in range(10):
    print(random.random())

0.19390860591352121
0.4117601342592766
0.2341051535164067
0.5987311999011811
0.5406309364633021
0.45307958300608286
0.37384514556694515
0.9742615190244572
0.09579578478316053
0.3496493517997701

In [68]:
len(connectors.keys())

54

In [71]:
len(data['Signal Name'].unique()),len(data['Pin PreferredSignal'].unique())

(511, 393)

In [22]:
signal_view=data.groupby(["Pin PreferredSignal"]).agg({"Pin Name":[ "count", 'nunique'], "Connector Name":'nunique' })
signal_view.head(10)

                       Pin Name         Connector Name
                          count nunique        nunique
Pin PreferredSignal
BATT_ENG_E_W/P-ZR_+B          2       1              2
CANFD_ADS_C1_BUS_HI           8       4              4
CANFD_ADS_C1_BUS_LO           8       4              4
CANFD_DS_BUS_HI              14       6             10
CANFD_DS_BUS_LO              12       6              8
CANFD_DS_LOCAL1_BUS_HI        4       2              4
CANFD_DS_LOCAL1_BUS_LO        6       3              6
CANFD_DS_LOCAL3_BUS_HI        6       3              6
CANFD_DS_LOCAL3_BUS_LO        6       3              6
CANFD_PL_BUS_HI               4       1              4

In [23]:
groupped.to_csv("data/connectors.csv", index=False)

In [27]:
groupped['Connector PartNumber'].fillna("NOPARTNUMBER", inplace=True)
groupped.head(20)

,Connector Name,Pin Name,Pin Name nunique,Pin Name count,Connector PartNumber,Pin PreferredSignal,Signal Name,check_signal
0,TO_111_LH_(113),1,1,1,KANGO-12326,TW_S_CLEARANCE_SNR_002,TW_S_CLEARANCE_SNR_002,1
1,TO_111_LH_(113),2,1,1,KANGO-12326,TW_S_CLEARANCE_SNR_003,TW_S_CLEARANCE_SNR_003,1
2,TO_111_LH_(113),3,1,1,KANGO-12326,TW_S_CLEARANCE_SNR_017,TW_S_CLEARANCE_SNR_017,1
3,TO_111_LH_(113),4,1,1,KANGO-12326,TW_S_CLEARANCE_SNR_018,TW_S_CLEARANCE_SNR_018,1
4,TO_111_LH_(113),5,1,1,KANGO-12326,TW_S_REMOTE_ANT_001,TW_S_REMOTE_ANT_001,1
5,TO_111_LH_(113),6,1,1,KANGO-12326,TW_S_REMOTE_ANT_002,TW_S_REMOTE_ANT_002,1
6,TO_111_LH_(113),7,1,1,KANGO-12326,S_CLEARANCE_SNR_001,S_CLEARANCE_SNR_001,1
7,TO_111_LH_(113),8,1,1,KANGO-12326,S_CLEARANCE_SNR_016,S_CLEARANCE_SNR_016,1
8,TO_111_LH_(113),9,1,1,KANGO-12326,na,na,2
9,TO_111_LH_(113),10,1,1,KANGO-12326,na,na,2
10,TO_111_LH_(113),11,1,1,KANGO-12326,na,na,2
11,TO_111_LH_(113),12,1,1,KANGO-12326,na,na,2
12,TO_111_LH_(113),13,1,1,KANGO-12326,na,na,2
13,TO_111_LH_(121),1,1,1,NOPARTNUMBER,EQ_F:SBW_IGCT-HV_L,EQ_F:SBW_IGCT-HV_L,1
14,TO_111_LH_(121),2,1,1,NOPARTNUMBER,EQ_F:P-CON_MTR_NO.1_L,EQ_F:P-CON_MTR_NO.1_L,1
15,TO_111_LH_(121),3,1,1,NOPARTNUMBER,CAN_SBW_BUS_HI,CAN_SBW_BUS_HI,1
16,TO_111_LH_(121),4,1,1,NOPARTNUMBER,CAN_SBW_BUS_LO,CAN_SBW_BUS_LO,1
17,TO_111_LH_(121),5,1,1,NOPARTNUMBER,BATT_ENG_E_W/P-ZR_+B,BATT_ENG_E_W/P-ZR_+B,1
18,TO_111_LH_(121),6,1,1,NOPARTNUMBER,EQ_EFI_ECU-TNGA_LIN,EQ_EFI_ECU-TNGA_LIN,1
19,TO_111_LH_(121),7,1,1,NOPARTNUMBER,EQ_ENG_E_W/P-TNGA_PLUSB,EQ_ENG_E_W/P-TNGA_PLUSB,1