In [1]:
from agent_pinner.pre_processing import *
import warnings

import pandas as pd
from pandas.core.common import SettingWithCopyWarning

warnings.simplefilter(action="ignore", category=SettingWithCopyWarning)

In [2]:
import numpy as np
import gym
from gym import spaces
import random
from gym.utils import seeding



class conn(gym.Env):
       
  #Custom Environment that follows gym interface.

      # observation space
    #1 number pins [0,Num_Pin_unique_max]
    #2 distance to center pin [0,11]bucket
    #3 number of neighbors[0,Num_Pin_unique_max-1]
    #4 internal/external[0,1]
    #5 mean_neighbors [0,11]bucket
    #6 distance centroide [0,11]bucket
    #7 signal category [0,7]
    #8 color wire categorical[0,max_color_categories]
    #9 thickness wire continuous[0,51]bucket
    #10 multicore yes/no [0,1]
    #11 number of internal pins [0,Num_Pin_unique_max//2]
    #12 nosignal [0,1]
    #13 ismulticore [0,1]
    #14 category multicore [0,max_multicore_categories]

  # Because of google colab, we cannot implement the GUI ('human' render mode)
    metadata = {'render.modes': ['console']}
  # Define constants for clearer code


    def __init__(self, Num_Pin_unique_max, max_color_categories, max_categories_multicore, number_pins=100):

        super(conn, self).__init__()
        # numero de pins connector -1 due to PartNumber
        # space number of pins of this connector
        self.lae=14
        self.p=Num_Pin_unique_max
        self.c=max_color_categories
        self.m=max_categories_multicore
        self.action_space = spaces.Box(low=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0]), \
                                      high=np.array([self.p+1,11,self.p,1,11,11,8,self.c+1,51,1,int(self.p//2),1,1, self.m+1]), \
                                       shape=(self.lae,))
        # observation space low/High bound number of diferent signals this connector
        # size, vector length number of pins
        self.observation_space = spaces.Box(low=np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0]), \
                                      high=np.array([self.p+1,11,self.p,1,11,11,8,self.c+1,51,1,int(self.p//2),1,1, self.m+1]), \
                                            shape=(self.lae,))
        # estate list of actions
        self.agent_pos=0
        self.bins10= np.linspace(1, 10, 11)
        self.bins100= np.linspace(0, 100, 101)
        self.binsp= np.linspace(0, self.p, self.p+1)# bin number of pins
        self.binsc= np.linspace(0, self.c, self.c+1)#  bin number of 
        self.binsm= np.linspace(0, self.m, self.m+1)
        self.number_pins=number_pins
        self.signal_in_conector=[]
        self.int_ext_in_conector=[]
        self.color_in_conector=[]
        self.number_pin_already_in_conector=[]
        self.distances_in_conector=[]
        self.no_signal_in_conector=[]
        self.reward=0
        return        

    def _seed(self, seed=None):
        self.np_random, seed = seeding.np_random(seed)
        return [seed]

    def reset(self):
        self.state = np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0])#np.zeros(self.lae, dtype='int')
        self.signal_in_conector=[]
        self.int_ext_in_conector=[]
        self.color_in_conector=[]
        self.number_pin_already_in_conector=[]
        self.distances_in_conector=[]
        self.no_signal_in_conector=[]
        self.agent_pos=0
        self.reward=0
        return self.state

    def render(self, mode='console'):
        if mode != 'console':
            raise NotImplementedError()
          # agent is represented as a cross, rest as a dot

        return



    def get_reward_cat(self,signal_cat, int_ext,distance, no_signal_pin):
        # save the previous rewards
        reward=0
        if signal_cat in self.signal_in_conector and signal_cat != 7:
            reward = reward -1

        else:
            reward = reward + 4
        # higvoltage close in internal PIN or close to an empty cavity
        if (signal_cat in [1,6]) and int_ext == 1 :
            reward =reward +5
        elif (signal_cat in [1,6]) and no_signal_pin ==1:
            reward =reward +2
        else:
            reward =reward -5
            
        # if GROUND is present reward more when far from High Power categories
        if (signal_cat in [1,6]) and 4 in self.signal_in_conector:
            reward = reward - int((distance +10)//4)
        else:
            reward = reward + int((distance +10)//4)
            
        if (signal_cat in [1,6]) and 5 in self.signal_in_conector:
            reward = reward - int((distance +10)//4)
        else:
            reward = reward + int((distance +10)//4)
        # if High power     is present reward more when far from ground categories
        if (signal_cat in [4,5]) and 1 in self.signal_in_conector:
            reward = reward - int((distance +10)//4)
        else:
            reward = reward + int((distance +10)//4)
            
        if (signal_cat in [4,5]) and 6 in self.signal_in_conector:
            reward = reward - int((distance +10)//4)
        else:
            reward = reward + int((distance +10)//4)
        #reward more high power far from other signals
        if signal_cat ==6 and len(self.distances_in_conector)>1:
            for ele in self.distances_in_conector:
                diff=abs(distance-ele)
                reward = reward + int((diff +10)//4)

        

        return reward

    def get_reward_color(self, color_cat):
        # save the previous rewards
        reward=0
        if color_cat in self.color_in_conector:
            reward = reward -4

        else:
            reward = reward + 4
        return reward

    def get_reward_int_ext(self, number_internal):
        # save the previous rewards
        reward=0
        if number_internal>  len(self.number_pin_already_in_conector):
            reward = reward -4

        else:
            reward = reward + 4
        return reward
    
    def get_reward_multicore_out(self, distance, multicore):
        # save the previous rewards
        reward=0
        if multicore ==1:
            reward = reward + int((distance +10)//2) 

        else:
            reward = reward - int((distance +10)//2)
        return reward
    
    def get_bin_s(self,n, bins):
        _bin=0
        for i in range(0,len(bins)):
            if bins[i]>= n:
                _bin=i-1
                break
        return _bin
    
    def get_zero_one(self, n):
        if n < 0.1:
            return 0
        else:
            return 1
    def get_reward_empty_cavities(self, number_of_empty_cavities):
        reward =0
        # if high power in connector reward more empty cavities 
        if 6 in self.signal_in_conector or 1 in self.signal_in_conector:
            reward = int((10 + number_of_empty_cavities )//10)
        elif number_of_empty_cavities <2 :
            reward = reward - 2
                
        return reward
        
    def calculate_reward(self,action):
        reward=0
        distance=self.get_bin_s(action[1],self.bins10) # distance to the center
        int_ext= self.get_zero_one(action[3]) # internal External Flag
        signal_cat=int(action[6]) # signal Category
        color_cat=int(action[7]) # color Category
        multicore=self.get_zero_one(action[9]) # multicore
        number_internal=int(action[10]) # number of internal pins
        no_signal_pin=self.get_zero_one(action[11]) # is an empty cavity
        number_of_empty_cavities=self.no_signal_in_conector.count(1) # number of empty cavities

        #print(distance)
        reward = reward + self.get_reward_cat( signal_cat, int_ext, distance,no_signal_pin)
        reward = reward + self.get_reward_color(color_cat)
        reward = reward + self.get_reward_int_ext(number_internal)
        reward = reward + self.get_reward_multicore_out(distance, multicore )
        reward = reward + self.get_reward_empty_cavities(number_of_empty_cavities )
        # append what you see to the observation space
        self.signal_in_conector.append(signal_cat)
        self.int_ext_in_conector.append(int_ext)
        self.color_in_conector.append(color_cat)
        self.distances_in_conector.append(distance)
        self.no_signal_in_conector.append(no_signal_pin)
        if int_ext==1:
            self.number_pin_already_in_conector.append(number_internal)
        
        return reward




    def step(self, action):
        
        #real=self.get_real(action) #  real values
        #calculate Reward
        self.reward = self.reward+self.calculate_reward(action)
        #print(self.reward)


        # Account for the boundaries of the grid
        self.agent_pos =  self.agent_pos + 1
        self.terminal = bool(self.agent_pos > self.p) 

        # Optionally we can pass additional info, we are not using that for now
        info = {}

        return self.state, self.reward, self.terminal, info

In [3]:
test=np.linspace(1, 12, 11)
test

array([ 1. ,  2.1,  3.2,  4.3,  5.4,  6.5,  7.6,  8.7,  9.8, 10.9, 12. ])

In [4]:
data1 = pd.read_csv("agent_pinner/data/symbol_pins.csv")
symbols=get_neighbors_partnumbers(data1)

data = pd.read_csv("agent_pinner/data/inline_pins.csv")
data, d, _ = preprocess_data(data, symbols)

connectors_dicc=create_connector_dicc(data)
#connector="TO_111_LH_F/143_3P"

In [8]:
len(data['Connector Name'].unique())

60

In [15]:
data.columns

Index(['Connector Name', 'Pin Name', 'Pin Name nunique', 'Pin Name count',
       'Connector PartNumber', 'Pin PreferredSignal', 'Signal Name',
       'Wire WireColor', 'Wire WireCSA', 'MulticoreInnerToOutter1',
       'MulticoreInnerToOutter2', 'MulticoreInnerToOutter4',
       'MulticoreInnerToOutter3', 'MulticoreInnerToOutter5',
       'MulticoreInnerToOutter6', 'MulticoreInnerToOutter7',
       'MulticoreInnerToOutter8', 'MulticoreInnerToOutter9', 'check_signal',
       'Num_Pin_unique', 'Num_Pins', 'more_signal_in_pin', 'signal_cat',
       'signal_multicore', 'Cat_Signal Name', 'dicc_signals',
       'Cat_PreferredSignal', 'Cat_Wire_WireColor', 'Cat_Wire_WireColor_max',
       'Wire_WireCSA_min', 'Wire_WireCSA_max', 'Num_Pin_unique_max',
       'no_signal_pin', 'multicore_same', 'is_multicore',
       'max_categories_multicore', 'Symbol Name', 'Pin CenterY', 'Pin CenterX',
       'Pin Width', 'Pin Height', 'distance_to_center', 'neighbors',
       'neighbors_length', 'internal_pin', 'mean_neighbors',
       'centroide_distance', 'number_internal_pin', 'min_distance',
       'max_distance'],
      dtype='object')

In [10]:
connector='TO_169_F/161_RH_13P'

In [28]:
d_models=[]
model_connectors={}

for connector in connectors_dicc.keys():
    num_pins=connectors_dicc[connector]['1']['Num_Pins']
    
    if not(num_pins in d_models):
        d_models.append(num_pins)
        
        model_connectors[num_pins]=[]
    if not(connector in model_connectors[num_pins]):
         model_connectors[num_pins].append(connector)
        
d_models

[17,
 28,
 3,
 53,
 49,
 50,
 41,
 35,
 42,
 10,
 8,
 13,
 2,
 18,
 55,
 31,
 52,
 25,
 24,
 19,
 38,
 47,
 21,
 5]

In [40]:
model_connectors[28]#'TO_111_LH_F/121'

['TO_111_LH_F/121', 'TO_121_F/111_LH', 'TO_141_LH_F/152', 'TO_152_F/141_LH']

In [151]:
def get_bin_10(n,bins10):
    _bin=10
    for i in range(0,len(bins10)):
        if bins10[i]> n:
            _bin=1
            break
    return _bin

In [152]:
Num_Pin_unique_max=connectors_dicc[connector]['1']['Num_Pin_unique_max']
Num_Pin_unique_max

55

In [153]:
max_color_categories=Cat_Wire_WireColor=connectors_dicc[connector]['1']['Cat_Wire_WireColor_max']
max_color_categories

30

In [154]:
max_categories_multicore=Cat_Wire_WireColor=connectors_dicc[connector]['1']['max_categories_multicore']
max_categories_multicore

8

In [155]:
Num_Pins= connectors_dicc[connector]['1']['Num_Pins']
Num_Pins

13

In [156]:
def get_pin_signal(sig_conn,i):
    bins_distance= np.linspace(sig_conn['1']['min_distance'], sig_conn['1']['max_distance'], 11)
    bins_thickness= np.linspace(sig_conn['1']['Wire_WireCSA_min'], sig_conn['1']['Wire_WireCSA_max'], 51)
    Num_Pins=sig_conn[str(i)]['Num_Pins']
    distance_to_center=get_bin_10(sig_conn[str(i)]['distance_to_center'], bins_distance)
    neighbors_length=sig_conn[str(i)]['neighbors_length']
    internal_pin = 1 if sig_conn[str(i)]['internal_pin'] =='True' else 0
    mean_neighbors=get_bin_10(sig_conn[str(i)]['mean_neighbors'], bins_distance)
    centroide_distance=get_bin_10(sig_conn[str(i)]['centroide_distance'], bins_distance)
    signal_group=sig_conn[str(i)]['signal_group']
    Cat_Wire_WireColor=sig_conn[str(i)]['Cat_Wire_WireColor']
    WireCSA=get_bin_10(sig_conn[str(i)]['WireCSA'], bins_thickness)
    is_multicore = 0 if sig_conn[str(i)]['is_multicore'] =='na' else 1
    number_internal_pin= sig_conn[str(i)]['number_internal_pin']
    nosignal = sig_conn[str(i)]['no_signal_pin']
    ismulticore= sig_conn[str(i)]['is_multicore']
    cat_multicore=sig_conn[str(i)]['multicore_same']
    return list([Num_Pins,distance_to_center,neighbors_length,internal_pin,mean_neighbors,
                 centroide_distance,signal_group,Cat_Wire_WireColor,WireCSA,is_multicore,
                 number_internal_pin,nosignal,ismulticore, cat_multicore])

In [157]:
get_pin_signal(connectors_dicc[connector],1)

[13, 10, 3, 0, 1, 1, 6, 26, 1, 1, 2.0, 0, 0, 1]

In [158]:
#action space == number of PIN,s

    # observation space
   #1 number pins [0,Num_Pin_unique_max]
    #2 distance to center pin [0,11]bucket
    #3 number of neighbors[0,Num_Pin_unique_max-1]
    #4 internal/external[0,1]
    #5 mean_neighbors [0,11]bucket
    #6 distance centroide [0,11]bucket
    #7 signal category [0,7]
    #8 color wire categorical[0,max_color_categories]
    #9 thickness wire continuous[0,51]bucket
    #10 multicore yes/no [0,1]
    #11 number of internal pins [0,Num_Pin_unique_max//2]
    #12 nosignal [0,1]
    #13 ismulticore [0,1]
    #14 category multicore [0,max_multicore_categories]

In [159]:
from stable_baselines3.common.env_checker import check_env

In [206]:
env = conn(Num_Pin_unique_max, max_color_categories,max_categories_multicore, Num_Pins) 
obs = env.reset()
env.render()

In [207]:
check_env(env, warn=True)

C:\Users\User\AppData\Roaming\Python\Python38\site-packages\stable_baselines3\common\env_checker.py:231: UserWarning: We recommend you to use a symmetric and normalized Box action space (range=[-1, 1]) cf https://stable-baselines3.readthedocs.io/en/master/guide/rl_tips.html
  warnings.warn(

In [162]:
print(env.observation_space)
print(env.action_space)
print(env.action_space.sample())

Box(0.0, 56.0, (14,), float32)
Box(0.0, 56.0, (14,), float32)
[27.033718    7.2732325  53.257896    0.34909415  0.97068226  5.181375
  3.2085385  15.310357   28.473034    0.06615737 25.46332     0.46346766
  0.5584964   2.4409416 ]

In [163]:
import sys

In [164]:
def gen_step():
    step=[]
    step.append(random.randint(0, Num_Pin_unique_max+1 ))
    step.append(random.randint(0,11))
    step.append(random.randint(0, Num_Pin_unique_max ))
    step.append(random.randint(0, 1 ))
    step.append(random.randint(0,11))
    step.append(random.randint(0,11))
    step.append(random.randint(0, 8 ))
    step.append(random.randint(0, max_color_categories ))
    step.append(random.randint(0,11))
    step.append(random.randint(0,1))
    step.append(random.randint(0,1))
    step.append(random.randint(0,int(Num_Pin_unique_max//2)))
    step.append(random.randint(0,1))
    step.append(random.randint(0,1))
    step.append(random.randint(0, max_categories_multicore ))
    return step
    
#[self.p+1,11,self.p,1,11,11,8,self.c+1,51,1,int(self.p//2)]

In [165]:
obs = env.reset()
env.render()
n_steps = 1300
#GO_LEFT=random.randint(0, max_categories )
for step in range(n_steps):
    #print("Step {}".format(step + 1))
    GO_LEFT=gen_step()
    obs, reward, done, info = env.step(GO_LEFT)
    #print('obs=', obs, 'reward=', reward, 'done=', done)
    env.render()
    if done:
        print("Goal reached!", "reward=", reward)
        obs = env.reset()

8
16
27
53
89
121
141
147
175
175
195
198
194
216
266
273
285
293
366
441
465
542
533
535
545
633
655
658
742
752
766
795
812
827
936
1055
1070
1097
1094
1104
1233
1249
1260
1278
1301
1476
1480
1495
1636
1656
1646
1666
1671
1863
1888
1888
Goal reached! reward= 1888
24
40
40
61
64
79
98
113
157
178
211
221
244
250
246
247
255
324
385
390
396
395
395
405
434
445
462
476
492
504
517
529
541
550
567
572
575
580
595
601
614
628
651
662
673
843
851
863
874
872
888
1046
1049
1058
1050
1057
Goal reached! reward= 1057
22
31
38
49
59
83
96
91
102
105
114
135
186
202
206
213
215
248
257
248
257
256
274
275
279
296
325
336
345
361
375
398
405
435
438
454
467
624
626
617
613
615
759
749
762
768
785
803
819
825
972
995
1001
1019
1022
1013
Goal reached! reward= 1013
22
43
58
89
106
115
133
148
179
197
200
209
217
206
228
242
258
264
274
284
298
382
389
411
412
501
506
504
590
590
602
618
624
638
661
684
701
704
729
740
758
748
739
749
753
761
773
802
820
833
838
851
871
874
893
918
Goal reached! reward= 918
10
28
38
53
77
105
131
143
138
192
207
230
242
242
250
257
270
273
285
313
331
339
331
407
420
421
433
438
438
467
474
473
477
481
484
489
520
543
553
565
578
596
624
770
761
766
779
770
762
756
750
769
780
796
809
800
Goal reached! reward= 800
30
38
45
55
72
92
110
134
165
175
176
177
187
198
211
219
223
215
244
316
334
351
361
385
397
488
489
517
546
651
662
676
670
670
682
685
822
844
854
866
870
869
883
901
904
927
944
962
957
974
982
988
987
1000
1005
996
Goal reached! reward= 996
23
27
65
78
98
115
147
153
164
199
210
217
221
243
264
277
294
303
304
376
378
383
392
407
412
441
450
468
481
501
513
527
548
566
580
581
600
623
635
657
680
709
698
701
705
712
743
774
937
1095
1103
1096
1100
1118
1132
1124
Goal reached! reward= 1124
1
4
24
38
69
98
106
109
129
140
153
170
176
204
225
253
248
267
275
288
300
314
324
335
337
342
348
361
378
383
393
500
612
634
626
620
651
673
698
717
714
723
855
866
1015
1022
1037
1041
1054
1061
1085
1096
1090
1108
1117
1113
Goal reached! reward= 1113
19
37
52
92
98
135
141
141
174
206
218
230
249
246
249
266
288
291
302
336
341
410
422
431
422
451
452
458
492
496
505
508
518
517
518
527
558
583
711
714
738
751
883
1039
1070
1063
1069
1091
1117
1119
1122
1138
1145
1160
1168
1174
Goal reached! reward= 1174
24
28
54
74
90
89
101
123
155
194
210
222
237
251
278
293
293
287
288
288
304
316
318
323
404
422
423
416
421
414
419
429
437
439
546
547
578
594
613
619
644
655
678
690
710
734
737
880
894
1041
1057
1063
1071
1084
1111
1294
Goal reached! reward= 1294
9
39
51
66
107
119
132
143
130
137
147
170
204
220
279
293
295
323
318
334
343
361
351
366
368
402
408
409
410
426
515
517
538
551
557
575
584
591
591
707
711
729
746
752
754
764
782
811
813
815
818
824
833
858
868
871
Goal reached! reward= 871
18
21
36
44
56
63
89
115
121
139
159
159
208
204
228
255
266
275
288
304
310
318
352
351
352
360
366
371
394
408
409
401
413
508
524
532
539
549
551
558
705
710
704
834
839
970
976
996
1022
1045
1047
1059
1081
1074
1074
1235
Goal reached! reward= 1235
13
16
27
27
52
61
92
102
121
142
154
164
173
188
192
214
284
298
323
315
336
344
352
356
442
446
456
478
570
587
714
722
728
735
751
754
755
772
774
799
789
800
803
807
829
845
862
888
908
923
944
954
948
954
958
963
Goal reached! reward= 963
31
38
76
75
101
96
122
153
156
176
196
248
265
270
287
315
377
388
401
479
532
548
557
572
594
597
610
619
641
664
685
688
791
915
942
956
986
996
1128
1243
1270
1283
1285
1309
1316
1319
1325
1337
1348
1355
1362
1380
1399
1598
1605
1623
Goal reached! reward= 1623
8
25
36
68
88
120
134
176
183
210
233
248
258
279
335
393
404
404
433
437
455
465
463
498
511
509
529
520
529
538
658
669
672
688
695
705
706
709
713
864
876
879
892
896
905
915
947
951
953
943
950
975
1145
1158
1357
1364
Goal reached! reward= 1364
10
32
64
82
102
105
118
150
163
180
222
263
264
309
306
369
376
384
384
406
427
439
443
509
580
597
606
627
640
650
666
672
697
715
721
836
854
864
875
890
896
911
1057
1048
1052
1055
1059
1083
1087
1111
1113
1132
1156
1162
1166
1169
Goal reached! reward= 1169
17
44
63
68
84
111
139
166
180
186
191
194
198
232
232
253
275
293
308
307
318
325
342
342
357
373
372
363
351
440
443
453
458
456
471
477
479
483
484
493
614
726
737
760
901
903
895
895
899
900
911
916
1068
1241
1246
1237
Goal reached! reward= 1237
24
47
75
82
102
130
157
158
165
189
211
229
257
305
314
302
330
397
403
393
422
503
508
522
526
528
552
667
697
724
749
760
771
773
776
782
784
788
799
922
927
943
960
973
1109
1275
1269
1272
1263
1288
1437
1443
1448
1460
1469
1471
Goal reached! reward= 1471
10
32
46
62
60
73
104
110
126
133
126
143
145
147
147
159
188
194
213
233
234
233
235
322
408
428
525
529
517
514
627
639
648
746
764
766
782
806
829
840
851
859
852
983
1003
1027
1172
1183
1196
1213
1218
1222
1227
1232
1236
1260
Goal reached! reward= 1260
31
55
89
93
105
117
138
158
179
183
205
215
236
305
314
331
340
396
384
398
415
486
507
508
499
496
506
507
512
525
538
643
654
791
808
806
827
832
843
872
889
905
907
1018
1042
1047
1069
1208
1237
1227
1231
1237
1243
1251
1255
1436
Goal reached! reward= 1436
15
24
58
78
106
117
145
204
215
227
255
273
287
282
299
303
324
332
339
357
384
376
385
386
386
387
457
462
483
513
537
539
570
560
577
703
709
709
713
730
752
770
885
1022
1025
1023
1024
1034
1039
1068
1077
1081
1096
1294
1288
1282
Goal reached! reward= 1282
2
12
27
36
55
76
116
130
157
169
178
195
212
215
216
224
253
260
335
336
370
371
387
402
405
423
422
432
429
433
452
451
468
480
482
503
509
526
528
658
781
785
822
824
849
853
865
871
884
888
901
920
1084
1224
1232
1259
Goal reached! reward= 1259
3
32
42
62
93
124
158
158
161
179
222
229
249
244
306
310
307
310
319
340
404
406
480
476
571
595
598
619
725
832
935
942
964
975
1078
1070
1210
1337
1350
1354
1366
1377
1394
1396
1391
1550
1566
1602
1626
1636
1810
1818
1823
1829
2026
2033
Goal reached! reward= 2033
1
14
50
66
99
109
120
167
184
222
219
236

In [166]:
from stable_baselines3.common.vec_env import DummyVecEnv
env_train = DummyVecEnv([lambda: conn(Num_Pin_unique_max, max_color_categories, max_categories_multicore, Num_Pins)])

In [167]:
from stable_baselines3 import DQN, TD3, PPO, A2C, SAC, DDPG
model = SAC('MlpPolicy', env_train, verbose=2, create_eval_env=True)

Using cpu device

In [168]:
import time
time1=time.time()
model.learn(10005)
time2=time.time()

print(time2-time1)

9
14
21
32
50
63
82
86
99
111
162
190
191
200
201
228
222
245
246
275
294
314
325
335
357
444
459
489
516
539
553
546
659
675
689
701
832
854
876
887
909
910
926
957
974
978
983
1012
1019
1205
1222
1229
1255
1266
1460
1483
9
12
24
42
49
61
67
77
115
128
147
197
229
237
263
267
264
252
275
284
296
311
324
333
335
350
366
383
403
424
445
546
657
672
690
699
708
718
747
767
770
781
805
835
859
876
894
916
922
937
944
967
991
999
1003
1010
2
24
42
46
71
107
105
110
137
149
160
164
164
159
154
181
196
196
208
228
247
269
281
283
365
382
398
410
439
447
448
453
469
479
482
484
494
495
518
534
545
544
574
601
618
760
767
786
792
795
818
835
845
862
865
878
14
33
49
68
86
99
108
102
108
111
132
137
156
178
185
197
231
250
259
278
282
304
326
411
426
518
526
548
553
583
601
601
616
741
768
778
794
784
801
807
818
839
842
859
867
878
907
939
945
957
962
999
1016
1186
1200
1206
---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 27       |
|    time_elapsed    | 8        |
|    total timesteps | 224      |
| train/             |          |
|    actor_loss      | -36.7    |
|    critic_loss     | 3.52e+05 |
|    ent_coef        | 0.964    |
|    ent_coef_loss   | -0.644   |
|    learning_rate   | 0.0003   |
|    n_updates       | 123      |
---------------------------------
0
16
14
30
37
49
64
76
87
104
131
151
202
207
215
235
240
262
276
293
301
309
320
325
390
411
427
435
441
461
469
490
501
524
533
542
543
552
561
587
596
605
614
625
634
655
676
681
690
699
719
728
729
738
755
764
10
15
12
17
30
27
32
37
46
56
64
64
72
80
88
96
104
112
120
120
128
128
148
156
164
172
180
200
208
216
224
232
232
240
248
256
276
284
309
317
325
333
341
341
341
357
365
385
385
393
401
409
417
425
425
425
18
23
28
41
46
51
64
61
66
63
60
70
78
86
94
94
102
118
134
134
142
150
158
166
174
174
182
190
198
203
212
220
228
224
220
233
253
253
257
265
265
278
282
290
290
294
299
304
411
432
440
460
477
482
482
490
10
32
37
42
52
62
75
80
81
86
109
105
145
141
146
182
187
192
197
202
207
212
217
230
235
240
245
250
263
268
273
278
283
288
293
298
303
308
313
318
323
328
333
338
343
348
353
358
363
368
373
378
383
388
393
398
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 21       |
|    time_elapsed    | 20       |
|    total timesteps | 448      |
| train/             |          |
|    actor_loss      | -446     |
|    critic_loss     | 1.42e+05 |
|    ent_coef        | 0.997    |
|    ent_coef_loss   | 0.039    |
|    learning_rate   | 0.0003   |
|    n_updates       | 347      |
---------------------------------
10
20
30
32
42
44
54
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100
114
124
134
144
154
156
158
160
232
245
250
255
260
273
278
283
296
309
314
319
324
329
334
339
344
349
354
367
372
377
10
12
14
24
34
44
54
64
66
68
70
72
82
92
94
96
98
100
102
104
106
108
110
112
114
116
118
120
134
136
138
140
208
213
218
223
228
233
311
312
474
491
502
507
512
525
719
725
717
742
755
760
752
760
777
794
30
38
60
82
84
81
95
97
107
103
125
135
144
146
133
129
131
131
135
135
130
129
136
242
246
313
316
328
335
451
459
450
441
461
542
541
547
555
555
562
570
578
576
583
583
596
595
598
597
598
599
598
599
598
597
596
9
5
1
-4
-8
-12
-16
-20
-24
-28
-32
-36
-40
-44
-48
-52
-56
-60
-64
-60
-64
-68
-72
-76
-80
-84
-88
-92
-96
-100
-104
-108
-112
-116
-120
-124
-128
-132
-136
-140
-144
-148
-152
-156
-160
-164
-168
-172
-176
-180
-184
-188
-192
-196
-200
-204
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 20       |
|    time_elapsed    | 32       |
|    total timesteps | 672      |
| train/             |          |
|    actor_loss      | -717     |
|    critic_loss     | 1.08e+05 |
|    ent_coef        | 1.06     |
|    ent_coef_loss   | -1.3     |
|    learning_rate   | 0.0003   |
|    n_updates       | 571      |
---------------------------------
9
5
1
-3
-7
-11
-15
-19
-23
-27
-31
-35
-39
-43
-47
-51
-55
-60
-49
-42
-43
-44
-45
-46
-47
-48
-39
-40
-41
-40
-41
-42
-29
-30
-32
-33
-33
-34
-35
-35
-37
-39
-40
-38
-39
-20
-22
-23
-16
-13
0
-2
-4
-3
4
3
9
-3
-14
1
16
14
21
20
18
25
44
42
50
48
56
57
63
71
78
76
84
92
100
98
96
95
103
123
131
129
136
144
157
155
162
160
162
160
168
188
196
204
212
210
230
230
238
236
244
252
255
254
263
272
271
270
12
17
23
35
42
41
38
45
52
50
47
54
60
61
67
74
81
88
95
109
116
131
128
154
161
168
174
181
195
202
209
216
223
230
237
243
250
257
264
270
277
296
302
309
316
330
337
344
359
366
373
379
386
413
427
434
18
30
37
52
59
66
73
80
87
101
107
113
120
126
141
148
155
161
167
173
200
206
213
220
226
238
244
264
270
276
283
297
304
319
339
353
359
366
372
378
384
390
403
410
416
423
429
443
457
471
477
490
496
502
508
526
----------------------------------
| time/              |           |
|    episodes        | 16        |
|    fps             | 20        |
|    time_elapsed    | 44        |
|    total timesteps | 896       |
| train/             |           |
|    actor_loss      | -1.33e+03 |
|    critic_loss     | 1.02e+05  |
|    ent_coef        | 1.12      |
|    ent_coef_loss   | -3.06     |
|    learning_rate   | 0.0003    |
|    n_updates       | 795       |
----------------------------------
17
29
49
55
75
81
93
99
105
123
140
148
156
172
180
188
196
204
212
220
229
246
255
264
273
282
299
308
317
326
336
346
356
366
376
386
396
406
416
426
437
448
459
470
481
492
503
514
525
536
549
561
573
585
600
612
17
21
27
33
39
67
74
86
85
97
105
142
150
158
171
180
188
201
214
222
231
241
250
259
273
287
347
361
377
386
400
409
423
438
448
463
473
483
498
508
517
527
542
552
562
572
587
597
607
617
632
642
653
664
680
691
24
36
48
60
67
75
87
99
112
138
150
158
163
176
184
197
210
223
236
249
262
269
282
295
305
318
331
344
358
372
386
395
409
431
445
459
473
487
501
515
529
543
557
571
585
599
613
627
641
655
669
683
698
712
726
740
18
28
37
46
55
65
86
95
104
119
128
137
152
161
182
192
208
230
252
261
291
301
310
319
334
356
365
374
383
393
402
412
427
436
445
454
463
473
483
493
509
518
527
536
546
562
572
581
603
613
622
643
659
668
677
687
----------------------------------
| time/              |           |
|    episodes        | 20        |
|    fps             | 19        |
|    time_elapsed    | 57        |
|    total timesteps | 1120      |
| train/             |           |
|    actor_loss      | -1.93e+03 |
|    critic_loss     | 8.94e+04  |
|    ent_coef        | 1.23      |
|    ent_coef_loss   | -5.87     |
|    learning_rate   | 0.0003    |
|    n_updates       | 1019      |
----------------------------------
24
39
61
70
80
90
105
115
125
147
157
167
176
186
204
226
235
257
267
289
299
321
343
353
363
373
383
405
415
425
435
457
467
488
498
508
518
528
538
548
558
568
578
588
598
608
618
628
638
648
658
668
678
688
698
708
18
28
38
38
38
48
58
68
68
78
88
98
108
118
126
126
136
146
156
156
156
156
166
176
186
196
206
216
216
216
216
216
216
226
236
236
236
236
246
246
256
266
266
266
266
266
276
276
286
286
296
296
306
316
326
326
18
28
28
28
38
48
58
68
78
78
78
78
88
106
116
126
126
136
146
156
156
156
156
156
156
164
174
184
184
194
194
204
214
224
224
224
224
224
224
224
224
234
244
246
258
260
262
264
266
278
280
282
284
296
298
300
8
8
18
18
18
18
18
18
18
20
22
24
26
36
48
60
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100
102
104
106
108
120
132
134
136
138
150
152
154
166
168
170
172
174
176
178
180
192
204
206
208
210
----------------------------------
| time/              |           |
|    episodes        | 24        |
|    fps             | 19        |
|    time_elapsed    | 69        |
|    total timesteps | 1344      |
| train/             |           |
|    actor_loss      | -2.47e+03 |
|    critic_loss     | 9.62e+04  |
|    ent_coef        | 1.35      |
|    ent_coef_loss   | -8.07     |
|    learning_rate   | 0.0003    |
|    n_updates       | 1243      |
----------------------------------
0
-8
-8
-16
-16
-24
-20
-26
-32
-38
-36
-42
-30
-28
-16
-22
-20
-18
-14
-20
-18
-16
-14
-12
-8
-6
-4
-2
0
12
24
26
28
30
32
44
56
68
70
72
74
86
88
100
112
114
126
128
130
132
144
156
168
180
200
202

0
-8
-8
-16
-24
-22
-20
-28
-26
-34
-30
-36
-32
-28
-24
-30
-36
8
3
-2
-11
-6
30
25
21
17
22
17
74
143
157
163
228
239
243
257
340
340
350
365
380
380
385
400
415
415
430
445
445
450
460
488
499
515
526
527
10
12
4
3
-3
-4
0
10
15
5
10
15
5
0
-8
-17
-11
-24
-18
-17
-16
-25
-30
-31
-36
-35
-31
-21
-11
11
7
7
7
7
12
16
21
21
32
37
59
69
74
90
112
114
124
135
139
140
152
164
175
187
194
218
10
5
3
-8
-9
-11
-22
-23
-24
-26
-28
-30
-40
-51
-61
-63
-64
-66
-77
-78
-88
-99
-110
-121
-122
-111
-113
-115
-126
-137
-138
-148
-138
-148
-158
-168
-161
-164
-158
-151
-154
-148
-150
-143
-137
-139
-127
-121
-114
-108
-102
-96
-89
-82
-76
-64
----------------------------------
| time/              |           |
|    episodes        | 28        |
|    fps             | 19        |
|    time_elapsed    | 81        |
|    total timesteps | 1568      |
| train/             |           |
|    actor_loss      | -3.67e+03 |
|    critic_loss     | 2.5e+05   |
|    ent_coef        | 1.48      |
|    ent_coef_loss   | -17.8     |
|    learning_rate   | 0.0003    |
|    n_updates       | 1467      |
----------------------------------
9
-3
-9
-4
7
6
4
2
-8
-10
-11
-13
-14
-15
-16
-18
-20
-22
-24
-26
-36
-32
-34
-24
-18
-20
-15
-16
-18
-20
-22
-23
-25
-26
-27
-29
-31
-32
-34
-35
-37
-38
-40
-42
-44
-46
-48
-50
-60
-62
-64
-65
-60
-61
-63
-65
9
13
12
2
0
-1
-3
3
9
7
6
12
2
1
-1
-2
4
2
8
-2
-4
2
8
6
-5
-7
-9
-19
-29
-31
-42
-38
-49
-51
-52
-54
-32
-30
-20
-18
-16
-21
-17
-14
-3
0
9
13
16
10
20
30
34
39
35
40
9
31
36
51
59
58
60
72
68
67
66
102
98
103
95
92
89
89
89
94
94
135
136
137
143
136
134
127
134
127
136
142
149
151
150
166
165
167
182
184
203
205
214
222
230
234
242
251
259
259
267
275
284
293
294
304
9
10
13
8
11
23
34
29
32
35
38
49
52
56
59
62
65
76
79
90
93
97
100
95
106
129
140
143
146
157
175
186
189
192
204
215
218
222
225
228
223
234
245
248
259
270
281
283
287
290
294
298
293
304
323
334
---------------------------------
| time/              |          |
|    episodes        | 32       |
|    fps             | 19       |
|    time_elapsed    | 93       |
|    total timesteps | 1792     |
| train/             |          |
|    actor_loss      | -4e+03   |
|    critic_loss     | 2.89e+05 |
|    ent_coef        | 1.66     |
|    ent_coef_loss   | -31.1    |
|    learning_rate   | 0.0003   |
|    n_updates       | 1691     |
---------------------------------
9
26
37
48
59
62
74
77
81
84
95
99
102
113
124
127
138
149
160
155
157
168
180
191
195
198
209
227
230
241
244
239
234
229
232
243
254
266
269
272
283
286
297
300
303
314
317
329
340
335
338
332
335
346
357
360
1
10
21
24
19
22
39
50
69
89
100
103
114
125
129
132
143
152
155
158
169
172
175
177
171
182
185
188
191
194
205
208
219
222
233
244
247
250
261
264
267
270
281
284
295
298
301
296
290
302
305
308
319
314
309
320
10
19
22
25
36
48
59
70
79
82
85
104
107
125
120
132
144
155
166
161
172
184
195
206
217
220
231
234
237
240
251
262
265
276
287
298
309
320
331
342
353
370
373
384
395
406
417
428
439
450
462
465
476
487
498
510
17
26
37
49
68
79
82
91
94
113
132
143
154
165
176
187
198
209
220
223
234
245
256
267
278
289
300
317
328
339
350
361
372
383
394
405
416
419
430
441
452
463
474
485
496
507
518
529
540
551
562
573
584
587
598
609
----------------------------------
| time/              |           |
|    episodes        | 36        |
|    fps             | 19        |
|    time_elapsed    | 105       |
|    total timesteps | 2016      |
| train/             |           |
|    actor_loss      | -5.01e+03 |
|    critic_loss     | 1.9e+05   |
|    ent_coef        | 1.84      |
|    ent_coef_loss   | -46.2     |
|    learning_rate   | 0.0003    |
|    n_updates       | 1915      |
----------------------------------
9
18
27
36
55
66
77
89
100
111
122
133
144
155
166
161
164
175
178
189
200
211
222
234
245
256
267
278
289
300
311
322
333
344
355
366
377
389
400
411
422
433
444
455
466
477
488
499
510
521
532
543
554
565
576
587
17
26
35
46
57
68
87
98
109
120
131
142
153
164
183
194
205
216
227
230
241
252
263
274
285
296
307
318
329
340
351
362
373
384
395
406
417
428
439
450
461
472
483
494
505
516
527
538
549
560
571
582
593
604
615
626
17
26
27
28
37
46
55
64
75
86
97
108
119
130
133
144
155
166
177
188
199
210
221
232
243
254
265
284
295
306
317
328
339
350
361
372
383
394
405
416
427
438
449
460
471
482
493
504
515
526
537
548
559
570
588
599
17
26
35
44
53
70
79
88
97
108
119
130
141
152
163
174
185
196
207
218
229
240
251
262
265
276
287
298
309
320
331
342
353
364
375
386
397
408
419
430
441
452
463
474
485
496
507
518
529
540
557
568
579
590
601
612
---------------------------------
| time/              |          |
|    episodes        | 40       |
|    fps             | 18       |
|    time_elapsed    | 118      |
|    total timesteps | 2240     |
| train/             |          |
|    actor_loss      | -5.5e+03 |
|    critic_loss     | 3.39e+05 |
|    ent_coef        | 2.06     |
|    ent_coef_loss   | -63.6    |
|    learning_rate   | 0.0003   |
|    n_updates       | 2139     |
---------------------------------
17
26
35
44
53
62
79
88
97
106
107
116
125
134
143
152
161
170
171
180
181
190
191
200
201
210
211
220
230
239
248
257
266
275
284
293
302
311
320
329
338
347
356
365
374
383
392
403
414
425
436
447
458
469
480
491
17
18
27
36
45
46
47
56
57
66
75
76
77
86
87
88
97
106
107
110
113
116
127
138
141
152
163
174
185
196
207
218
229
240
251
262
273
284
295
306
317
328
339
350
361
372
383
394
405
416
427
438
449
460
471
482
17
18
19
20
21
22
23
24
25
26
27
28
37
38
39
53
54
55
56
57
58
59
68
69
70
71
88
97
106
115
124
133
142
159
168
177
186
195
204
213
222
231
240
249
258
267
276
285
294
311
320
329
338
347
356
365
9
18
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
53
54
55
56
57
58
59
68
77
86
96
105
114
123
132
154
163
172
181
190
199
208
217
226
235
244
253
262
271
280
289
298
307
316
325
334
----------------------------------
| time/              |           |
|    episodes        | 44        |
|    fps             | 18        |
|    time_elapsed    | 130       |
|    total timesteps | 2464      |
| train/             |           |
|    actor_loss      | -5.48e+03 |
|    critic_loss     | 2.98e+05  |
|    ent_coef        | 2.29      |
|    ent_coef_loss   | -79.2     |
|    learning_rate   | 0.0003    |
|    n_updates       | 2363      |
----------------------------------
9
18
19
20
21
22
23
24
25
26
27
28
29
30
39
40
41
42
43
55
64
68
69
78
79
75
71
75
87
96
100
109
113
117
134
146
150
167
171
175
179
183
187
191
195
199
203
207
211
215
219
223
227
242
249
261
9
13
22
26
30
26
22
26
27
23
19
20
16
12
9
10
6
2
-2
-5
-9
-8
-12
-16
-15
-14
-10
-6
-2
2
6
10
14
20
33
39
45
59
65
71
90
104
111
117
131
152
159
166
173
180
195
202
210
217
224
231
9
18
22
18
22
18
22
26
22
18
14
10
6
2
-2
-6
-9
-13
-17
-13
-9
-13
-2
-3
2
6
5
12
27
34
41
53
60
75
82
89
96
103
110
118
125
132
139
146
153
160
168
176
184
199
206
213
230
237
250
258
9
22
26
30
26
30
26
23
19
23
27
23
27
39
36
32
28
32
44
48
44
56
52
56
60
56
52
57
61
66
70
74
78
82
99
109
113
118
122
127
132
136
140
144
149
153
157
162
166
171
175
179
189
194
199
203
----------------------------------
| time/              |           |
|    episodes        | 48        |
|    fps             | 18        |
|    time_elapsed    | 142       |
|    total timesteps | 2688      |
| train/             |           |
|    actor_loss      | -6.19e+03 |
|    critic_loss     | 3.64e+05  |
|    ent_coef        | 2.51      |
|    ent_coef_loss   | -87.6     |
|    learning_rate   | 0.0003    |
|    n_updates       | 2587      |
----------------------------------
9
20
25
37
42
38
34
31
36
33
29
46
43
40
45
50
47
56
53
49
46
50
55
60
64
69
73
78
82
87
92
97
102
106
103
108
113
118
123
128
125
130
135
139
136
141
146
151
168
173
190
194
204
209
206
210
18
31
28
25
29
34
39
44
49
54
58
55
60
57
53
58
63
68
73
78
83
88
93
98
103
108
105
110
115
120
125
130
135
140
145
142
147
152
157
162
167
172
177
188
192
189
194
199
204
209
214
219
224
229
231
236
18
31
36
41
46
51
55
52
57
73
78
83
88
93
98
103
108
113
118
123
128
133
138
143
148
153
158
163
168
173
178
183
188
193
190
195
200
205
210
215
220
225
230
235
240
245
258
255
260
265
270
275
280
277
282
287
10

15
28
33
38
43
40
37
34
39
44
49
54
59
64
69
66
71
68
73
86
91
96
93
98
103
108
113
118
123
128
133
138
143
148
153
150
155
160
165
170
175
180
177
182
187
192
197
202
207
212
209
214
219
224
229
----------------------------------
| time/              |           |
|    episodes        | 52        |
|    fps             | 18        |
|    time_elapsed    | 154       |
|    total timesteps | 2912      |
| train/             |           |
|    actor_loss      | -6.98e+03 |
|    critic_loss     | 5.86e+05  |
|    ent_coef        | 2.76      |
|    ent_coef_loss   | -122      |
|    learning_rate   | 0.0003    |
|    n_updates       | 2811      |
----------------------------------
18
23
34
31
36
41
46
51
56
61
74
79
84
89
94
99
104
109
114
119
124
129
134
139
144
149
154
159
164
169
174
171
176
181
186
191
204
217
222
227
232
237
242
247
252
257
262
267
272
269
274
279
284
289
294
299
18
23
28
33
38
43
48
53
58
63
68
73
83
88
93
98
111
116
129
134
139
144
149
154
159
164
169
174
187
192
197
202
207
212
217
222
227
232
237
242
239
244
249
254
259
264
269
274
279
284
289
294
307
312
322
327
18
23
28
33
38
43
48
53
58
63
68
73
78
83
96
101
106
111
116
121
126
131
136
141
146
151
156
161
166
163
168
173
178
183
188
193
198
203
200
205
210
215
220
225
230
235
240
245
250
255
260
265
270
275
280
285
18
31
44
49
54
59
64
69
74
79
84
89
86
91
96
91
86
91
86
96
101
88
80
88
86
94
107
115
113
121
137
140
138
136
144
134
132
130
136
134
142
140
138
136
139
137
135
135
133
131
129
127
125
133
136
134
----------------------------------
| time/              |           |
|    episodes        | 56        |
|    fps             | 18        |
|    time_elapsed    | 166       |
|    total timesteps | 3136      |
| train/             |           |
|    actor_loss      | -6.83e+03 |
|    critic_loss     | 1.17e+06  |
|    ent_coef        | 3.03      |
|    ent_coef_loss   | -114      |
|    learning_rate   | 0.0003    |
|    n_updates       | 3035      |
----------------------------------
8
13
21
24
19
24
19
22
22
17
20
20
20
23
28
23
18
18
13
8
3
-2
-7
-12
-17
-22
-27
-32
-37
-37
-47
-39
-49
-36
-33
-38
-38
-35
44
120
123
121
119
117
115
118
116
119
125
112
115
118
116
119
109
112
8
8
19
30
28
31
34
32
35
33
31
29
27
17
15
5
0
-9
-11
-13
-23
-17
-19
-21
-23
-28
-30
-27
-37
-47
-38
-35
-40
-42
-44
-54
-51
-48
-45
-55
-57
-59
19
17
15
18
29
19
22
20
15
13
11
9
7
10
8
8
11
6
9
7
-3
-5
-10
-7
-4
-1
10
8
-2
1
4
2
8
11
14
12
10
0
-2
-12
-9
-6
-11
-20
-22
-27
-29
-26
-28
-25
-27
-29
-27
-29
-39
-44
-49
-54
-56
-61
-71
-68
-73
-83
-75
-67
-59
-56
-40
-42
8
3
-10
-13
-18
-26
-34
-34
-47
-47
-52
-60
-65
-70
-75
-75
-88
-83
-81
-81
-89
-94
-107
-120
-117
-117
-77
-79
-76
-86
-87
-89
-91
-96
-106
-108
-118
-115
-120
-122
-119
-129
-139
-141
-143
-148
-153
-150
-155
-160
-170
-180
-177
-174
-171
-173
----------------------------------
| time/              |           |
|    episodes        | 60        |
|    fps             | 18        |
|    time_elapsed    | 178       |
|    total timesteps | 3360      |
| train/             |           |
|    actor_loss      | -6.72e+03 |
|    critic_loss     | 1.38e+06  |
|    ent_coef        | 3.26      |
|    ent_coef_loss   | -111      |
|    learning_rate   | 0.0003    |
|    n_updates       | 3259      |
----------------------------------
0
0
-13
-10
-15
-15
-23
-23
-23
-36
-44
-57
-57
-62
-67
-64
-72
-82
-87
-89
-86
-96
-101
-103
-113
-123
-128
-130
-140
-145
-147
-152
-162
-164
-174
-176
-181
-186
-196
-206
-208
-210
-131
-141
-151
-153
-155
-157
-162
-172
-182
-192
-194
-98
-95
-100
0
-8
-13
-21
-34
-39
-44
-57
-70
-73
-86
-99
-107
-115
-128
-141
-154
-167
-180
-193
-201
-214
-227
-238
-234
-240
-251
-257
-260
-266
-277
-283
-286
-297
-308
-314
-325
-321
-332
-333
-336
-347
-350
-353
-364
-375
-381
-387
-398
-404
-407
-418
-429
-440
-451
-452
0
18
13
0
-5
-13
-26
-31
-31
-36
-44
-57
-65
-78
-86
-94
-107
-120
-125
-138
-151
-159
-172
-185
-198
-211
-224
-232
-245
-250
-263
-268
-281
-286
-294
-307
-312
-325
-330
-343
-356
-369
-367
-380
-388
-401
-409
-417
-430
-443
-456
-459
-472
-477
-482
-490
8
0
-5
-18
-26
-23
-28
-28
-33
-46
-59
-59
-49
-57
-57
-70
-83
-96
-109
-112
-125
-138
-146
-159
-164
-164
-177
-185
-198
-196
-209
-209
-222
-227
-227
-240
-253
-250
-255
-260
-273
-281
-276
-289
-302
-315
-328
-336
-339
-347
-352
-357
-362
-359
-372
-385
----------------------------------
| time/              |           |
|    episodes        | 64        |
|    fps             | 18        |
|    time_elapsed    | 190       |
|    total timesteps | 3584      |
| train/             |           |
|    actor_loss      | -7.01e+03 |
|    critic_loss     | 8.36e+05  |
|    ent_coef        | 3.5       |
|    ent_coef_loss   | -121      |
|    learning_rate   | 0.0003    |
|    n_updates       | 3483      |
----------------------------------
0
-5
-2
-7
-4
-2
-7
-4
7
6
9
7
15
23
13
11
1
-9
-11
-13
-10
-12
-17
-22
-22
-24
-26
-36
-28
-38
-48
-41
-46
-56
-66
-73
-70
-72
-74
-76
-78
-80
-72
-59
-54
-56
-58
-60
-47
-57
-54
-51
-56
-56
-53
-50
8
10
5
17
20
23
13
26
29
37
45
53
58
48
38
46
54
67
66
64
59
54
57
60
66
61
122
125
128
128
131
129
127
122
130
138
141
144
147
150
148
151
159
175
188
201
209
208
216
224
232
240
248
261
275
273
18
18
18
38
36
44
34
39
37
58
56
64
62
70
78
86
84
92
100
108
121
111
119
127
125
133
141
146
154
162
170
178
186
194
202
200
208
216
225
234
243
252
261
270
279
288
297
306
323
332
346
355
364
495
623
633
18
23
30
37
41
48
55
70
77
84
91
88
95
102
109
116
123
130
137
144
151
158
165
172
179
194
201
208
215
222
229
241
248
255
262
269
276
283
290
297
294
306
313
320
327
324
331
338
345
352
359
371
378
375
382
389
----------------------------------
| time/              |           |
|    episodes        | 68        |
|    fps             | 18        |
|    time_elapsed    | 201       |
|    total timesteps | 3808      |
| train/             |           |
|    actor_loss      | -7.96e+03 |
|    critic_loss     | 1.58e+06  |
|    ent_coef        | 3.76      |
|    ent_coef_loss   | -141      |
|    learning_rate   | 0.0003    |
|    n_updates       | 3707      |
----------------------------------
18
23
30
37
44
51
58
65
62
69
76
75
82
89
96
103
110
117
124
131
138
145
152
159
166
173
192
202
212
222
232
242
242
252
263
274
285
296
307
318
329
340
351
362
374
386
398
410
422
434
446
448
460
472
484
496
18
23
30
37
44
41
48
45
57
64
71
78
77
76
73
80
87
94
101
108
115
122
129
136
135
142
149
156
163
170
177
184
181
188
195
202
209
216
228
235
242
249
264
271
278
285
291
298
305
312
319
326
338
345
352
359
18
23
28
33
38
48
55
61
68
75
74
81
88
95
113
120
127
134
136
143
150
157
164
161
168
175
172
179
185
183
190
187
194
191
198
204
211
218
224
236
233
239
246
252
259
258
255
262
269
286
293
300
298
304
311
330
17
21
25
39
46
53
60
67
73
80
86
92
99
106
112
118
124
131
129
135
147
145
159
166
172
178
190
196
202
208
227
233
239
253
259
266
280
287
293
299
297
309
306
312
318
325
331
338
344
350
356
362
368
374
380
378
----------------------------------
| time/              |           |
|    episodes        | 72        |
|    fps             | 18        |
|    time_elapsed    | 213       |
|    total timesteps | 4032      |
| train/             |           |
|    actor_loss      | -8.23e+03 |
|    critic_loss     | 1.27e+06  |
|    ent_coef        | 4.03      |
|    ent_coef_loss   | -139      |
|    learning_rate   | 0.0003    |
|    n_updates       | 3931      |
----------------------------------
17
13
18
22
26
32
47
53
59
65
71
77
83
101
107
113
125
131
129
135
141
139
145
151
157
163
169
183
181
187
193
207
213
219
225
231
237
243
249
255
261
267
273
271
277
291
302
309
315
321
335
341
347
353
359
365
17
21
25
31
37
43
49
47
53
67
73
71
77
83
89
95
101
107
113
119
125
131
137
135
141
147
153
167
173
179
185
191
197
203
209
207
213
219
225
223
229
243
249
247
253
259
257
263
261
267
273
279
291
297
303
309
17
21
27
33
39
37
43
49
55
53
59
65
71
77
77
88
94
92
98
104
110
116
122
128
128
134
140
146
152
150
156
162
168
174
180
186
193
199
205
211
217
223
229
240
246
253
259
257
263
269
275
281
287
293
293
300
17
29
27
33
39
45
51
57
47
45
51
57
63
69
75
81
92
98
96
110
108
114
120
118
124
130
136
142
148
154
160
166
172
170

176
182
188
194
200
211
222
228
226
237
235
241
238
249
255
261
259
266
272
262
260
266
----------------------------------
| time/              |           |
|    episodes        | 76        |
|    fps             | 18        |
|    time_elapsed    | 225       |
|    total timesteps | 4256      |
| train/             |           |
|    actor_loss      | -7.96e+03 |
|    critic_loss     | 1.24e+06  |
|    ent_coef        | 4.32      |
|    ent_coef_loss   | -139      |
|    learning_rate   | 0.0003    |
|    n_updates       | 4155      |
----------------------------------
17
21
19
30
27
33
23
21
27
25
39
37
48
54
60
74
85
99
105
119
117
123
129
127
133
139
137
143
149
147
153
159
165
176
174
195
205
216
226
236
238
248
259
266
285
296
299
315
326
338
354
365
369
381
393
405
17
29
35
46
52
58
56
70
76
90
96
110
116
122
128
139
137
143
149
155
161
172
178
184
190
196
202
208
214
220
226
232
238
244
250
261
275
281
307
305
311
317
315
321
332
343
341
339
350
356
370
381
392
398
396
402
17
29
48
54
44
55
53
72
78
84
82
77
75
115
139
150
158
163
171
163
171
172
189
190
199
200
209
218
219
220
229
244
241
251
266
276
278
285
287
292
302
390
393
396
391
407
418
421
433
444
455
458
462
458
462
474
22
30
42
49
44
48
52
59
63
62
61
69
85
93
106
107
115
115
128
128
144
145
151
152
161
162
171
172
173
178
249
264
274
276
278
298
313
323
338
353
363
453
456
459
470
465
474
482
482
482
493
504
513
517
529
541
---------------------------------
| time/              |          |
|    episodes        | 80       |
|    fps             | 18       |
|    time_elapsed    | 237      |
|    total timesteps | 4480     |
| train/             |          |
|    actor_loss      | -7.7e+03 |
|    critic_loss     | 1.79e+06 |
|    ent_coef        | 4.59     |
|    ent_coef_loss   | -124     |
|    learning_rate   | 0.0003   |
|    n_updates       | 4379     |
---------------------------------
9
5
11
22
25
53
60
64
63
62
74
74
74
74
74
74
87
95
103
124
116
117
131
145
146
147
148
154
147
140
141
155
149
159
161
163
165
172
166
168
162
177
180
175
186
190
201
224
240
240
235
238
249
257
261
270
1
2
9
3
14
17
20
18
24
27
38
49
52
56
74
79
84
92
97
97
110
111
125
126
135
136
137
146
147
153
155
148
150
152
146
156
171
173
166
173
176
182
189
192
195
198
193
196
195
198
214
222
230
239
235
243
9
-3
-5
13
17
13
12
16
27
26
33
37
37
53
53
107
107
107
104
96
109
120
112
112
126
124
125
126
124
125
131
145
212
213
214
220
222
216
210
220
227
229
252
259
277
284
299
299
302
305
313
329
340
348
359
370
9
11
9
7
11
9
7
10
9
8
14
17
20
23
34
24
27
25
23
13
8
6
17
20
10
13
16
83
89
90
99
100
93
99
107
122
143
153
168
170
185
195
205
227
237
247
263
266
277
288
291
302
313
316
319
330
----------------------------------
| time/              |           |
|    episodes        | 84        |
|    fps             | 18        |
|    time_elapsed    | 249       |
|    total timesteps | 4704      |
| train/             |           |
|    actor_loss      | -7.74e+03 |
|    critic_loss     | 1.14e+06  |
|    ent_coef        | 4.86      |
|    ent_coef_loss   | -130      |
|    learning_rate   | 0.0003    |
|    n_updates       | 4603      |
----------------------------------
9
5
-2
-4
-14
-16
-21
-18
-20
-17
-14
-16
-13
-2
-4
-6
5
8
11
9
12
15
5
3
1
7
13
16
26
29
32
38
44
47
58
77
88
102
108
119
122
129
135
138
144
147
153
164
162
168
179
185
196
207
213
224
1
-4
-7
-9
-11
-13
-14
-16
-18
-20
-22
-32
-34
-36
-33
-35
-45
-47
-49
-46
-48
-50
-46
-48
-50
-47
-57
-51
-45
-39
-33
-22
-16
-10
2
9
16
27
33
31
38
41
39
36
34
40
46
52
58
170
180
186
196
207
217
227
1
-3
-10
-7
-9
4
4
3
7
6
10
14
13
12
11
10
9
8
7
3
3
2
6
13
8
7
6
10
22
22
30
38
38
46
46
51
51
64
78
78
78
91
99
107
107
115
123
128
141
146
146
154
154
167
176
190
0
8
17
5
-2
-14
-18
-20
-22
-23
-25
-33
-35
-37
-47
-49
-59
-53
-47
-57
-46
-48
-50
-52
-54
-44
-46
-48
-37
-31
-30
-32
-25
-28
-22
-19
-13
-15
-9
-11
-13
-2
-4
-6
0
19
17
24
22
28
31
37
35
37
43
41
----------------------------------
| time/              |           |
|    episodes        | 88        |
|    fps             | 18        |
|    time_elapsed    | 260       |
|    total timesteps | 4928      |
| train/             |           |
|    actor_loss      | -7.27e+03 |
|    critic_loss     | 7.02e+05  |
|    ent_coef        | 5.17      |
|    ent_coef_loss   | -134      |
|    learning_rate   | 0.0003    |
|    n_updates       | 4827      |
----------------------------------
9
13
9
-3
-7
-5
-17
-9
-15
-17
-19
-16
-13
-7
-9
-11
-8
-5
-15
-9
-19
-13
-7
-9
-11
-5
-7
0
11
22
28
25
31
37
43
49
62
68
67
73
79
76
83
101
112
118
124
122
128
133
139
145
156
153
159
166
10
2
14
10
8
6
0
4
-1
-11
-13
-2
-4
-6
-8
-9
-11
-7
-9
-6
-16
-19
-25
-19
-10
-11
-4
-9
-2
4
7
18
24
21
27
33
44
62
81
87
84
96
103
106
117
123
129
135
132
143
161
159
165
171
178
190
9
2
-1
4
8
12
0
4
8
12
19
23
13
15
21
27
39
42
31
29
35
42
100
100
105
113
128
147
155
153
160
159
171
178
185
192
200
198
205
212
219
226
234
242
255
260
274
281
289
294
303
311
319
318
326
326
16
26
35
31
21
33
47
59
70
76
88
94
91
90
141
148
151
149
148
160
165
177
168
181
193
197
205
204
219
232
239
246
259
267
280
288
302
311
320
329
338
346
354
367
380
389
409
417
529
537
545
564
572
572
581
590
----------------------------------
| time/              |           |
|    episodes        | 92        |
|    fps             | 18        |
|    time_elapsed    | 272       |
|    total timesteps | 5152      |
| train/             |           |
|    actor_loss      | -6.87e+03 |
|    critic_loss     | 6.6e+05   |
|    ent_coef        | 5.48      |
|    ent_coef_loss   | -116      |
|    learning_rate   | 0.0003    |
|    n_updates       | 5051      |
----------------------------------
17
27
37
50
60
69
64
63
70
89
100
106
117
124
128
126
132
151
157
160
166
172
179
185
196
216
222
225
231
237
243
254
266
277
283
294
314
320
331
329
343
354
365
371
385
388
394
400
424
430
453
459
465
476
482
485
17
26
35
36
46
56
62
73
71
77
83
90
101
107
118
125
139
137
140
138
137
143
162
168
163
177
175
192
199
210
216
223
234
247
253
260
266
280
282
288
294
300
312
419
425
422
432
442
451
457
466
483
493
495
511
521
17
19
41
52
58
69
72
78
89
92
104
110
108
119
130
142
140
152
155
162
168
179
190
188
195
261
269
285
302
316
330
340
349
363
377
386
400
410
419
425
431
437
446
453
464
479
489
495
510
526
537
539
540
550
558
566
1
10
21
24
30
41
43
49
55
58
64
70
68
79
90
101
112
123
134
145
143
154
152
163
169
167
165
171
185
199
276
277
278
287
296
310
312
321
330
339
348
348
349
358
375
385
396
402
404
414
416
426
436
438
448
463
----------------------------------
| time/              |           |
|    episodes        | 96        |
|    fps             | 18        |
|    time_elapsed    | 285       |
|    total timesteps | 5376      |
| train/             |           |
|    actor_loss      | -6.78e+03 |
|    critic_loss     | 9.59e+05  |
|    ent_coef        | 5.79      |
|    ent_coef_loss   | -125      |
|    learning_rate   | 0.0003    |
|    n_updates       | 5275      |
----------------------------------
17
39
43
55
53
59
65
71
82
89
87
98
109
121
142
147
160
173
186
199
212
220
228
241
249
249
327
335
341
347
356
370
384
398
407
407
421
430
444
454
463
477
483
493
503
513
523
530
532
534
544
554
569
571
573
580
27
39
59
71
75
79
86
82
97
104
116
115
120
133
146
146
159
172
176
181
194
217
230
235
235
241
250
259
265
279
288
297
298
312
318
323
329
331
346
356
371
378
388
390
400
410
412
427
437
447
457
472
482
492
494
504
17
26
22
23
27
33
53
56
62
65
63
60
62
65
63
74
80
86
97
95
101
112
123
126
137
140
146
152
158
156
159
165
176
182
185
191
202
221
227
225
228
231
250
248
259
265
263
269
267
278
284
290
415
431
447
458
17
19
20
26
37
48
59
65
71
69
67
65
71
74
80
86
97
100
106
112
118
129
127
125
131
142
153
164
183
189
200
211
225
223
228
234
240
243
249
255
258
270
273
271
274
277
288
295
312
322
337
347
357
372
382
392
----------------------------------
| time/              |           |
|    episodes        | 100       |
|    fps             | 18        |
|    time_elapsed    | 297       |
|    total timesteps | 5600      |
| train/             |           |
|    actor_loss      | -6.46e+03 |
|    critic_loss     | 5.46e+05  |
|    ent_coef        | 6.13      |
|    ent_coef_loss   | -135      |
|    learning_rate   | 0.0003    |
|    n_updates       | 5499      |
----------------------------------

17
26
35
39
35
41
60
66
77
88
94
100
103
109
107
110
113
119
122
120
126
129
135
146
152
150
148
143
141
148
159
165
168
174
188
279
288
297
315
324
333
334
343
359
377
392
394
400
415
417
432
434
441
444
447
463
9
18
27
28
29
40
51
46
65
63
112
116
123
122
129
136
135
139
143
143
159
167
180
193
209
222
227
227
232
232
241
242
251
257
266
275
292
306
307
404
418
427
433
443
453
464
474
484
486
488
498
501
508
526
534
546
9
13
14
15
16
19
25
31
37
40
38
49
54
67
74
127
134
142
155
168
176
176
181
201
222
230
238
246
259
267
280
296
305
306
314
328
329
338
360
361
362
379
394
403
412
434
444
459
469
471
482
497
503
505
507
522
9
18
30
41
44
50
56
70
76
82
80
86
85
91
97
103
109
209
217
217
222
230
236
245
251
260
266
280
350
373
374
383
383
389
403
404
405
414
416
431
433
443
450
473
480
482
497
507
522
537
539
563
574
590
601
604
----------------------------------
| time/              |           |
|    episodes        | 104       |
|    fps             | 18        |
|    time_elapsed    | 309       |
|    total timesteps | 5824      |
| train/             |           |
|    actor_loss      | -6.01e+03 |
|    critic_loss     | 6.51e+05  |
|    ent_coef        | 6.49      |
|    ent_coef_loss   | -119      |
|    learning_rate   | 0.0003    |
|    n_updates       | 5723      |
----------------------------------
17
18
27
48
47
67
90
97
112
124
143
155
162
184
184
192
189
209
208
208
221
234
247
263
284
292
305
305
372
385
399
408
414
480
494
504
518
524
530
539
556
570
584
599
608
614
624
639
654
664
680
695
702
704
711
726
27
39
51
59
72
88
96
111
110
117
124
127
126
130
138
152
168
176
176
189
197
201
209
222
230
235
243
251
265
288
308
317
326
336
358
367
385
399
414
416
431
447
462
477
498
513
537
547
570
575
590
613
642
653
664
680
24
45
51
49
48
68
88
109
134
147
163
171
187
194
202
206
214
231
245
263
276
276
289
302
310
323
345
359
369
387
397
415
430
445
454
468
478
488
490
491
502
525
540
575
586
597
620
635
652
676
688
707
719
731
743
763
18
35
45
71
90
96
110
129
170
178
186
198
197
206
205
213
226
235
241
254
263
287
305
314
323
332
350
359
368
377
385
395
410
426
437
447
457
472
483
493
503
519
530
545
562
574
586
597
613
624
644
661
672
696
708
720
----------------------------------
| time/              |           |
|    episodes        | 108       |
|    fps             | 18        |
|    time_elapsed    | 321       |
|    total timesteps | 6048      |
| train/             |           |
|    actor_loss      | -5.92e+03 |
|    critic_loss     | 1.02e+06  |
|    ent_coef        | 6.85      |
|    ent_coef_loss   | -125      |
|    learning_rate   | 0.0003    |
|    n_updates       | 5947      |
----------------------------------
10
19
38
58
63
69
79
77
89
101
112
129
136
154
166
177
184
186
205
220
227
234
241
247
254
272
279
286
293
300
307
314
326
339
345
357
364
376
403
410
429
432
447
466
481
480
487
494
501
513
525
537
534
554
561
564
17
35
49
64
76
87
106
121
120
132
156
173
180
186
198
205
220
226
239
238
250
262
274
280
286
293
300
312
324
330
350
362
369
382
389
401
413
427
438
445
457
469
476
483
494
501
527
533
540
547
678
685
696
712
728
744
30
48
63
75
88
102
127
139
142
149
162
175
184
198
212
220
228
237
244
248
270
284
301
315
330
357
370
380
389
398
419
433
442
452
457
471
481
495
510
521
537
553
564
575
591
600
635
654
669
679
690
709
725
742
753
761
18
30
37
57
69
66
90
97
111
117
124
131
143
154
161
163
175
182
197
216
223
230
227
238
250
257
264
276
283
358
368
378
392
392
401
418
428
430
452
475
485
509
520
539
550
560
576
699
710
720
748
763
791
807
824
836
----------------------------------
| time/              |           |
|    episodes        | 112       |
|    fps             | 18        |
|    time_elapsed    | 334       |
|    total timesteps | 6272      |
| train/             |           |
|    actor_loss      | -5.57e+03 |
|    critic_loss     | 8.32e+05  |
|    ent_coef        | 7.25      |
|    ent_coef_loss   | -117      |
|    learning_rate   | 0.0003    |
|    n_updates       | 6171      |
----------------------------------
18
21
36
48
60
84
91
103
100
107
118
136
143
149
168
174
178
193
190
197
204
211
218
224
227
233
245
265
285
292
303
310
334
333
364
371
391
418
424
431
454
460
467
474
486
498
510
517
524
527
551
563
587
593
605
612
17
35
59
74
94
106
104
119
130
154
166
170
176
182
202
204
216
231
242
253
264
271
289
303
318
325
328
339
351
358
364
381
387
394
397
404
401
407
419
418
429
426
430
449
447
458
476
479
485
500
518
536
535
534
540
559
18
30
39
46
81
80
85
89
101
121
129
136
136
157
166
182
191
213
227
241
258
266
280
288
303
312
312
322
337
346
356
371
368
370
384
399
409
419
429
438
446
457
468
492
508
524
535
551
562
577
593
604
633
634
650
661
9
27
32
51
70
76
88
87
99
104
122
140
155
167
178
194
209
216
228
234
246
253
271
280
289
298
307
313
313
322
336
340
340
349
347
361
371
386
399
409
419
437
445
447
463
479
495
511
522
541
564
586
588
604
606
617
----------------------------------
| time/              |           |
|    episodes        | 116       |
|    fps             | 18        |
|    time_elapsed    | 346       |
|    total timesteps | 6496      |
| train/             |           |
|    actor_loss      | -5.12e+03 |
|    critic_loss     | 5.89e+05  |
|    ent_coef        | 7.64      |
|    ent_coef_loss   | -109      |
|    learning_rate   | 0.0003    |
|    n_updates       | 6395      |
----------------------------------
18
42
54
74
85
104
110
117
132
139
154
160
159
170
181
238
252
273
287
308
308
334
360
374
387
378
392
400
423
427
442
457
479
479
500
526
535
545
546
556
566
582
596
614
617
628
644
660
670
685
696
720
736
751
762
773
17
19
46
56
63
61
60
67
74
81
87
99
106
121
127
139
151
149
148
160
171
178
177
176
171
173
170
182
193
196
190
197
204
208
215
222
228
234
328
344
367
383
418
425
444
471
482
492
507
500
511
528
531
542
677
689
18
18
28
34
33
35
56
76
84
91
115
123
130
135
134
145
167
173
182
195
203
220
233
247
256
262
279
283
291
297
318
402
408
423
424
427
433
435
437
447
456
466
481
491
500
515
531
561
563
568
583
599
607
608
624
639
17
35
50
74
88
90
103
106
105
117
124
135
146
144
150
157
169
172
191
198
205
211
206
221
227
234
241
248
245
256
263
281
278
289
296
316
323
321
327
347
354
365
359
365
368
482
483
494
497
508
525
542
554
790
810
822
---------------------------------
| time/              |          |
|    episodes        | 120      |
|    fps             | 18       |
|    time_elapsed    | 358      |
|    total timesteps | 6720     |
| train/             |          |
|    actor_loss      | -4.7e+03 |
|    critic_loss     | 6.21e+05 |
|    ent_coef        | 8.03     |
|    ent_coef_loss   | -108     |
|    learning_rate   | 0.0003   |
|    n_updates       | 6619     |
---------------------------------
17
27
37
49
71
71
85
101
109
107
132
145
144
144
143
149
207
210
219
224
233
225
225
217
206
199
211
219
228
235
245
327
320
325
339
333
335
349
371
375
391
392
395
411
435
453
468
466
462
477
488
490
500
507
519
536
0
2
22
35
40
40
54
59
66
65
90
91
98
94
102
118
126
117
126
122
122
135
141
148
156
165
175
167
175
182
182
182
188
198
208
223
233
235
256
265
266
277
280
290
291
301
316
332
334
336
347
340
342
353
361
381
18
23
34
24
44
43
50
48
64
63
74
81
93
100
110
109
116
122
134
132
139
142
149
156
162
176
195
187
186
258
274
275
285
287
289
303
305
299
301
302
304
314
329
331
334
337
340
343
350
361
458
464
474
589
600
619
10
28
26
15
10
1
9
16
32
23
30
30
60
68
69
81
89
97
93
102
102
118
123
131
131
129
129
122
123
124
130
130
138
149
239
256
263
271
294
305
316
310
312
322
330
332
335
343
360
354
348
352
356
359
368
379
----------------------------------
| time/              |           |
|    episodes        | 124       |
|    fps             | 18        |
|    time_elapsed    | 370       |
|    total timesteps | 6944      |
| train/             |           |
|    actor_loss      | -4.34e+03 |
|    critic_loss     | 3.4e+05   |
|    ent_coef        | 8.45      |
|    ent_coef_loss   | -113      |
|    learning_rate   | 0.0003    |
|    n_updates       | 6843      |
----------------------------------
8
4
-6
1
14
12
10
9
18
15
15
4
2
1
0
-11
-4
-5
-6
1
-4
2
1
0
7
13
20
14
16
13
11
14
28
26
28
26
24
30
37
56
54
53
69
67
71
77
76
74
72

87
98
109
115
114
112
110
10
14
20
26
33
30
42
48
37
27
34
24
23
35
33
37
34
48
52
47
50
40
44
58
48
52
63
62
68
75
70
59
65
55
52
51
41
47
53
43
67
71
70
61
59
57
64
62
61
55
61
72
70
68
73
68
9
13
20
27
33
45
56
54
43
49
56
55
53
52
50
49
47
49
64
62
60
63
69
67
74
84
82
80
84
82
81
93
99
105
103
101
111
109
108
115
114
112
110
108
98
97
96
86
84
82
101
99
97
102
101
104
1
-4
2
8
7
7
18
26
25
24
23
31
39
59
51
52
61
61
62
54
69
77
82
82
91
107
109
111
121
135
137
138
140
150
160
169
172
165
172
166
169
180
190
191
199
210
212
214
217
228
245
257
260
272
267
262
----------------------------------
| time/              |           |
|    episodes        | 128       |
|    fps             | 18        |
|    time_elapsed    | 382       |
|    total timesteps | 7168      |
| train/             |           |
|    actor_loss      | -4.01e+03 |
|    critic_loss     | 2.61e+05  |
|    ent_coef        | 8.88      |
|    ent_coef_loss   | -90.6     |
|    learning_rate   | 0.0003    |
|    n_updates       | 7067      |
----------------------------------
24
33
42
49
63
69
76
74
77
79
85
75
72
62
68
75
81
82
80
86
97
96
103
102
109
112
102
112
126
121
128
137
142
157
175
177
186
196
196
190
208
218
220
234
228
230
241
257
264
274
276
287
290
294
303
306
17
22
18
16
30
20
26
29
35
33
30
33
40
38
37
44
43
40
55
61
59
57
60
49
68
84
77
86
79
97
114
124
127
141
150
159
169
171
181
188
182
181
192
202
205
208
201
213
213
216
219
230
233
236
245
249
17
34
29
33
40
46
44
42
41
53
43
42
46
57
71
69
67
86
93
91
98
92
90
97
94
92
98
104
111
110
175
176
169
179
193
193
203
213
206
208
218
220
218
219
220
227
221
224
230
238
246
249
252
255
259
281
9
26
24
22
12
15
9
8
19
25
36
42
41
56
75
67
65
72
70
68
66
64
68
72
62
61
59
66
72
79
91
89
87
84
90
101
100
98
87
85
84
74
73
79
82
86
98
109
127
125
136
142
140
147
154
152
----------------------------------
| time/              |           |
|    episodes        | 132       |
|    fps             | 18        |
|    time_elapsed    | 395       |
|    total timesteps | 7392      |
| train/             |           |
|    actor_loss      | -3.71e+03 |
|    critic_loss     | 3.29e+05  |
|    ent_coef        | 9.25      |
|    ent_coef_loss   | -60.9     |
|    learning_rate   | 0.0003    |
|    n_updates       | 7291      |
----------------------------------
9
5
1
15
21
20
24
27
34
41
60
67
66
72
75
81
87
93
105
110
123
129
131
145
152
164
171
177
182
185
192
204
202
209
220
232
239
246
261
263
269
288
294
291
288
293
291
306
308
314
320
489
500
507
519
535
23
36
42
57
56
62
69
83
95
102
108
115
133
134
143
156
164
178
186
202
224
234
244
253
324
338
347
353
380
394
397
420
433
443
458
476
512
527
543
567
592
616
633
657
682
793
917
933
950
981
1007
1033
1050
1067
1084
1114
22
40
57
69
80
92
112
123
146
158
183
207
225
248
271
283
300
312
324
336
348
359
371
395
413
431
455
472
495
507
539
550
562
573
596
620
632
656
668
679
691
702
733
757
768
788
820
844
862
873
885
897
916
927
950
961
23
41
72
102
134
167
180
212
231
255
281
307
333
347
372
398
412
426
451
470
485
500
526
561
582
608
622
657
671
698
719
740
756
778
917
944
979
1007
1023
1038
1055
1080
1089
1106
1118
1146
1330
1355
1372
1394
1412
1429
1459
1476
1500
1518
----------------------------------
| time/              |           |
|    episodes        | 136       |
|    fps             | 18        |
|    time_elapsed    | 407       |
|    total timesteps | 7616      |
| train/             |           |
|    actor_loss      | -4.57e+03 |
|    critic_loss     | 4.12e+05  |
|    ent_coef        | 9.34      |
|    ent_coef_loss   | -0.761    |
|    learning_rate   | 0.0003    |
|    n_updates       | 7515      |
----------------------------------
9
39
51
62
82
100
111
135
154
166
189
209
221
252
321
335
349
362
388
415
429
444
471
492
572
586
612
639
653
668
683
705
733
761
788
816
832
847
867
882
904
921
938
966
988
1010
1027
1055
1206
1229
1259
1277
1300
1317
1334
1352
10
27
50
53
65
104
117
137
150
175
188
207
221
235
306
325
351
410
423
437
457
472
487
600
627
648
663
677
698
718
733
748
770
798
825
841
856
872
900
911
928
1052
1068
1104
1121
1150
1166
1183
1211
1228
1246
1263
1286
1309
1327
1351
18
40
72
83
107
119
138
162
180
191
203
214
269
283
302
315
329
355
381
395
410
425
506
521
535
549
564
649
664
684
699
723
739
754
770
798
820
847
874
902
919
942
964
980
1113
1130
1147
1164
1193
1209
1416
1446
1464
1487
1505
1523
9
39
58
69
81
93
104
128
139
188
202
216
242
255
281
295
309
327
341
361
376
391
414
441
456
471
485
520
535
550
566
594
610
634
650
672
687
715
745
772
801
818
846
875
891
908
924
941
958
981
1010
1028
1052
1082
1106
1124
----------------------------------
| time/              |           |
|    episodes        | 140       |
|    fps             | 18        |
|    time_elapsed    | 419       |
|    total timesteps | 7840      |
| train/             |           |
|    actor_loss      | -4.85e+03 |
|    critic_loss     | 3.87e+05  |
|    ent_coef        | 9.36      |
|    ent_coef_loss   | -5.4      |
|    learning_rate   | 0.0003    |
|    n_updates       | 7739      |
----------------------------------
24
46
58
62
66
78
102
134
146
158
176
196
208
219
231
243
255
267
285
297
309
326
338
350
367
465
492
519
545
560
576
592
613
637
666
682
698
714
750
766
794
816
839
864
887
903
920
937
954
971
989
1013
1030
1060
1078
1108
18
48
60
72
96
114
134
157
169
213
239
253
275
294
308
322
336
350
363
377
392
406
427
454
482
568
595
621
648
663
679
706
836
851
866
882
898
1013
1029
1045
1061
1077
1094
1123
1140
1156
1173
1190
1212
1240
1269
1292
1309
1327
1344
1373
9
33
45
57
68
91
103
115
127
131
151
175
187
199
210
221
233
256
268
292
315
327
351
363
387
399
410
433
465
477
489
501
512
524
547
564
576
588
619
631
649
661
673
697
709
721
733
744
755
767
785
809
821
833
851
863
15
33
53
65
76
93
104
127
145
169
184
200
219
245
257
281
305
317
341
353
370
393
410
421
432
456
468
479
491
617
645
672
699
721
737
858
874
895
911
927
943
971
988
1010
1027
1043
1073
1102
1131
1159
1189
1206
1229
1247
1270
1287
----------------------------------
| time/              |           |
|    episodes        | 144       |
|    fps             | 18        |
|    time_elapsed    | 431       |
|    total timesteps | 8064      |
| train/             |           |
|    actor_loss      | -5.17e+03 |
|    critic_loss     | 7.64e+05  |
|    ent_coef        | 9.41      |
|    ent_coef_loss   | -8.84     |
|    learning_rate   | 0.0003    |
|    n_updates       | 7963      |
----------------------------------
30
45
56
68
79
104
127
139
162
171
183
200
209
220
230
245
249
252
320
340
361
388
402
422
434
522
536
562
576
590
605
621
637
652
674
702
718
860
876
884
901
929
958
974
991
1028
1057
1074
1090
1106
1123
1140
1158
1175
1205
1222
23
40
51
70
81
101
119
130
142
153
156
167
191
209
220
232
250
261
273
284
288
300
312
335
352
363
375
387
404
422
433
450
468
485
497
508
532
544
556
579
590
602
614
638
649
666
678
689
700
711
877
907
924
954
978
996
9
10
14
38
49
60
79
103
143
161
175
188
215
235
249
263
282
295
308
333
348
363
378
404
425
452
474
494
509
536
552
573
589
605
629
645
681
696
711
727
743
760
789
812
841
857
874
891
908
930
947
965
982
1011
1029
1059
18
41
59
84
95
107
125
140
144
156
168
185
204
228
252
276
299
323
346
372
384
396
419
431
454
471
488
500
524
536
548
572
589
612
624
635
647
671
695
718
729
740
764
776
800
812
830
842
853
865
876
894
911
922
934
957
----------------------------------
| time/              |           |
|    episodes        | 148       |
|    fps             | 18        |
|    time_elapsed    | 442       |
|    total timesteps | 8288      |
| train/             |           |
|    actor_loss      | -5.44e+03 |
|    critic_loss     | 6.55e+05  |
|    ent_coef        | 9.48      |
|    ent_coef_loss   | -12       |
|    learning_rate   | 0.0003    |
|    n_updates       | 8187      |
----------------------------------
10
31
43
62
74
85
96
112
136
153
164
187
199
210
221
238
262
279
310
322
333
345
357
381
401
425
449
461
478
490
502
514
531
554
578
590
613
625
637
649
673
691
715
738
755
767
791
803
827
851
863
875
887
899
911
923
17
47
63
75
99
131
155
175
195
199
211
223
247
264
288
292
315
327
345
349
361
365
397
409
421
425
437
449
469
493
497
509
533
545
549
561
573
597
621
625
637
649
661
685
708
720
732
755
767
785
797
809
821
833
850
862
30
46
58
70
92
120
145
170
189
214
228
234
248
262
296
310
324
350
372
386
405
420
446
473
499
526
553
576
591
606
622
650
678
694
710
726
742
764
780
808
825
842
870
892
909
938
967
996
1024
1052
1070
1088
1106
1136
1154
1332
29
47
73
85
103
118
130
148
160
177
188
200
212
235
247
259
282
294
306
375
402
429
456
471
498
525
551
585
600
615
639
666
682
698
714
735
751
778
805
827
855
872
889
926
942
959
1136
1153
1170
1199
1217
1406
1424
1442
1460
1489
----------------------------------
| time/              |           |
|    episodes        | 152       |
|    fps             | 18        |
|    time_elapsed    | 453       |
|    total timesteps | 8512      |
| train/             |           |
|    actor_loss      | -5.69e+03 |
|    critic_loss     | 6.39e+05  |
|    ent_coef        | 9.58      |
|    ent_coef_loss   | -12.2     |
|    learning_rate   | 0.0003    |
|    n_updates       | 8411      |
----------------------------------
18
28
60
84
88
112
124
136
148
171
195
207
224
236
248
260
272
284
296
316
327
339
351
363
375
399
411
431
443
557
573
601
617
767
783
810
826
842
871
898
915
932
949
966
989
1011
1027
1051
1080
1102
1132
1150
1180
1204
1390
1408
18
35
55
74
86
110
133
158
170
181
199
216
266
286
338
352
378
392
418
432
447
468
483
498
525
539
565
580
594
615
631
653
680
701
717
733
754
775
796
812
829
846
875
892
909
926
949
977
1005
1028
1045
1069
1092
1110
1134
1152
18
39
42
53
57
74
94
117
128
140
172
195
207
231
251
262
274
298
309
321
332
356
380
391
414
432
456
474
486
497
509
527
539
556
568
591
602
613
636
659
671
694
706
718
730
741
753
765
782
793
805
829
848
872
884
895
24
34
45
56
72
96
116
136
160
177
200
218
230
256
267
276
288
306
318
350
362
374
397
414
426
438
462
547
567
594
610
625
641
662
690
706
722
743
758
780
797
825
841
866
889
906
934
962
978
995
1013
1031
1061
1079
1097
1115
----------------------------------
| time/              |           |
|    episodes        | 156       |
|    fps             | 18        |
|    time_elapsed    | 465       |
|    total timesteps | 8736      |
| train/             |           |
|    actor_loss      | -5.94e+03 |
|    critic_loss     | 6.23e+05  |
|    ent_coef        | 9.69      |
|    ent_coef_loss   | -12.8     |
|    learning_rate   | 0.0003    |
|    n_updates       | 8635      |
----------------------------------
18
28
48
59
77
89
101
117
132
149
161
185
205
217
241
253
277
289
301
321
333
350
374
385
397
401
413
437
455
466
470
493
505
516
528
548
572
584
602
614
626
643
654
666
677
689
712
730
754
778
802
813
825
837
849
866
24
47
70
90
101
113
131
143
155
165
177
181
185
189
201
224
248
260
271
283
294
312
387
414
428
510
525
532
566
580
595
611
639
660
682
698
713
740
756
783
805
827
850
870
892
900
909
926
943
966
996
1014
1043
1073
1091
1114
22
62
75
99
119
131
144
168
180
192
206
228
247
267
286
300
320
346
360
386
401
416
436
451
466
476
558
573
588
614
630
652
668
684
705
726
742
758
774
796
812
829
851
880
909
938
955
984
1001
1018
1048
1066
1084
1107
1318
1336
18
36
48
60
76
101
113
125
137
161
228
248
274
300
356
382
396
421
435
449
464
491
506
533
548
563
578
601
616
631
658
680
696
712
728
756
772
808
832
860
889
906
923
940
969
992
1009
1038
1067
1095
1125
1143
1173
1191
1215
1244
----------------------------------
| time/              |           |
|    episodes        | 160       |
|    fps             | 18        |
|    time_elapsed    | 477       |
|    total timesteps | 8960      |
| train/             |           |
|    actor_loss      | -6.16e+03 |
|    critic_loss     | 2.88e+05  |
|    ent_coef        | 9.82      |
|    ent_coef_loss   | -13.4     |
|    learning_rate   | 0.0003    |
|    n_updates       | 8859      |
----------------------------------
24
34
46
58
70
82
102
114
126
138
150
167
191
203
215
239
251
263
275
293
305
317
329
341
359
384
395
415
427
438
455
466
490
507
525
537
549
566
584
596
608
620
644
656
668
685
708
720
731
743
766
778
796
814
838
849
18
41
60
75
79
91
111
115
139
151
163
175
198
210
222
234
246
264
276
293
310
322
332
356
388
408
419
436
447
459
471
495
507
519
530
542
554
571
583
601
619
643
660
843
860
889
906
929
958
975
1005
1023
1041
1064
1094
1112
18
36
48
72
84
101
105
123
147
164
188
200
212
230
242
266
290
302
326
350
374
386
398
421
433
445
457
469
481
504
516
548
565
589
613
625
637
657
681
704
716
736
760
780
792
809
825
849
861
879
891
915
933
945
962
986
18
36
62
79
91
103
127
152
164
176
202
214
218
230
247
271
295
319
331
343
361
441
456
470
496
516
531
546
561
582
597
613
641
662
689
711
726
742
757
773
790
807
831
860
877
894
910
933
961
977
1001
1033
1062
1080
1098
1115
----------------------------------
| time/              |           |
|    episodes        | 164       |
|    fps             | 18        |
|    time_elapsed    | 489       |
|    total timesteps | 9184      |
| train/             |           |
|    actor_loss      | -6.37e+03 |
|    critic_loss     | 8.13e+05  |
|    ent_coef        | 9.95      |
|    ent_coef_loss   | -12.4     |
|    learning_rate   | 0.0003    |
|    n_updates       | 9083      |
----------------------------------
30
40
59
63
87
107
119
123
127
144
156
167
178
182
205
228
252
275
298
329
415
441
462
477
491
511
526
561
575
602
609
636
651
768
795
811
826
842
858
894
923
940
956
972
994
1023
1032
1049
1066
1083
1106
1123
1141
1170
1188
1209
9
10
33
53
65
77
95
106
118
129
152
211
225
239
258
272
294
313
335
349
375
396
417
495
510
525
540
555
569
590
618
641
657
673
695
710
738
757
773
789
811
839
862
879
896
912
924
941
970
987
1005
1034
1057
1083
1113
1131
18
36
48
72
90
110
122
134
151
169
187
199
211
222
245
262
286
306
318
342
359
371
383
401
418
430
447
465
477
500
512
524
542
554
565
577
589
606
618
630
641
653
665
689
693
705
717
734
758
769
781
798
822
834
846
869
18
28
48
72
84
102
126
146
166
198
217
227
251
271
294
305
317
334
352
363
375
399
423
529
556
571
586
612
626
641
662
689
705
720
742
770
786
814
830
852
876
905
933
950
967
984
1006
1035
1064
1081
1110
1128
1151
1169
1187
1216
---------------------------------
| time/              |          |
|    episodes        | 168      |
|    fps             | 18       |
|    time_elapsed    | 501      |
|    total timesteps | 9408     |
| train/             |          |
|    actor_loss      | -6.5e+03 |
|    critic_loss     | 1.16e+06 |
|    ent_coef        | 10.1     |
|    ent_coef_loss   | -9.16    |
|    learning_rate   | 0.0003   |
|    n_updates       | 9307     |
---------------------------------
10
50
74
87
92
125
130
143
175
199
226
288
308
322
348
362
376
442
468
482
497
595
622
637
672
687
708
723
738
753
780
808
830
846
868
884
900
916
938
960
983
1000
1017
1033
1050
1067
1096
1113
1130
1159
1359
1377
1407
1437
1466
1484
18
40
60
72
100
125
150
174
187
200
219
233
247
261
295
308
328
341
363
377
397
417
432
452
564
590
611
637
652
667
695
709
729
745
761
777
785
799
827
843
872
889
918
946
975
992
1021
1038
1055
1084
1113
1143
1161
1179
1209
1235
29
60
84
110
138
151
164
174
191
224
238
264
282
296
302
316
330
347
372
386
401
422
448
463
482
497
524
539
554
569
585
601
617
726
750
758
774
790
810
969
994
1011
1024
1053
1070
1099
1108
1125
1142
1171
1189
1207
1225
1255
1284
1314
10
20
43
77
90
115
133
146
159
177
190
212
232
251
265
284
290
303
317
345
372
387
413
440
455
470
485
500
515
541
570
586
602
618
645
661
689
717
733
754
782
799
827
844
866
883
900
917
934
962
991
1009
1035
1065
1094
1112
----------------------------------
| time/              |           |
|    episodes        | 172       |
|    fps             | 18        |
|    time_elapsed    | 514       |
|    total timesteps | 9632      |
| train/             |           |
|    actor_loss      | -6.75e+03 |
|    critic_loss     | 9.24e+05  |
|    ent_coef        | 10.3      |
|    ent_coef_loss   | -12       |
|    learning_rate   | 0.0003    |
|    n_updates       | 9531      |
----------------------------------
10
40
55
59
83
101
113
125
137
190
216
230
256
262
288
341
366
372
378
384
396
411
425
448
463
490
505
532
554
575
591
606
625
769
785
801
817
833
849
865
881
910
939
962
991
1008
1025
1042
1070

1087
1105
1123
1153
1175
1193
1363
17
41
66
79
91
112
130
148
161
174
193
221
246
260
311
324
337
350
364
389
475
489
599
613
628
730
749
768
783
798
814
835
854
889
917
944
965
980
996
1012
1035
1063
1091
1114
1130
1158
1174
1191
1213
1235
1252
1282
1305
1335
1353
1370
22
32
52
69
89
113
137
153
178
190
202
214
238
250
268
280
304
316
328
340
352
372
384
408
420
443
475
499
517
529
541
553
565
569
581
593
704
720
736
752
781
798
815
832
849
866
883
905
933
955
973
1003
1032
1062
1080
1098
18
39
63
95
115
139
151
175
187
239
258
284
298
312
326
359
385
399
413
439
454
481
496
522
537
552
573
608
623
638
666
690
711
727
743
771
786
802
817
833
850
866
889
906
935
957
974
997
1026
1043
1066
1089
1106
1124
1154
1172
----------------------------------
| time/              |           |
|    episodes        | 176       |
|    fps             | 18        |
|    time_elapsed    | 526       |
|    total timesteps | 9856      |
| train/             |           |
|    actor_loss      | -6.91e+03 |
|    critic_loss     | 9.62e+05  |
|    ent_coef        | 10.5      |
|    ent_coef_loss   | -11.1     |
|    learning_rate   | 0.0003    |
|    n_updates       | 9755      |
----------------------------------
30
39
51
63
80
104
116
132
149
167
185
203
223
235
258
270
281
292
304
321
333
356
374
397
420
510
525
551
566
581
608
624
640
667
683
706
722
749
777
799
816
839
856
881
909
938
955
983
1012
1040
1070
1094
1123
1153
1170
1188
24
54
78
124
142
152
165
178
197
214
234
254
268
285
299
374
392
406
424
444
462
555
570
585
612
632
646
681
696
710
734
762
789
811
819
835
855
871
893
909
932
968
997
1014
1031
1060
1077
1106
1123
1283
1313
1342
1372
1390
1408
1426
18
36
48
68
80
92
96
100
112
124
156
160
172
184
196
208
220
232
244
256
268
291
358
385
400
415
430
445
460
483
499
527
543
559
586
614
630
534.2453184127808

In [169]:
from stable_baselines3.common.evaluation import evaluate_policy

In [170]:
env = conn(Num_Pin_unique_max, max_color_categories,max_categories_multicore, Num_Pins) 
obs = env.reset()
env.render()
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=10)
print(f'Mean reward: {mean_reward} +/- {std_reward:.2f}')

C:\Users\User\AppData\Roaming\Python\Python38\site-packages\stable_baselines3\common\evaluation.py:65: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(

18
28
40
52
64
76
88
100
112
124
136
148
160
172
184
196
208
220
232
244
256
268
280
292
304
316
328
340
352
364
376
388
400
412
424
436
448
460
472
484
496
508
520
532
544
556
568
580
592
604
616
628
640
652
664
676
18
28
40
52
64
76
88
100
112
124
136
148
160
172
184
196
208
220
232
244
256
268
280
292
304
316
328
340
352
364
376
388
400
412
424
436
448
460
472
484
496
508
520
532
544
556
568
580
592
604
616
628
640
652
664
676
18
28
40
52
64
76
88
100
112
124
136
148
160
172
184
196
208
220
232
244
256
268
280
292
304
316
328
340
352
364
376
388
400
412
424
436
448
460
472
484
496
508
520
532
544
556
568
580
592
604
616
628
640
652
664
676
18
28
40
52
64
76
88
100
112
124
136
148
160
172
184
196
208
220
232
244
256
268
280
292
304
316
328
340
352
364
376
388
400
412
424
436
448
460
472
484
496
508
520
532
544
556
568
580
592
604
616
628
640
652
664
676
18
28
40
52
64
76
88
100
112
124
136
148
160
172
184
196
208
220
232
244
256
268
280
292
304
316
328
340
352
364
376
388
400
412
424
436
448
460
472
484
496
508
520
532
544
556
568
580
592
604
616
628
640
652
664
676
18
28
40
52
64
76
88
100
112
124
136
148
160
172
184
196
208
220
232
244
256
268
280
292
304
316
328
340
352
364
376
388
400
412
424
436
448
460
472
484
496
508
520
532
544
556
568
580
592
604
616
628
640
652
664
676
18
28
40
52
64
76
88
100
112
124
136
148
160
172
184
196
208
220
232
244
256
268
280
292
304
316
328
340
352
364
376
388
400
412
424
436
448
460
472
484
496
508
520
532
544
556
568
580
592
604
616
628
640
652
664
676
18
28
40
52
64
76
88
100
112
124
136
148
160
172
184
196
208
220
232
244
256
268
280
292
304
316
328
340
352
364
376
388
400
412
424
436
448
460
472
484
496
508
520
532
544
556
568
580
592
604
616
628
640
652
664
676
18
28
40
52
64
76
88
100
112
124
136
148
160
172
184
196
208
220
232
244
256
268
280
292
304
316
328
340
352
364
376
388
400
412
424
436
448
460
472
484
496
508
520
532
544
556
568
580
592
604
616
628
640
652
664
676
18
28
40
52
64
76
88
100
112
124
136
148
160
172
184
196
208
220
232
244
256
268
280
292
304
316
328
340
352
364
376
388
400
412
424
436
448
460
472
484
496
508
520
532
544
556
568
580
592
604
616
628
640
652
664
676
Mean reward: 19378.0 +/- 0.00

In [171]:
connector='TO_121_TNGA_F/219_13P'

In [172]:
env = conn(Num_Pin_unique_max, max_color_categories,max_categories_multicore, Num_Pins)

In [173]:
obs = env.reset()
for key in connectors_dicc[connector].keys():
    if key != 'PartNumber':
        obs = np.array(get_pin_signal(connectors_dicc[connector],key))
        action, _state = model.predict(obs, deterministic=True)
        
        obs, reward, done, info = env.step(action.astype(int))
        print(reward)
        env.render()
        if done:
           obs = env.reset()
print(reward)

18
18
22
22
27
27
28
28
35
35
42
42
43
43
50
50
51
51
58
58
65
65
72
72
79
79
79

#DQN 'TO_169_F/161_RH_13P' =234 , 'TO_121_TNGA_F/219_13P' = 342 'TO_169_F/161_RH_13P' = 113 'TO_111_LH_F/143_3P' 0

In [174]:
#TD3 'TO_169_F/161_RH_13P' = 123 , 'TO_121_TNGA_F/219_13P' =169  'TO_169_F/161_RH_13P' = 134 'TO_111_LH_F/143_3P' 227

In [175]:
# for key in connectors_dicc[connector].keys():
#     if key != 'PartNumber':
#         pred= np.array(get_pin_signal(connectors_dicc[connector],key))
        
#         prediction=model.predict(pred,  deterministic= False)

In [176]:
Num_Pins

13

In [177]:
connectors_dicc[connector]

{'1': {'PreferredSignal': 'na',
  'Cat_PreferredSignal': 27,
  'Signal': 'SLD_EFI_ECU-TNGA_KNOCK_SSR_101',
  'Cat_Signal': 14,
  'dicc_signals': "{0: 'CLEARANCE_SNR_ECU_0885', 1: 'CLEARANCE_SNR_ECU_0890', 2: 'EQ_FUEL_PRESS_SSR_HI-TNGA_E2', 3: 'EQ_FUEL_PRESS_SSR_HI-TNGA_PR', 4: 'EQ_FUEL_PRESS_SSR_HI-TNGA_VC', 5: 'EQ_NE_SSR-TNGA_NE-', 6: 'EQ_NE_SSR-TNGA_NEP', 7: 'EQ_NE_SSR-TNGA_VCNE', 8: 'EQ_PDB_L_1', 9: 'EQ_PDB_L_2', 10: 'EQ_PDB_L_5', 11: 'GND_BK_UP_LP_LH_E', 12: 'HV_ECU-HV_0024', 13: 'HV_ECU-HV_0025', 14: 'SLD_EFI_ECU-TNGA_KNOCK_SSR_101', 15: 'SLD_EFI_ECU-TNGA_KNOCK_SSR_102', 16: 'SLD_MG_ECU_197', 17: 'SLD_MG_ECU_198', 18: 'SLD_MG_ECU_199', 19: 'SLD_MG_ECU_200', 20: 'SLD_MG_ECU_201', 21: 'SLD_MG_ECU_202', 22: 'SLD_MG_ECU_203', 23: 'TW_CLEARANCE_SNR_ECU_055', 24: 'TW_CLEARANCE_SNR_ECU_056', 25: 'TW_CLEARANCE_SNR_ECU_061', 26: 'TW_CLEARANCE_SNR_ECU_062', 27: 'na'}",
  'check_signal': 0,
  'Num_Pins': 13,
  'Num_Pin_unique': 13,
  'more_signal_in_pin': False,
  'WireColor': 'W',
  'WireCSA': 0.35,
  'Multicore': 'MC142264',
  'signal_group': 7,
  'internal_pin': 'False',
  'neighbors_length': 3,
  'mean_neighbors': 17978.4389589976,
  'centroide_distance': 17692.997233682912,
  'number_internal_pin': 2.0,
  'max_distance': 23124.761296065306,
  'min_distance': 9604.020824633815,
  'Cat_Wire_WireColor': 27,
  'Cat_Wire_WireColor_max': 30,
  'Wire_WireCSA_min': 0.0,
  'Wire_WireCSA_max': 8.0,
  'Num_Pin_unique_max': 55,
  'no_signal_pin': 0,
  'multicore_same': 1,
  'is_multicore': 1,
  'max_categories_multicore': 8,
  'distance_to_center': 23121.024631274453,
  'neighbors': ['2', '7', '8']},
 'PartNumber': '90980-12716',
 '2': {'PreferredSignal': 'na',
  'Cat_PreferredSignal': 27,
  'Signal': 'SLD_EFI_ECU-TNGA_KNOCK_SSR_102',
  'Cat_Signal': 15,
  'dicc_signals': "{0: 'CLEARANCE_SNR_ECU_0885', 1: 'CLEARANCE_SNR_ECU_0890', 2: 'EQ_FUEL_PRESS_SSR_HI-TNGA_E2', 3: 'EQ_FUEL_PRESS_SSR_HI-TNGA_PR', 4: 'EQ_FUEL_PRESS_SSR_HI-TNGA_VC', 5: 'EQ_NE_SSR-TNGA_NE-', 6: 'EQ_NE_SSR-TNGA_NEP', 7: 'EQ_NE_SSR-TNGA_VCNE', 8: 'EQ_PDB_L_1', 9: 'EQ_PDB_L_2', 10: 'EQ_PDB_L_5', 11: 'GND_BK_UP_LP_LH_E', 12: 'HV_ECU-HV_0024', 13: 'HV_ECU-HV_0025', 14: 'SLD_EFI_ECU-TNGA_KNOCK_SSR_101', 15: 'SLD_EFI_ECU-TNGA_KNOCK_SSR_102', 16: 'SLD_MG_ECU_197', 17: 'SLD_MG_ECU_198', 18: 'SLD_MG_ECU_199', 19: 'SLD_MG_ECU_200', 20: 'SLD_MG_ECU_201', 21: 'SLD_MG_ECU_202', 22: 'SLD_MG_ECU_203', 23: 'TW_CLEARANCE_SNR_ECU_055', 24: 'TW_CLEARANCE_SNR_ECU_056', 25: 'TW_CLEARANCE_SNR_ECU_061', 26: 'TW_CLEARANCE_SNR_ECU_062', 27: 'na'}",
  'check_signal': 0,
  'Num_Pins': 13,
  'Num_Pin_unique': 13,
  'more_signal_in_pin': False,
  'WireColor': 'B',
  'WireCSA': 0.35,
  'Multicore': 'MC142264',
  'signal_group': 7,
  'internal_pin': 'False',
  'neighbors_length': 5,
  'mean_neighbors': 17089.98857437672,
  'centroide_distance': 16559.055152997105,
  'number_internal_pin': 2.0,
  'max_distance': 23124.761296065306,
  'min_distance': 9604.020824633815,
  'Cat_Wire_WireColor': 0,
  'Cat_Wire_WireColor_max': 30,
  'Wire_WireCSA_min': 0.0,
  'Wire_WireCSA_max': 8.0,
  'Num_Pin_unique_max': 55,
  'no_signal_pin': 0,
  'multicore_same': 1,
  'is_multicore': 1,
  'max_categories_multicore': 8,
  'distance_to_center': 19202.000416623265,
  'neighbors': ['3', '1', '8', '7', '9']},
 '3': {'PreferredSignal': 'na',
  'Cat_PreferredSignal': 27,
  'Signal': 'na',
  'Cat_Signal': 27,
  'dicc_signals': "{0: 'CLEARANCE_SNR_ECU_0885', 1: 'CLEARANCE_SNR_ECU_0890', 2: 'EQ_FUEL_PRESS_SSR_HI-TNGA_E2', 3: 'EQ_FUEL_PRESS_SSR_HI-TNGA_PR', 4: 'EQ_FUEL_PRESS_SSR_HI-TNGA_VC', 5: 'EQ_NE_SSR-TNGA_NE-', 6: 'EQ_NE_SSR-TNGA_NEP', 7: 'EQ_NE_SSR-TNGA_VCNE', 8: 'EQ_PDB_L_1', 9: 'EQ_PDB_L_2', 10: 'EQ_PDB_L_5', 11: 'GND_BK_UP_LP_LH_E', 12: 'HV_ECU-HV_0024', 13: 'HV_ECU-HV_0025', 14: 'SLD_EFI_ECU-TNGA_KNOCK_SSR_101', 15: 'SLD_EFI_ECU-TNGA_KNOCK_SSR_102', 16: 'SLD_MG_ECU_197', 17: 'SLD_MG_ECU_198', 18: 'SLD_MG_ECU_199', 19: 'SLD_MG_ECU_200', 20: 'SLD_MG_ECU_201', 21: 'SLD_MG_ECU_202', 22: 'SLD_MG_ECU_203', 23: 'TW_CLEARANCE_SNR_ECU_055', 24: 'TW_CLEARANCE_SNR_ECU_056', 25: 'TW_CLEARANCE_SNR_ECU_061', 26: 'TW_CLEARANCE_SNR_ECU_062', 27: 'na'}",
  'check_signal': 2,
  'Num_Pins': 13,
  'Num_Pin_unique': 13,
  'more_signal_in_pin': False,
  'WireColor': 'na',
  'WireCSA': 0.0,
  'Multicore': 'na',
  'signal_group': 7,
  'internal_pin': 'False',
  'neighbors_length': 4,
  'mean_neighbors': 13744.0522515368,
  'centroide_distance': 13174.968387058847,
  'number_internal_pin': 2.0,
  'max_distance': 23124.761296065306,
  'min_distance': 9604.020824633815,
  'Cat_Wire_WireColor': 30,
  'Cat_Wire_WireColor_max': 30,
  'Wire_WireCSA_min': 0.0,
  'Wire_WireCSA_max': 8.0,
  'Num_Pin_unique_max': 55,
  'no_signal_pin': 1,
  'multicore_same': 2,
  'is_multicore': 0,
  'max_categories_multicore': 8,
  'distance_to_center': 16407.53058811715,
  'neighbors': ['2', '9', '8', '10']},
 '4': {'PreferredSignal': 'na',
  'Cat_PreferredSignal': 27,
  'Signal': 'EQ_NE_SSR-TNGA_NEP',
  'Cat_Signal': 6,
  'dicc_signals': "{0: 'CLEARANCE_SNR_ECU_0885', 1: 'CLEARANCE_SNR_ECU_0890', 2: 'EQ_FUEL_PRESS_SSR_HI-TNGA_E2', 3: 'EQ_FUEL_PRESS_SSR_HI-TNGA_PR', 4: 'EQ_FUEL_PRESS_SSR_HI-TNGA_VC', 5: 'EQ_NE_SSR-TNGA_NE-', 6: 'EQ_NE_SSR-TNGA_NEP', 7: 'EQ_NE_SSR-TNGA_VCNE', 8: 'EQ_PDB_L_1', 9: 'EQ_PDB_L_2', 10: 'EQ_PDB_L_5', 11: 'GND_BK_UP_LP_LH_E', 12: 'HV_ECU-HV_0024', 13: 'HV_ECU-HV_0025', 14: 'SLD_EFI_ECU-TNGA_KNOCK_SSR_101', 15: 'SLD_EFI_ECU-TNGA_KNOCK_SSR_102', 16: 'SLD_MG_ECU_197', 17: 'SLD_MG_ECU_198', 18: 'SLD_MG_ECU_199', 19: 'SLD_MG_ECU_200', 20: 'SLD_MG_ECU_201', 21: 'SLD_MG_ECU_202', 22: 'SLD_MG_ECU_203', 23: 'TW_CLEARANCE_SNR_ECU_055', 24: 'TW_CLEARANCE_SNR_ECU_056', 25: 'TW_CLEARANCE_SNR_ECU_061', 26: 'TW_CLEARANCE_SNR_ECU_062', 27: 'na'}",
  'check_signal': 0,
  'Num_Pins': 13,
  'Num_Pin_unique': 13,
  'more_signal_in_pin': False,
  'WireColor': 'L',
  'WireCSA': 0.35,
  'Multicore': 'na',
  'signal_group': 7,
  'internal_pin': 'False',
  'neighbors_length': 4,
  'mean_neighbors': 13757.646567580376,
  'centroide_distance': 13192.034284465,
  'number_internal_pin': 2.0,
  'max_distance': 23124.761296065306,
  'min_distance': 9604.020824633815,
  'Cat_Wire_WireColor': 7,
  'Cat_Wire_WireColor_max': 30,
  'Wire_WireCSA_min': 0.0,
  'Wire_WireCSA_max': 8.0,
  'Num_Pin_unique_max': 55,
  'no_signal_pin': 0,
  'multicore_same': 2,
  'is_multicore': 0,
  'max_categories_multicore': 8,
  'distance_to_center': 16408.58363784029,
  'neighbors': ['5', '11', '10', '12']},
 '5': {'PreferredSignal': 'na',
  'Cat_PreferredSignal': 27,
  'Signal': 'EQ_NE_SSR-TNGA_NE-',
  'Cat_Signal': 5,
  'dicc_signals': "{0: 'CLEARANCE_SNR_ECU_0885', 1: 'CLEARANCE_SNR_ECU_0890', 2: 'EQ_FUEL_PRESS_SSR_HI-TNGA_E2', 3: 'EQ_FUEL_PRESS_SSR_HI-TNGA_PR', 4: 'EQ_FUEL_PRESS_SSR_HI-TNGA_VC', 5: 'EQ_NE_SSR-TNGA_NE-', 6: 'EQ_NE_SSR-TNGA_NEP', 7: 'EQ_NE_SSR-TNGA_VCNE', 8: 'EQ_PDB_L_1', 9: 'EQ_PDB_L_2', 10: 'EQ_PDB_L_5', 11: 'GND_BK_UP_LP_LH_E', 12: 'HV_ECU-HV_0024', 13: 'HV_ECU-HV_0025', 14: 'SLD_EFI_ECU-TNGA_KNOCK_SSR_101', 15: 'SLD_EFI_ECU-TNGA_KNOCK_SSR_102', 16: 'SLD_MG_ECU_197', 17: 'SLD_MG_ECU_198', 18: 'SLD_MG_ECU_199', 19: 'SLD_MG_ECU_200', 20: 'SLD_MG_ECU_201', 21: 'SLD_MG_ECU_202', 22: 'SLD_MG_ECU_203', 23: 'TW_CLEARANCE_SNR_ECU_055', 24: 'TW_CLEARANCE_SNR_ECU_056', 25: 'TW_CLEARANCE_SNR_ECU_061', 26: 'TW_CLEARANCE_SNR_ECU_062', 27: 'na'}",
  'check_signal': 0,
  'Num_Pins': 13,
  'Num_Pin_unique': 13,
  'more_signal_in_pin': False,
  'WireColor': 'Y',
  'WireCSA': 0.35,
  'Multicore': 'MC137562',
  'signal_group': 7,
  'internal_pin': 'False',
  'neighbors_length': 5,
  'mean_neighbors': 17108.6293754634,
  'centroide_distance': 16577.271785188295,
  'number_internal_pin': 2.0,
  'max_distance': 23124.761296065306,
  'min_distance': 9604.020824633815,
  'Cat_Wire_WireColor': 29,
  'Cat_Wire_WireColor_max': 30,
  'Wire_WireCSA_min': 0.0,
  'Wire_WireCSA_max': 8.0,
  'Num_Pin_unique_max': 55,
  'no_signal_pin': 0,
  'multicore_same': 0,
  'is_multicore': 1,
  'max_categories_multicore': 8,
  'distance_to_center': 19203.800066653475,
  'neighbors': ['4', '12', '6', '11', '13']},
 '6': {'PreferredSignal': 'na',
  'Cat_PreferredSignal': 27,
  'Signal': 'EQ_NE_SSR-TNGA_VCNE',
  'Cat_Signal': 7,
  'dicc_signals': "{0: 'CLEARANCE_SNR_ECU_0885', 1: 'CLEARANCE_SNR_ECU_0890', 2: 'EQ_FUEL_PRESS_SSR_HI-TNGA_E2', 3: 'EQ_FUEL_PRESS_SSR_HI-TNGA_PR', 4: 'EQ_FUEL_PRESS_SSR_HI-TNGA_VC', 5: 'EQ_NE_SSR-TNGA_NE-', 6: 'EQ_NE_SSR-TNGA_NEP', 7: 'EQ_NE_SSR-TNGA_VCNE', 8: 'EQ_PDB_L_1', 9: 'EQ_PDB_L_2', 10: 'EQ_PDB_L_5', 11: 'GND_BK_UP_LP_LH_E', 12: 'HV_ECU-HV_0024', 13: 'HV_ECU-HV_0025', 14: 'SLD_EFI_ECU-TNGA_KNOCK_SSR_101', 15: 'SLD_EFI_ECU-TNGA_KNOCK_SSR_102', 16: 'SLD_MG_ECU_197', 17: 'SLD_MG_ECU_198', 18: 'SLD_MG_ECU_199', 19: 'SLD_MG_ECU_200', 20: 'SLD_MG_ECU_201', 21: 'SLD_MG_ECU_202', 22: 'SLD_MG_ECU_203', 23: 'TW_CLEARANCE_SNR_ECU_055', 24: 'TW_CLEARANCE_SNR_ECU_056', 25: 'TW_CLEARANCE_SNR_ECU_061', 26: 'TW_CLEARANCE_SNR_ECU_062', 27: 'na'}",
  'check_signal': 0,
  'Num_Pins': 13,
  'Num_Pin_unique': 13,
  'more_signal_in_pin': False,
  'WireColor': 'V',
  'WireCSA': 0.35,
  'Multicore': 'MC137562',
  'signal_group': 7,
  'internal_pin': 'False',
  'neighbors_length': 3,
  'mean_neighbors': 18001.48144179527,
  'centroide_distance': 17714.50599869434,
  'number_internal_pin': 2.0,
  'max_distance': 23124.761296065306,
  'min_distance': 9604.020824633815,
  'Cat_Wire_WireColor': 26,
  'Cat_Wire_WireColor_max': 30,
  'Wire_WireCSA_min': 0.0,
  'Wire_WireCSA_max': 8.0,
  'Num_Pin_unique_max': 55,
  'no_signal_pin': 0,
  'multicore_same': 0,
  'is_multicore': 1,
  'max_categories_multicore': 8,
  'distance_to_center': 23124.761296065306,
  'neighbors': ['13', '5', '12']},
 '7': {'PreferredSignal': 'na',
  'Cat_PreferredSignal': 27,
  'Signal': 'EQ_FUEL_PRESS_SSR_HI-TNGA_E2',
  'Cat_Signal': 2,
  'dicc_signals': "{0: 'CLEARANCE_SNR_ECU_0885', 1: 'CLEARANCE_SNR_ECU_0890', 2: 'EQ_FUEL_PRESS_SSR_HI-TNGA_E2', 3: 'EQ_FUEL_PRESS_SSR_HI-TNGA_PR', 4: 'EQ_FUEL_PRESS_SSR_HI-TNGA_VC', 5: 'EQ_NE_SSR-TNGA_NE-', 6: 'EQ_NE_SSR-TNGA_NEP', 7: 'EQ_NE_SSR-TNGA_VCNE', 8: 'EQ_PDB_L_1', 9: 'EQ_PDB_L_2', 10: 'EQ_PDB_L_5', 11: 'GND_BK_UP_LP_LH_E', 12: 'HV_ECU-HV_0024', 13: 'HV_ECU-HV_0025', 14: 'SLD_EFI_ECU-TNGA_KNOCK_SSR_101', 15: 'SLD_EFI_ECU-TNGA_KNOCK_SSR_102', 16: 'SLD_MG_ECU_197', 17: 'SLD_MG_ECU_198', 18: 'SLD_MG_ECU_199', 19: 'SLD_MG_ECU_200', 20: 'SLD_MG_ECU_201', 21: 'SLD_MG_ECU_202', 22: 'SLD_MG_ECU_203', 23: 'TW_CLEARANCE_SNR_ECU_055', 24: 'TW_CLEARANCE_SNR_ECU_056', 25: 'TW_CLEARANCE_SNR_ECU_061', 26: 'TW_CLEARANCE_SNR_ECU_062', 27: 'na'}",
  'check_signal': 0,
  'Num_Pins': 13,
  'Num_Pin_unique': 13,
  'more_signal_in_pin': False,
  'WireColor': 'G',
  'WireCSA': 0.35,
  'Multicore': 'na',
  'signal_group': 7,
  'internal_pin': 'True',
  'neighbors_length': 3,
  'mean_neighbors': 19101.713873555167,
  'centroide_distance': 19003.96814995343,
  'number_internal_pin': 2.0,
  'max_distance': 23124.761296065306,
  'min_distance': 9604.020824633815,
  'Cat_Wire_WireColor': 5,
  'Cat_Wire_WireColor_max': 30,
  'Wire_WireCSA_min': 0.0,
  'Wire_WireCSA_max': 8.0,
  'Num_Pin_unique_max': 55,
  'no_signal_pin': 0,
  'multicore_same': 2,
  'is_multicore': 0,
  'max_categories_multicore': 8,
  'distance_to_center': 19751.199887601764,
  'neighbors': ['8', '1', '2']},
 '8': {'PreferredSignal': 'na',
  'Cat_PreferredSignal': 27,
  'Signal': 'EQ_FUEL_PRESS_SSR_HI-TNGA_PR',
  'Cat_Signal': 3,
  'dicc_signals': "{0: 'CLEARANCE_SNR_ECU_0885', 1: 'CLEARANCE_SNR_ECU_0890', 2: 'EQ_FUEL_PRESS_SSR_HI-TNGA_E2', 3: 'EQ_FUEL_PRESS_SSR_HI-TNGA_PR', 4: 'EQ_FUEL_PRESS_SSR_HI-TNGA_VC', 5: 'EQ_NE_SSR-TNGA_NE-', 6: 'EQ_NE_SSR-TNGA_NEP', 7: 'EQ_NE_SSR-TNGA_VCNE', 8: 'EQ_PDB_L_1', 9: 'EQ_PDB_L_2', 10: 'EQ_PDB_L_5', 11: 'GND_BK_UP_LP_LH_E', 12: 'HV_ECU-HV_0024', 13: 'HV_ECU-HV_0025', 14: 'SLD_EFI_ECU-TNGA_KNOCK_SSR_101', 15: 'SLD_EFI_ECU-TNGA_KNOCK_SSR_102', 16: 'SLD_MG_ECU_197', 17: 'SLD_MG_ECU_198', 18: 'SLD_MG_ECU_199', 19: 'SLD_MG_ECU_200', 20: 'SLD_MG_ECU_201', 21: 'SLD_MG_ECU_202', 22: 'SLD_MG_ECU_203', 23: 'TW_CLEARANCE_SNR_ECU_055', 24: 'TW_CLEARANCE_SNR_ECU_056', 25: 'TW_CLEARANCE_SNR_ECU_061', 26: 'TW_CLEARANCE_SNR_ECU_062', 27: 'na'}",
  'check_signal': 0,
  'Num_Pins': 13,
  'Num_Pin_unique': 13,
  'more_signal_in_pin': False,
  'WireColor': 'P',
  'WireCSA': 0.35,
  'Multicore': 'na',
  'signal_group': 7,
  'internal_pin': 'False',
  'neighbors_length': 5,
  'mean_neighbors': 17933.96534314784,
  'centroide_distance': 17408.414866379993,
  'number_internal_pin': 2.0,
  'max_distance': 23124.761296065306,
  'min_distance': 9604.020824633815,
  'Cat_Wire_WireColor': 23,
  'Cat_Wire_WireColor_max': 30,
  'Wire_WireCSA_min': 0.0,
  'Wire_WireCSA_max': 8.0,
  'Num_Pin_unique_max': 55,
  'no_signal_pin': 0,
  'multicore_same': 2,
  'is_multicore': 0,
  'max_categories_multicore': 8,
  'distance_to_center': 14982.116572767682,
  'neighbors': ['9', '7', '2', '3', '1']},
 '9': {'PreferredSignal': 'na',
  'Cat_PreferredSignal': 27,
  'Signal': 'EQ_FUEL_PRESS_SSR_HI-TNGA_VC',
  'Cat_Signal': 4,
  'dicc_signals': "{0: 'CLEARANCE_SNR_ECU_0885', 1: 'CLEARANCE_SNR_ECU_0890', 2: 'EQ_FUEL_PRESS_SSR_HI-TNGA_E2', 3: 'EQ_FUEL_PRESS_SSR_HI-TNGA_PR', 4: 'EQ_FUEL_PRESS_SSR_HI-TNGA_VC', 5: 'EQ_NE_SSR-TNGA_NE-', 6: 'EQ_NE_SSR-TNGA_NEP', 7: 'EQ_NE_SSR-TNGA_VCNE', 8: 'EQ_PDB_L_1', 9: 'EQ_PDB_L_2', 10: 'EQ_PDB_L_5', 11: 'GND_BK_UP_LP_LH_E', 12: 'HV_ECU-HV_0024', 13: 'HV_ECU-HV_0025', 14: 'SLD_EFI_ECU-TNGA_KNOCK_SSR_101', 15: 'SLD_EFI_ECU-TNGA_KNOCK_SSR_102', 16: 'SLD_MG_ECU_197', 17: 'SLD_MG_ECU_198', 18: 'SLD_MG_ECU_199', 19: 'SLD_MG_ECU_200', 20: 'SLD_MG_ECU_201', 21: 'SLD_MG_ECU_202', 22: 'SLD_MG_ECU_203', 23: 'TW_CLEARANCE_SNR_ECU_055', 24: 'TW_CLEARANCE_SNR_ECU_056', 25: 'TW_CLEARANCE_SNR_ECU_061', 26: 'TW_CLEARANCE_SNR_ECU_062', 27: 'na'}",
  'check_signal': 0,
  'Num_Pins': 13,
  'Num_Pin_unique': 13,
  'more_signal_in_pin': False,
  'WireColor': 'BR',
  'WireCSA': 0.35,
  'Multicore': 'na',
  'signal_group': 7,
  'internal_pin': 'False',
  'neighbors_length': 4,
  'mean_neighbors': 15048.917100535498,
  'centroide_distance': 14405.845430327927,
  'number_internal_pin': 2.0,
  'max_distance': 23124.761296065306,
  'min_distance': 9604.020824633815,
  'Cat_Wire_WireColor': 3,
  'Cat_Wire_WireColor_max': 30,
  'Wire_WireCSA_min': 0.0,
  'Wire_WireCSA_max': 8.0,
  'Num_Pin_unique_max': 55,
  'no_signal_pin': 0,
  'multicore_same': 2,
  'is_multicore': 0,
  'max_categories_multicore': 8,
  'distance_to_center': 11188.07119212244,
  'neighbors': ['10', '8', '3', '2']},
 '10': {'PreferredSignal': 'na',
  'Cat_PreferredSignal': 27,
  'Signal': 'na',
  'Cat_Signal': 27,
  'dicc_signals': "{0: 'CLEARANCE_SNR_ECU_0885', 1: 'CLEARANCE_SNR_ECU_0890', 2: 'EQ_FUEL_PRESS_SSR_HI-TNGA_E2', 3: 'EQ_FUEL_PRESS_SSR_HI-TNGA_PR', 4: 'EQ_FUEL_PRESS_SSR_HI-TNGA_VC', 5: 'EQ_NE_SSR-TNGA_NE-', 6: 'EQ_NE_SSR-TNGA_NEP', 7: 'EQ_NE_SSR-TNGA_VCNE', 8: 'EQ_PDB_L_1', 9: 'EQ_PDB_L_2', 10: 'EQ_PDB_L_5', 11: 'GND_BK_UP_LP_LH_E', 12: 'HV_ECU-HV_0024', 13: 'HV_ECU-HV_0025', 14: 'SLD_EFI_ECU-TNGA_KNOCK_SSR_101', 15: 'SLD_EFI_ECU-TNGA_KNOCK_SSR_102', 16: 'SLD_MG_ECU_197', 17: 'SLD_MG_ECU_198', 18: 'SLD_MG_ECU_199', 19: 'SLD_MG_ECU_200', 20: 'SLD_MG_ECU_201', 21: 'SLD_MG_ECU_202', 22: 'SLD_MG_ECU_203', 23: 'TW_CLEARANCE_SNR_ECU_055', 24: 'TW_CLEARANCE_SNR_ECU_056', 25: 'TW_CLEARANCE_SNR_ECU_061', 26: 'TW_CLEARANCE_SNR_ECU_062', 27: 'na'}",
  'check_signal': 2,
  'Num_Pins': 13,
  'Num_Pin_unique': 13,
  'more_signal_in_pin': False,
  'WireColor': 'na',
  'WireCSA': 0.0,
  'Multicore': 'na',
  'signal_group': 7,
  'internal_pin': 'False',
  'neighbors_length': 4,
  'mean_neighbors': 13803.33577568975,
  'centroide_distance': 12484.004846202199,
  'number_internal_pin': 2.0,
  'max_distance': 23124.761296065306,
  'min_distance': 9604.020824633815,
  'Cat_Wire_WireColor': 30,
  'Cat_Wire_WireColor_max': 30,
  'Wire_WireCSA_min': 0.0,
  'Wire_WireCSA_max': 8.0,
  'Num_Pin_unique_max': 55,
  'no_signal_pin': 1,
  'multicore_same': 2,
  'is_multicore': 0,
  'max_categories_multicore': 8,
  'distance_to_center': 9604.020824633815,
  'neighbors': ['9', '11', '4', '3']},
 '11': {'PreferredSignal': 'na',
  'Cat_PreferredSignal': 27,
  'Signal': 'na',
  'Cat_Signal': 27,
  'dicc_signals': "{0: 'CLEARANCE_SNR_ECU_0885', 1: 'CLEARANCE_SNR_ECU_0890', 2: 'EQ_FUEL_PRESS_SSR_HI-TNGA_E2', 3: 'EQ_FUEL_PRESS_SSR_HI-TNGA_PR', 4: 'EQ_FUEL_PRESS_SSR_HI-TNGA_VC', 5: 'EQ_NE_SSR-TNGA_NE-', 6: 'EQ_NE_SSR-TNGA_NEP', 7: 'EQ_NE_SSR-TNGA_VCNE', 8: 'EQ_PDB_L_1', 9: 'EQ_PDB_L_2', 10: 'EQ_PDB_L_5', 11: 'GND_BK_UP_LP_LH_E', 12: 'HV_ECU-HV_0024', 13: 'HV_ECU-HV_0025', 14: 'SLD_EFI_ECU-TNGA_KNOCK_SSR_101', 15: 'SLD_EFI_ECU-TNGA_KNOCK_SSR_102', 16: 'SLD_MG_ECU_197', 17: 'SLD_MG_ECU_198', 18: 'SLD_MG_ECU_199', 19: 'SLD_MG_ECU_200', 20: 'SLD_MG_ECU_201', 21: 'SLD_MG_ECU_202', 22: 'SLD_MG_ECU_203', 23: 'TW_CLEARANCE_SNR_ECU_055', 24: 'TW_CLEARANCE_SNR_ECU_056', 25: 'TW_CLEARANCE_SNR_ECU_061', 26: 'TW_CLEARANCE_SNR_ECU_062', 27: 'na'}",
  'check_signal': 2,
  'Num_Pins': 13,
  'Num_Pin_unique': 13,
  'more_signal_in_pin': False,
  'WireColor': 'na',
  'WireCSA': 0.0,
  'Multicore': 'na',
  'signal_group': 7,
  'internal_pin': 'False',
  'neighbors_length': 4,
  'mean_neighbors': 15057.503055870677,
  'centroide_distance': 14416.71135349529,
  'number_internal_pin': 2.0,
  'max_distance': 23124.761296065306,
  'min_distance': 9604.020824633815,
  'Cat_Wire_WireColor': 30,
  'Cat_Wire_WireColor_max': 30,
  'Wire_WireCSA_min': 0.0,
  'Wire_WireCSA_max': 8.0,
  'Num_Pin_unique_max': 55,
  'no_signal_pin': 1,
  'multicore_same': 2,
  'is_multicore': 0,
  'max_categories_multicore': 8,
  'distance_to_center': 11209.157684679076,
  'neighbors': ['10', '12', '4', '5']},
 '12': {'PreferredSignal': 'na',
  'Cat_PreferredSignal': 27,
  'Signal': 'na',
  'Cat_Signal': 27,
  'dicc_signals': "{0: 'CLEARANCE_SNR_ECU_0885', 1: 'CLEARANCE_SNR_ECU_0890', 2: 'EQ_FUEL_PRESS_SSR_HI-TNGA_E2', 3: 'EQ_FUEL_PRESS_SSR_HI-TNGA_PR', 4: 'EQ_FUEL_PRESS_SSR_HI-TNGA_VC', 5: 'EQ_NE_SSR-TNGA_NE-', 6: 'EQ_NE_SSR-TNGA_NEP', 7: 'EQ_NE_SSR-TNGA_VCNE', 8: 'EQ_PDB_L_1', 9: 'EQ_PDB_L_2', 10: 'EQ_PDB_L_5', 11: 'GND_BK_UP_LP_LH_E', 12: 'HV_ECU-HV_0024', 13: 'HV_ECU-HV_0025', 14: 'SLD_EFI_ECU-TNGA_KNOCK_SSR_101', 15: 'SLD_EFI_ECU-TNGA_KNOCK_SSR_102', 16: 'SLD_MG_ECU_197', 17: 'SLD_MG_ECU_198', 18: 'SLD_MG_ECU_199', 19: 'SLD_MG_ECU_200', 20: 'SLD_MG_ECU_201', 21: 'SLD_MG_ECU_202', 22: 'SLD_MG_ECU_203', 23: 'TW_CLEARANCE_SNR_ECU_055', 24: 'TW_CLEARANCE_SNR_ECU_056', 25: 'TW_CLEARANCE_SNR_ECU_061', 26: 'TW_CLEARANCE_SNR_ECU_062', 27: 'na'}",
  'check_signal': 2,
  'Num_Pins': 13,
  'Num_Pin_unique': 13,
  'more_signal_in_pin': False,
  'WireColor': 'na',
  'WireCSA': 0.0,
  'Multicore': 'na',
  'signal_group': 7,
  'internal_pin': 'False',
  'neighbors_length': 5,
  'mean_neighbors': 17946.667849923077,
  'centroide_distance': 17420.718727997417,
  'number_internal_pin': 2.0,
  'max_distance': 23124.761296065306,
  'min_distance': 9604.020824633815,
  'Cat_Wire_WireColor': 30,
  'Cat_Wire_WireColor_max': 30,
  'Wire_WireCSA_min': 0.0,
  'Wire_WireCSA_max': 8.0,
  'Num_Pin_unique_max': 55,
  'no_signal_pin': 1,
  'multicore_same': 2,
  'is_multicore': 0,
  'max_categories_multicore': 8,
  'distance_to_center': 15013.607694355145,
  'neighbors': ['13', '11', '5', '6', '4']},
 '13': {'PreferredSignal': 'na',
  'Cat_PreferredSignal': 27,
  'Signal': 'na',
  'Cat_Signal': 27,

In [179]:
dicc_13={0: 'CLEARANCE_SNR_ECU_0885', 1: 'CLEARANCE_SNR_ECU_0890', 2: 'EQ_FUEL_PRESS_SSR_HI-TNGA_E2', 3: 'EQ_FUEL_PRESS_SSR_HI-TNGA_PR', 4: 'EQ_FUEL_PRESS_SSR_HI-TNGA_VC', 5: 'EQ_NE_SSR-TNGA_NE-', 6: 'EQ_NE_SSR-TNGA_NEP', 7: 'EQ_NE_SSR-TNGA_VCNE', 8: 'EQ_PDB_L_1', 9: 'EQ_PDB_L_2', 10: 'EQ_PDB_L_5', 11: 'GND_BK_UP_LP_LH_E', 12: 'HV_ECU-HV_0024', 13: 'HV_ECU-HV_0025', 14: 'SLD_EFI_ECU-TNGA_KNOCK_SSR_101', 15: 'SLD_EFI_ECU-TNGA_KNOCK_SSR_102', 16: 'SLD_MG_ECU_197', 17: 'SLD_MG_ECU_198', 18: 'SLD_MG_ECU_199', 19: 'SLD_MG_ECU_200', 20: 'SLD_MG_ECU_201', 21: 'SLD_MG_ECU_202', 22: 'SLD_MG_ECU_203', 23: 'TW_CLEARANCE_SNR_ECU_055', 24: 'TW_CLEARANCE_SNR_ECU_056', 25: 'TW_CLEARANCE_SNR_ECU_061', 26: 'TW_CLEARANCE_SNR_ECU_062', 27: 'na'}

In [180]:
num_signals=len(dicc_13.keys())
Num_Pins, num_signals

(13, 28)

In [181]:
import random
import pandas as pd

In [182]:
cols=[str(i) for i in range(1,Num_Pins+1 )]

In [183]:
data_test= pd.DataFrame(data=[], columns=cols)
data_test.head()

Empty DataFrame
Columns: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
Index: []

In [184]:
for x in range(0,500):
    variant=[]
    data={}
    for i in range(0, Num_Pins):
        variant.append(random.randint(0, num_signals-1))
        data[str(i+1)]=random.randint(0, num_signals-1)
    data_test= data_test.append(data, ignore_index=True)
    print(variant)

[24, 13, 4, 0, 17, 19, 11, 27, 20, 27, 25, 24, 4]
[11, 20, 6, 12, 25, 13, 21, 24, 3, 10, 13, 6, 10]
[8, 12, 24, 0, 11, 0, 11, 12, 4, 7, 3, 8, 12]
[1, 26, 10, 14, 0, 0, 18, 7, 13, 13, 15, 21, 18]
[15, 20, 22, 0, 26, 6, 6, 5, 2, 1, 20, 12, 12]
[11, 1, 7, 7, 21, 20, 17, 11, 11, 4, 23, 12, 22]
[25, 4, 16, 11, 6, 19, 12, 4, 24, 21, 7, 10, 18]
[23, 11, 12, 22, 9, 14, 22, 10, 9, 20, 11, 8, 0]
[12, 15, 22, 6, 8, 16, 23, 19, 8, 26, 27, 22, 12]
[12, 23, 12, 16, 13, 0, 19, 16, 11, 21, 4, 0, 27]
[20, 19, 8, 11, 22, 16, 16, 18, 1, 7, 22, 12, 6]
[16, 14, 12, 9, 23, 4, 10, 14, 19, 20, 17, 23, 21]
[6, 2, 6, 24, 17, 13, 4, 12, 11, 6, 5, 6, 8]
[7, 5, 22, 14, 21, 25, 12, 2, 0, 11, 20, 22, 12]
[7, 3, 24, 7, 1, 1, 27, 18, 6, 7, 17, 5, 23]
[25, 8, 15, 15, 24, 27, 4, 17, 27, 11, 9, 21, 27]
[13, 24, 11, 26, 9, 19, 12, 6, 26, 17, 4, 17, 20]
[24, 24, 20, 13, 12, 3, 13, 25, 15, 6, 8, 16, 5]
[10, 19, 7, 23, 13, 13, 13, 20, 1, 19, 11, 24, 1]
[26, 27, 0, 24, 26, 25, 0, 17, 1, 15, 24, 25, 8]
[7, 23, 5, 12, 17, 15, 2, 16, 2, 19, 6, 26, 5]
[23, 2, 15, 6, 17, 26, 14, 2, 2, 13, 25, 17, 24]
[17, 17, 24, 26, 8, 8, 18, 8, 0, 23, 25, 0, 19]
[16, 3, 10, 2, 10, 6, 19, 4, 23, 25, 18, 13, 13]
[3, 14, 21, 0, 25, 24, 4, 0, 1, 24, 27, 8, 6]
[16, 0, 17, 15, 26, 13, 23, 8, 13, 10, 0, 13, 4]
[13, 15, 9, 17, 2, 4, 18, 25, 17, 2, 6, 9, 5]
[14, 0, 24, 7, 6, 6, 6, 14, 23, 6, 26, 13, 14]
[14, 17, 24, 18, 9, 24, 7, 16, 2, 3, 12, 13, 22]
[18, 3, 21, 5, 3, 23, 15, 7, 18, 8, 12, 18, 20]
[2, 12, 27, 7, 13, 14, 6, 20, 24, 5, 16, 0, 19]
[2, 27, 24, 1, 25, 27, 16, 25, 11, 24, 22, 16, 26]
[12, 10, 26, 25, 23, 4, 17, 4, 13, 8, 3, 26, 8]
[25, 20, 17, 18, 14, 6, 22, 23, 25, 7, 11, 27, 18]
[18, 23, 24, 3, 7, 24, 6, 5, 23, 11, 11, 23, 3]
[9, 18, 3, 12, 9, 13, 18, 9, 5, 21, 17, 11, 1]
[8, 26, 12, 26, 3, 17, 27, 22, 16, 5, 6, 12, 11]
[12, 12, 6, 17, 1, 27, 20, 19, 19, 15, 18, 2, 18]
[14, 13, 22, 26, 14, 11, 2, 27, 14, 26, 7, 21, 18]
[0, 19, 6, 7, 6, 9, 17, 12, 8, 14, 27, 21, 9]
[9, 14, 20, 7, 2, 26, 3, 13, 27, 11, 24, 19, 25]
[12, 25, 10, 9, 16, 7, 13, 9, 10, 20, 3, 24, 11]
[23, 9, 15, 7, 1, 4, 18, 15, 1, 10, 11, 0, 20]
[17, 26, 14, 17, 8, 1, 23, 13, 7, 6, 4, 8, 21]
[14, 2, 0, 24, 20, 23, 23, 16, 1, 27, 16, 15, 8]
[9, 13, 19, 24, 9, 13, 12, 25, 6, 0, 19, 14, 0]
[20, 24, 19, 23, 0, 26, 11, 27, 0, 24, 7, 8, 19]
[6, 0, 25, 18, 27, 23, 27, 21, 12, 0, 14, 21, 5]
[2, 14, 6, 26, 17, 16, 16, 14, 5, 4, 16, 19, 24]
[19, 21, 17, 11, 8, 12, 27, 19, 0, 8, 17, 7, 4]
[17, 9, 6, 24, 8, 5, 22, 12, 25, 9, 6, 6, 7]
[12, 8, 6, 0, 22, 19, 15, 15, 23, 9, 6, 21, 8]
[7, 17, 7, 6, 25, 16, 5, 25, 8, 24, 2, 21, 26]
[8, 20, 9, 23, 4, 15, 4, 16, 4, 3, 22, 7, 22]
[7, 19, 16, 22, 8, 4, 0, 9, 6, 24, 25, 14, 12]
[18, 0, 7, 12, 4, 27, 11, 2, 22, 3, 8, 11, 25]
[15, 2, 26, 22, 0, 2, 14, 23, 25, 11, 27, 18, 12]
[1, 14, 2, 9, 10, 0, 15, 4, 9, 7, 6, 7, 15]
[25, 24, 5, 25, 6, 26, 7, 23, 22, 9, 27, 15, 26]
[23, 21, 13, 26, 10, 22, 25, 13, 3, 23, 22, 9, 9]
[14, 6, 4, 7, 15, 9, 23, 5, 20, 1, 23, 13, 5]
[25, 5, 18, 18, 18, 2, 19, 24, 18, 18, 25, 5, 9]
[21, 0, 7, 22, 7, 16, 25, 24, 23, 25, 6, 23, 22]
[13, 5, 12, 1, 26, 25, 15, 23, 11, 27, 6, 24, 26]
[1, 14, 4, 12, 6, 3, 4, 25, 22, 20, 2, 11, 17]
[4, 13, 26, 6, 5, 12, 13, 1, 22, 19, 16, 22, 2]
[3, 12, 23, 14, 20, 3, 17, 22, 9, 11, 11, 27, 3]
[2, 16, 26, 5, 1, 25, 23, 11, 14, 17, 9, 0, 8]
[14, 16, 14, 24, 12, 17, 3, 24, 27, 5, 10, 2, 21]
[12, 17, 21, 19, 4, 9, 10, 12, 12, 26, 8, 2, 11]
[6, 18, 2, 12, 25, 24, 25, 14, 26, 7, 21, 27, 16]
[6, 25, 21, 12, 26, 18, 21, 26, 13, 3, 6, 27, 4]
[27, 18, 12, 19, 19, 11, 20, 27, 21, 9, 18, 10, 16]
[15, 20, 10, 26, 15, 24, 16, 14, 19, 0, 14, 2, 6]
[4, 2, 7, 13, 11, 1, 2, 20, 7, 5, 23, 3, 4]
[0, 12, 21, 2, 4, 27, 27, 19, 17, 17, 13, 23, 24]
[19, 26, 26, 7, 2, 6, 16, 27, 11, 27, 7, 19, 9]
[18, 5, 11, 18, 0, 24, 1, 13, 12, 14, 1, 8, 22]
[4, 5, 8, 12, 21, 18, 3, 13, 0, 26, 13, 4, 9]
[21, 15, 26, 7, 19, 2, 4, 5, 19, 1, 2, 14, 3]
[9, 15, 11, 22, 21, 1, 5, 21, 3, 0, 18, 2, 1]
[9, 17, 23, 22, 27, 27, 20, 5, 21, 17, 6, 21, 27]
[3, 5, 7, 3, 6, 23, 0, 14, 12, 5, 27, 10, 22]
[10, 3, 8, 19, 7, 4, 10, 10, 13, 17, 12, 1, 16]
[13, 9, 11, 16, 25, 24, 15, 26, 16, 0, 5, 14, 10]
[1, 0, 21, 25, 8, 8, 9, 15, 23, 7, 5, 0, 12]
[0, 5, 24, 5, 14, 5, 4, 7, 0, 21, 1, 5, 18]
[24, 9, 20, 8, 11, 25, 25, 17, 8, 4, 6, 5, 20]
[25, 15, 7, 9, 12, 13, 21, 25, 24, 19, 1, 7, 21]
[2, 9, 4, 9, 16, 3, 9, 4, 19, 5, 8, 13, 7]
[18, 18, 24, 9, 27, 11, 26, 3, 26, 15, 2, 24, 9]
[2, 9, 11, 9, 9, 22, 3, 6, 19, 2, 22, 20, 13]
[3, 17, 9, 8, 26, 12, 0, 22, 10, 4, 17, 26, 18]
[1, 22, 9, 25, 6, 13, 19, 8, 12, 1, 27, 3, 27]
[2, 19, 4, 24, 24, 14, 27, 27, 17, 26, 6, 25, 11]
[12, 12, 1, 17, 0, 22, 12, 24, 23, 23, 14, 23, 17]
[22, 9, 4, 9, 25, 8, 25, 7, 25, 17, 14, 4, 9]
[21, 5, 15, 22, 26, 15, 15, 19, 21, 9, 8, 25, 1]
[20, 5, 18, 17, 17, 7, 5, 20, 27, 1, 18, 13, 14]
[0, 7, 16, 3, 21, 15, 20, 0, 1, 19, 15, 2, 5]
[0, 14, 17, 2, 19, 24, 10, 16, 25, 7, 10, 13, 2]
[4, 13, 21, 3, 25, 2, 3, 27, 26, 12, 18, 2, 19]
[14, 5, 15, 17, 9, 19, 9, 6, 22, 10, 8, 6, 24]
[10, 23, 27, 21, 20, 15, 22, 19, 7, 0, 6, 21, 27]
[9, 14, 5, 3, 18, 7, 6, 10, 3, 16, 26, 9, 16]
[19, 22, 22, 4, 27, 24, 8, 0, 2, 21, 24, 24, 22]
[7, 18, 27, 13, 10, 24, 26, 15, 25, 4, 22, 7, 1]
[3, 8, 6, 22, 3, 13, 12, 18, 2, 19, 17, 7, 12]
[15, 17, 13, 26, 12, 18, 14, 15, 25, 24, 5, 11, 25]
[16, 8, 21, 4, 11, 4, 4, 7, 5, 23, 13, 15, 7]
[16, 3, 16, 9, 24, 12, 0, 19, 3, 19, 3, 24, 26]
[15, 11, 24, 13, 26, 9, 4, 6, 12, 23, 21, 6, 22]
[6, 11, 8, 1, 21, 10, 20, 11, 0, 25, 3, 21, 10]
[4, 21, 22, 19, 1, 23, 16, 23, 11, 4, 23, 23, 9]
[19, 1, 18, 27, 25, 7, 4, 2, 10, 1, 1, 9, 2]
[7, 13, 0, 10, 8, 21, 11, 4, 17, 24, 22, 16, 23]
[26, 2, 25, 12, 2, 5, 6, 6, 2, 22, 18, 7, 15]
[4, 25, 22, 3, 26, 4, 15, 10, 20, 26, 15, 6, 12]
[12, 4, 8, 12, 8, 23, 3, 7, 24, 10, 17, 27, 14]
[10, 11, 20, 9, 17, 6, 21, 3, 10, 12, 15, 2, 4]
[16, 0, 9, 1, 27, 23, 10, 9, 17, 16, 2, 23, 19]
[27, 5, 5, 3, 25, 10, 6, 21, 27, 3, 15, 8, 17]
[19, 1, 15, 26, 3, 26, 1, 17, 0, 16, 21, 10, 8]
[11, 6, 14, 14, 15, 13, 12, 8, 0, 13, 4, 26, 3]
[17, 16, 2, 24, 27, 0, 14, 15, 14, 5, 3, 14, 9]
[1, 17, 10, 2, 21, 0, 14, 21, 0, 17, 22, 2, 13]
[0, 11, 7, 12, 26, 10, 17, 4, 14, 0, 22, 11, 23]
[17, 20, 13, 23, 9, 23, 17, 11, 5, 16, 22, 21, 22]
[20, 20, 12, 0, 11, 22, 21, 6, 9, 19, 14, 17, 27]
[13, 23, 11, 14, 21, 21, 1, 19, 14, 10, 10, 27, 7]
[1, 13, 9, 8, 5, 12, 20, 15, 5, 23, 18, 27, 2]
[14, 18, 1, 5, 18, 14, 18, 21, 20, 0, 4, 11, 8]
[3, 26, 11, 13, 11, 22, 10, 5, 8, 25, 20, 23, 20]
[20, 18, 0, 23, 19, 13, 7, 17, 23, 27, 26, 27, 22]
[13, 22, 10, 14, 18, 7, 21, 6, 19, 13, 0, 26, 25]
[17, 10, 6, 17, 5, 27, 5, 0, 12, 16, 26, 20, 14]
[13, 26, 21, 7, 6, 16, 12, 15, 18, 8, 10, 20, 22]
[4, 9, 26, 4, 1, 23, 4, 3, 9, 25, 23, 8, 6]
[21, 22, 7, 0, 21, 23, 16, 1, 11, 0, 9, 4, 8]
[11, 5, 1, 25, 7, 25, 24, 24, 26, 22, 27, 26, 25]
[12, 6, 24, 19, 13, 20, 20, 16, 21, 0, 5, 17, 2]
[19, 9, 23, 3, 1, 26, 22, 24, 5, 14, 19, 20, 7]
[11, 15, 20, 4, 15, 9, 0, 0, 15, 22, 22, 0, 21]
[23, 6, 12, 12, 4, 5, 14, 9, 9, 1, 16, 8, 15]
[16, 6, 9, 18, 27, 26, 19, 2, 21, 4, 15, 20, 16]
[4, 1, 3, 7, 10, 24, 18, 17, 1, 16, 0, 22, 15]
[1, 8, 6, 13, 24, 20, 23, 0, 24, 23, 20, 23, 9]
[14, 3, 16, 4, 22, 27, 13, 8, 2, 21, 12, 4, 19]
[6, 17, 15, 8, 5, 13, 24, 0, 9, 2, 1, 17, 4]
[0, 2, 11, 8, 7, 8, 12, 18, 0, 6, 2, 4, 19]
[12, 22, 21, 1, 12, 21, 1, 6, 12, 24, 8, 3, 27]
[3, 13, 26, 16, 3, 4, 9, 27, 22, 9, 16, 0, 27]
[5, 27, 24, 25, 19, 6, 18, 12, 21, 24, 15, 24, 10]
[4, 21, 1, 7, 4, 15, 20, 3, 2, 13, 24, 22, 11]
[17, 14, 8, 4, 4, 18, 14, 7, 22, 9, 3, 7, 3]
[9, 23, 12, 7, 24, 9, 5, 24, 26, 1, 1, 12, 7]
[11, 22, 1, 4, 7, 0, 2, 20, 7, 3, 10, 15, 21]
[14, 13, 22, 20, 16, 0, 16, 12, 22, 16, 25, 1, 13]
[17, 8, 0, 1, 8, 25, 25, 27, 15, 13, 16, 0, 21]
[0, 14, 27, 0, 21, 6, 5, 26, 22, 25, 15, 26, 10]
[18, 24, 13, 4, 6, 2, 25, 25, 1, 27, 26, 19, 15]
[18, 14, 7, 11, 24, 8, 21, 16, 13, 26, 22, 7, 22]
[6, 24, 21, 9, 23, 20, 15, 17, 11, 22, 12, 25, 21]
[13, 0, 24, 14, 18, 19, 18, 9, 1, 8, 8, 9, 13]
[19, 6, 8, 19, 5, 14, 16, 23, 15, 9, 6, 3, 7]
[3, 20, 12, 21, 13, 11, 8, 20, 7, 7, 19, 3, 23]
[22, 27, 15, 2, 4, 5, 15, 7, 8, 20, 8, 16, 9]
[22, 23, 22, 24, 27, 2, 15, 11, 20, 4, 19, 24, 23]
[14, 19, 12, 20, 16, 23, 5, 10, 18, 8, 22, 5, 6]
[1, 21, 14, 18, 5, 15, 22, 19, 20, 16, 0, 17, 21]
[0, 19, 10, 27, 7, 21, 22, 27, 21, 15, 12, 14, 2]
[27, 14, 2, 1, 6, 11, 0, 16, 20, 24, 6, 2, 14]
[25, 21, 18, 13, 25, 26, 14, 20, 13, 20, 23, 26, 12]
[13, 11, 11, 13, 16, 13, 3, 12, 5, 8, 10, 15, 5]
[6, 9, 1, 13, 24, 1, 14, 0, 10, 20, 10, 6, 13]
[23, 22, 18, 17, 7, 19, 19, 18, 0, 13, 15, 0, 3]
[27, 24, 3, 25, 14, 4, 23, 16, 0, 14, 6, 11, 3]
[6, 1, 8, 24, 26, 25, 16, 0, 14, 12, 14, 27, 12]
[14, 1, 4, 21, 5, 24, 18, 5, 14, 15, 15, 0, 27]
[4, 13, 7, 1, 24, 15, 25, 2, 6, 14, 22, 0, 20]
[14, 21, 19, 13, 26, 22, 0, 18, 12, 14, 12, 4, 8]
[18, 18, 24, 4, 17, 6, 18, 24, 6, 4, 4, 14, 0]
[9, 0, 3, 9, 0, 5, 4, 24, 12, 25, 21, 24, 4]
[27, 20, 12, 1, 15, 23, 25, 26, 24, 24, 6, 3, 17]
[18, 21, 19, 25, 2, 20, 9, 7, 14, 20, 10, 13, 15]
[17, 1, 12, 20, 14, 9, 6, 15, 7, 24, 8, 11, 21]
[15, 14, 14, 25, 27, 20, 15, 11, 9, 4, 16, 24, 6]
[14, 6, 3, 17, 3, 15, 22, 14, 15, 11, 20, 22, 21]
[20, 23, 5, 20, 2, 0, 1, 21, 1, 20, 21, 2, 20]
[14, 15, 7, 3, 2, 7, 17, 16, 15, 15, 0, 7, 5]
[19, 17, 11, 23, 18, 26, 22, 0, 21, 3, 25, 25, 4]
[19, 25, 13, 10, 6, 25, 0, 11, 9, 6, 14, 17, 10]
[22, 5, 21, 3, 14, 12, 18, 6, 23, 26, 22, 8, 11]
[0, 16, 1, 6, 23, 26, 12, 22, 6, 21, 0, 25, 24]
[19, 4, 20, 2, 15, 23, 16, 17, 12, 13, 18, 0, 0]
[22, 25, 1, 26, 16, 10, 3, 7, 13, 14, 14, 1, 2]
[14, 12, 3, 20, 7, 11, 25, 20, 7, 24, 20, 16, 18]
[16, 18, 2, 22, 5, 1, 16, 19, 25, 22, 5, 15, 8]
[16, 25, 0, 1, 1, 18, 11, 24, 20, 13, 17, 2, 16]
[21, 7, 20, 2, 13, 22, 22, 20, 15, 21, 17, 11, 20]
[16, 19, 8, 7, 26, 10, 6, 20, 8, 9, 20, 12, 11]
[12, 26, 13, 21, 1, 19, 20, 11, 2, 12, 1, 24, 20]
[15, 2, 20, 18, 16, 22, 10, 25, 13, 22, 25, 9, 23]
[11, 26, 19, 24, 11, 27, 17, 26, 25, 23, 0, 0, 23]
[18, 5, 3, 10, 12, 14, 16, 22, 12, 25, 19, 20, 7]
[15, 20, 13, 13, 16, 15, 9, 27, 5, 25, 24, 5, 24]
[11, 11, 2, 19, 7, 2, 25, 8, 12, 20, 7, 14, 3]
[20, 6, 10, 4, 20, 27, 23, 20, 14, 26, 17, 15, 15]
[2, 13, 5, 6, 8, 12, 21, 14, 27, 1, 0, 4, 13]
[18, 18, 1, 4, 17, 6, 22, 1, 11, 26, 17, 24, 24]
[22, 5, 16, 20, 7, 18, 10, 23, 23, 2, 16, 3, 26]
[6, 0, 11, 22, 5, 20, 19, 16, 6, 23, 1, 0, 13]
[10, 27, 20, 12, 4, 23, 27, 23, 6, 17, 9, 2, 10]
[16, 22, 4, 16, 11, 5, 1, 7, 15, 8, 26, 25, 18]
[23, 27, 7, 22, 10, 10, 13, 19, 11, 14, 16, 18, 17]
[6, 13, 19, 22, 5, 23, 10, 9, 11, 8, 2, 7, 20]
[22, 3, 1, 1, 15, 14, 26, 19, 21, 5, 10, 10, 4]
[1, 14, 25, 1, 4, 19, 14, 8, 14, 18, 0, 22, 1]
[22, 15, 22, 9, 18, 18, 18, 14, 16, 15, 0, 8, 24]
[5, 17, 20, 14, 22, 23, 10, 9, 3, 23, 0, 27, 17]
[13, 23, 5, 1, 17, 21, 25, 13, 21, 9, 4, 24, 12]
[19, 4, 21, 26, 26, 26, 7, 27, 19, 6, 19, 9, 17]
[16, 0, 19, 8, 20, 14, 20, 0, 14, 3, 10, 5, 11]
[18, 24, 19, 18, 23, 11, 13, 21, 16, 9, 14, 5, 27]
[11, 5, 17, 6, 0, 23, 15, 25, 24, 27, 15, 22, 13]
[10, 23, 24, 13, 9, 17, 10, 3, 7, 10, 13, 4, 7]
[8, 23, 3, 18, 12, 1, 26, 17, 19, 17, 2, 27, 9]
[0, 25, 16, 13, 6, 15, 2, 21, 10, 27, 23, 17, 9]
[12, 16, 24, 2, 19, 2, 12, 7, 17, 10, 21, 20, 11]
[3, 22, 17, 18, 4, 12, 2, 16, 22, 9, 19, 25, 14]
[4, 15, 7, 23, 1, 4, 4, 14, 24, 10, 7, 2, 5]
[11, 20, 9, 23, 23, 27, 9, 0, 1, 12, 17, 17, 15]
[4, 7, 1, 19, 4, 2, 25, 1, 4, 9, 25, 6, 2]
[18, 9, 7, 25, 16, 1, 13, 16, 7, 5, 5, 7, 20]
[2, 17, 4, 12, 19, 1, 13, 7, 21, 12, 19, 15, 23]
[5, 24, 23, 14, 15, 11, 1, 23, 17, 11, 12, 20, 23]
[10, 14, 19, 22, 0, 10, 12, 0, 24, 14, 20, 11, 11]
[9, 19, 5, 11, 0, 1, 9, 15, 9, 23, 17, 1, 22]
[11, 5, 18, 14, 16, 19, 16, 24, 13, 23, 6, 8, 8]
[20, 23, 7, 25, 23, 24, 11, 5, 6, 22, 17, 20, 4]
[1, 2, 11, 20, 14, 2, 14, 17, 16, 22, 10, 20, 21]
[2, 5, 20, 22, 8, 5, 12, 5, 27, 20, 25, 14, 14]
[19, 26, 16, 16, 12, 13, 21, 3, 12, 8, 27, 13, 7]
[8, 12, 1, 4, 7, 0, 20, 26, 3, 24, 1, 6, 24]
[19, 26, 27, 19, 12, 25, 16, 5, 21, 10, 22, 24, 25]
[19, 24, 23, 22, 14, 3, 26, 27, 0, 1, 9, 13, 26]
[9, 4, 4, 8, 8, 6, 10, 6, 12, 22, 16, 14, 23]
[7, 0, 24, 7, 26, 18, 26, 8, 5, 17, 9, 17, 3]
[18, 0, 7, 10, 13, 17, 21, 9, 14, 26, 1, 6, 18]
[11, 16, 17, 12, 27, 0, 3, 23, 10, 19, 23, 26, 1]
[13, 20, 15, 12, 13, 2, 16, 16, 26, 23, 25, 17, 26]
[25, 23, 24, 14, 5, 6, 22, 22, 15, 20, 5, 16, 16]
[11, 4, 14, 1, 24, 4, 3, 2, 6, 27, 1, 21, 22]

[2, 21, 26, 23, 22, 26, 15, 5, 26, 7, 27, 16, 4]
[9, 23, 13, 17, 19, 17, 10, 6, 15, 9, 11, 7, 20]
[0, 14, 16, 26, 26, 14, 22, 21, 15, 21, 9, 7, 2]
[3, 17, 19, 3, 22, 26, 10, 1, 0, 0, 21, 11, 3]
[24, 26, 24, 2, 26, 20, 1, 24, 0, 17, 4, 15, 11]
[14, 3, 6, 20, 0, 27, 23, 27, 14, 6, 14, 8, 10]
[14, 11, 25, 22, 15, 1, 4, 24, 19, 22, 5, 14, 4]
[11, 2, 22, 1, 16, 11, 13, 6, 13, 12, 10, 6, 17]
[15, 9, 1, 15, 27, 3, 26, 21, 22, 22, 20, 9, 1]
[25, 8, 9, 7, 10, 15, 26, 11, 15, 10, 26, 10, 4]
[9, 25, 20, 20, 14, 18, 18, 12, 18, 11, 20, 2, 19]
[0, 15, 3, 11, 18, 24, 24, 5, 18, 9, 19, 7, 12]
[9, 7, 13, 15, 22, 0, 3, 16, 27, 17, 1, 27, 20]
[14, 9, 3, 24, 22, 12, 14, 27, 0, 19, 22, 21, 18]
[15, 9, 10, 15, 7, 9, 18, 8, 24, 12, 18, 4, 23]
[16, 19, 16, 26, 27, 21, 7, 9, 24, 3, 23, 22, 5]
[13, 26, 16, 8, 22, 20, 23, 14, 19, 22, 19, 4, 2]
[2, 8, 1, 19, 23, 27, 18, 21, 5, 17, 15, 3, 12]
[21, 17, 10, 6, 21, 14, 27, 21, 15, 22, 27, 4, 13]
[24, 23, 4, 11, 12, 21, 23, 4, 11, 10, 2, 16, 25]
[26, 26, 21, 27, 23, 16, 9, 0, 27, 10, 3, 12, 9]
[23, 13, 12, 16, 15, 15, 2, 26, 3, 11, 11, 13, 16]
[4, 21, 6, 7, 26, 10, 19, 16, 24, 7, 0, 14, 21]
[8, 10, 2, 15, 14, 27, 20, 20, 10, 15, 22, 8, 12]
[21, 8, 15, 1, 12, 5, 2, 15, 9, 19, 19, 7, 9]
[8, 22, 0, 22, 9, 5, 19, 13, 2, 24, 25, 12, 13]
[12, 20, 19, 20, 5, 18, 17, 21, 9, 16, 22, 18, 17]
[20, 20, 19, 14, 10, 0, 8, 4, 14, 5, 4, 3, 3]
[1, 5, 22, 4, 12, 20, 13, 16, 8, 26, 10, 23, 23]
[14, 13, 8, 8, 18, 8, 20, 24, 24, 20, 18, 12, 10]
[24, 1, 0, 11, 21, 9, 16, 1, 1, 23, 16, 22, 13]
[26, 19, 6, 23, 22, 24, 19, 4, 0, 11, 17, 4, 15]
[15, 0, 25, 22, 13, 21, 25, 1, 9, 4, 7, 10, 14]
[26, 3, 0, 6, 2, 3, 14, 19, 3, 7, 17, 2, 2]
[15, 10, 1, 3, 27, 12, 27, 26, 17, 12, 6, 5, 27]
[11, 4, 7, 22, 13, 24, 14, 25, 19, 21, 6, 15, 17]
[24, 15, 15, 13, 10, 14, 15, 4, 18, 23, 2, 12, 0]
[26, 21, 25, 27, 7, 25, 3, 8, 13, 25, 3, 17, 11]
[20, 20, 16, 14, 0, 25, 24, 5, 4, 15, 0, 20, 6]
[9, 3, 15, 12, 18, 25, 5, 15, 27, 12, 0, 25, 14]
[27, 14, 11, 26, 11, 10, 7, 21, 15, 0, 12, 21, 21]
[13, 20, 6, 22, 6, 18, 5, 2, 18, 10, 25, 5, 20]
[14, 24, 12, 13, 20, 12, 22, 11, 19, 21, 8, 11, 20]
[7, 0, 1, 20, 13, 24, 9, 23, 10, 15, 10, 18, 14]
[2, 11, 13, 9, 14, 21, 7, 21, 25, 4, 13, 5, 8]
[6, 3, 25, 12, 24, 17, 0, 15, 16, 20, 23, 8, 5]
[10, 16, 3, 16, 0, 25, 11, 3, 10, 1, 7, 10, 14]
[19, 9, 21, 12, 5, 24, 27, 13, 2, 7, 2, 10, 2]
[19, 8, 25, 18, 22, 15, 24, 3, 6, 6, 17, 11, 1]
[11, 26, 0, 8, 20, 6, 6, 20, 19, 6, 9, 15, 14]
[13, 12, 13, 24, 24, 22, 2, 22, 5, 13, 12, 9, 19]
[7, 3, 0, 11, 5, 21, 10, 26, 22, 26, 8, 18, 7]
[3, 17, 18, 23, 3, 17, 18, 6, 21, 7, 9, 0, 10]
[27, 18, 0, 26, 0, 12, 24, 16, 6, 11, 8, 0, 12]
[26, 3, 8, 23, 0, 13, 12, 14, 1, 10, 16, 7, 7]
[3, 24, 8, 7, 3, 4, 26, 10, 23, 21, 1, 25, 5]
[17, 5, 25, 6, 13, 8, 23, 9, 26, 1, 10, 22, 16]
[27, 18, 9, 15, 13, 27, 14, 2, 15, 15, 22, 8, 20]
[27, 26, 21, 26, 4, 22, 16, 7, 5, 20, 25, 24, 13]
[11, 3, 14, 7, 8, 23, 18, 7, 22, 4, 8, 1, 19]
[1, 21, 24, 20, 3, 22, 9, 5, 25, 3, 10, 7, 11]
[2, 27, 2, 20, 26, 12, 10, 9, 24, 20, 2, 5, 24]
[26, 18, 7, 0, 11, 7, 12, 22, 18, 20, 9, 5, 10]
[13, 26, 14, 16, 15, 1, 8, 4, 10, 26, 12, 23, 26]
[25, 16, 11, 1, 25, 24, 18, 0, 17, 23, 13, 16, 11]
[22, 22, 9, 20, 25, 12, 27, 7, 20, 26, 22, 2, 11]
[16, 14, 24, 26, 19, 3, 5, 8, 19, 16, 25, 21, 17]
[18, 22, 3, 18, 27, 14, 17, 11, 17, 15, 19, 1, 2]
[2, 8, 3, 11, 24, 18, 14, 25, 4, 17, 27, 15, 15]
[21, 19, 9, 9, 1, 6, 21, 17, 24, 3, 25, 1, 4]
[26, 9, 7, 4, 10, 21, 27, 21, 6, 22, 25, 12, 13]
[1, 16, 27, 15, 25, 0, 25, 7, 15, 1, 25, 12, 24]
[20, 4, 11, 16, 0, 14, 5, 12, 25, 2, 12, 5, 19]
[5, 4, 19, 24, 15, 17, 21, 6, 20, 1, 5, 24, 22]
[5, 14, 9, 12, 18, 21, 13, 17, 10, 24, 16, 25, 25]
[3, 4, 20, 25, 2, 11, 20, 25, 3, 0, 22, 23, 3]
[9, 10, 10, 26, 27, 20, 6, 21, 4, 19, 9, 3, 4]
[13, 13, 18, 10, 1, 18, 8, 22, 10, 8, 21, 3, 18]
[12, 13, 10, 13, 8, 24, 13, 23, 12, 10, 1, 0, 26]
[4, 14, 0, 12, 7, 13, 17, 5, 13, 0, 22, 22, 27]
[19, 7, 25, 26, 4, 2, 3, 21, 7, 8, 15, 27, 10]
[14, 25, 11, 10, 17, 22, 4, 7, 16, 10, 9, 21, 6]
[5, 20, 8, 24, 24, 23, 21, 26, 8, 2, 0, 9, 25]
[26, 18, 8, 25, 18, 14, 23, 13, 19, 12, 2, 0, 21]
[9, 14, 4, 17, 6, 18, 19, 8, 12, 25, 1, 21, 8]
[7, 11, 2, 12, 22, 12, 13, 1, 9, 10, 5, 13, 19]
[12, 20, 14, 14, 13, 7, 9, 7, 24, 23, 5, 2, 5]
[18, 18, 1, 4, 18, 5, 5, 12, 24, 27, 2, 21, 20]
[13, 2, 24, 4, 24, 17, 27, 10, 13, 5, 22, 21, 18]
[12, 1, 14, 15, 16, 11, 9, 0, 22, 0, 26, 14, 21]
[4, 8, 8, 11, 5, 27, 16, 9, 0, 16, 22, 18, 1]
[8, 5, 24, 17, 18, 21, 7, 8, 9, 7, 9, 20, 9]
[14, 8, 5, 23, 7, 10, 25, 18, 12, 12, 0, 16, 25]
[16, 22, 26, 22, 19, 17, 20, 24, 23, 18, 27, 20, 18]
[20, 24, 21, 14, 5, 20, 13, 13, 4, 13, 8, 22, 20]
[20, 23, 23, 27, 18, 20, 25, 18, 5, 22, 9, 18, 3]
[4, 8, 4, 23, 17, 12, 14, 17, 4, 25, 10, 2, 27]
[22, 23, 10, 18, 8, 14, 14, 2, 0, 6, 25, 15, 21]
[18, 22, 7, 22, 24, 24, 2, 0, 17, 18, 17, 20, 10]
[4, 19, 5, 26, 10, 20, 16, 21, 20, 14, 7, 9, 25]
[6, 19, 3, 9, 7, 21, 21, 9, 15, 10, 23, 24, 21]
[12, 22, 21, 19, 2, 14, 18, 7, 3, 18, 11, 26, 22]
[15, 20, 0, 12, 10, 15, 0, 18, 18, 1, 26, 20, 24]
[3, 3, 0, 0, 16, 17, 12, 11, 4, 26, 19, 9, 22]
[0, 15, 8, 20, 22, 20, 6, 6, 13, 10, 1, 5, 14]
[22, 23, 23, 0, 6, 2, 7, 8, 23, 16, 26, 27, 19]
[19, 19, 11, 13, 6, 9, 25, 26, 7, 3, 14, 4, 22]
[6, 25, 11, 9, 25, 7, 22, 17, 27, 16, 3, 20, 27]
[20, 21, 1, 12, 27, 2, 10, 21, 27, 13, 8, 13, 15]
[13, 22, 19, 8, 27, 4, 14, 3, 9, 10, 4, 14, 4]
[20, 3, 2, 9, 27, 6, 8, 5, 27, 19, 3, 25, 13]
[19, 24, 15, 15, 8, 20, 19, 1, 2, 10, 7, 1, 25]
[6, 12, 23, 27, 26, 13, 5, 6, 21, 21, 1, 6, 6]
[3, 0, 6, 8, 21, 20, 2, 26, 4, 4, 18, 12, 1]
[1, 23, 25, 8, 0, 22, 11, 21, 19, 25, 1, 2, 17]
[2, 16, 24, 20, 3, 0, 15, 3, 20, 17, 7, 26, 21]
[11, 8, 27, 16, 25, 6, 11, 19, 22, 20, 15, 5, 22]
[10, 25, 1, 11, 5, 27, 7, 21, 11, 21, 3, 22, 7]
[3, 3, 10, 8, 7, 10, 18, 16, 12, 0, 6, 18, 6]
[19, 8, 25, 7, 23, 0, 9, 27, 18, 8, 2, 25, 9]
[23, 4, 17, 22, 1, 18, 3, 20, 19, 2, 12, 18, 2]
[10, 16, 2, 5, 3, 0, 18, 23, 12, 3, 10, 25, 27]
[11, 25, 5, 11, 15, 21, 24, 9, 10, 22, 20, 16, 18]
[13, 16, 22, 18, 9, 4, 1, 3, 13, 8, 18, 3, 11]
[18, 8, 24, 18, 16, 6, 15, 25, 12, 6, 3, 0, 18]
[25, 21, 22, 9, 8, 12, 12, 3, 11, 25, 13, 2, 8]
[25, 24, 1, 10, 16, 19, 7, 26, 9, 9, 22, 16, 14]
[10, 19, 13, 4, 23, 22, 5, 8, 26, 18, 27, 1, 21]
[10, 13, 0, 0, 2, 16, 2, 21, 8, 19, 11, 20, 17]
[24, 2, 21, 15, 9, 21, 19, 10, 9, 6, 5, 8, 19]
[16, 8, 7, 9, 18, 22, 4, 8, 21, 3, 2, 25, 14]
[14, 6, 17, 0, 13, 22, 0, 0, 25, 20, 27, 27, 22]
[4, 1, 16, 16, 6, 14, 14, 8, 21, 21, 20, 18, 1]
[24, 5, 22, 12, 11, 7, 22, 7, 13, 19, 26, 14, 5]
[14, 0, 7, 3, 3, 17, 21, 21, 8, 15, 18, 17, 13]
[20, 4, 9, 8, 15, 1, 4, 11, 11, 6, 17, 26, 1]
[27, 9, 11, 10, 1, 12, 7, 15, 26, 20, 0, 11, 15]
[22, 8, 7, 23, 12, 10, 17, 15, 20, 8, 25, 24, 22]
[13, 26, 16, 16, 11, 21, 9, 17, 6, 12, 25, 16, 14]
[5, 11, 6, 20, 6, 2, 10, 27, 16, 1, 25, 0, 19]
[16, 16, 9, 20, 13, 10, 6, 5, 10, 18, 10, 3, 15]
[5, 25, 22, 25, 23, 0, 7, 14, 0, 17, 17, 27, 3]
[4, 0, 4, 11, 12, 3, 2, 8, 21, 3, 5, 1, 8]
[9, 26, 14, 6, 14, 10, 6, 25, 5, 24, 9, 25, 7]
[23, 23, 20, 16, 10, 10, 8, 6, 4, 17, 1, 16, 27]
[18, 0, 4, 14, 25, 7, 26, 7, 26, 12, 0, 9, 2]
[19, 4, 23, 1, 27, 27, 11, 2, 4, 5, 7, 16, 13]
[20, 14, 1, 6, 24, 23, 24, 18, 21, 12, 26, 26, 24]
[10, 2, 15, 12, 6, 9, 4, 17, 19, 22, 7, 0, 22]
[26, 10, 24, 25, 21, 25, 5, 2, 17, 13, 2, 21, 2]
[23, 24, 2, 24, 17, 3, 12, 27, 20, 18, 2, 19, 3]
[4, 24, 7, 17, 11, 18, 20, 13, 24, 21, 13, 26, 10]
[24, 22, 11, 21, 10, 23, 14, 17, 27, 25, 20, 26, 27]
[25, 27, 23, 19, 14, 18, 16, 9, 15, 19, 19, 19, 18]
[2, 16, 12, 4, 23, 24, 8, 1, 22, 18, 16, 3, 20]
[25, 11, 5, 15, 27, 13, 17, 10, 14, 20, 22, 22, 9]
[23, 10, 4, 22, 19, 20, 6, 7, 0, 21, 26, 14, 24]
[2, 27, 22, 24, 26, 17, 21, 17, 5, 5, 2, 25, 13]
[0, 27, 1, 3, 16, 22, 10, 5, 1, 0, 6, 2, 27]
[21, 5, 22, 18, 21, 26, 4, 11, 26, 3, 24, 13, 22]
[12, 9, 21, 5, 1, 11, 18, 23, 14, 5, 20, 17, 15]
[6, 9, 12, 22, 3, 4, 18, 8, 9, 22, 15, 13, 13]
[0, 18, 26, 9, 26, 6, 5, 5, 13, 26, 18, 10, 2]
[22, 0, 0, 20, 2, 9, 0, 8, 24, 23, 19, 13, 17]
[18, 27, 20, 8, 18, 14, 7, 8, 19, 5, 9, 19, 6]
[7, 26, 14, 23, 24, 10, 14, 5, 21, 15, 15, 22, 25]
[26, 9, 17, 26, 3, 19, 7, 14, 16, 26, 27, 10, 3]
[4, 15, 17, 13, 2, 18, 4, 27, 3, 9, 26, 22, 4]
[25, 3, 16, 4, 1, 27, 27, 0, 24, 19, 25, 18, 9]
[10, 2, 3, 24, 18, 23, 21, 0, 4, 21, 22, 21, 23]
[1, 3, 19, 10, 12, 0, 14, 19, 15, 12, 20, 2, 13]
[17, 5, 13, 19, 7, 18, 8, 10, 6, 0, 13, 27, 27]
[1, 14, 7, 12, 0, 23, 10, 23, 20, 5, 3, 19, 4]
[11, 22, 26, 17, 15, 6, 7, 3, 6, 22, 11, 13, 16]
[8, 3, 2, 20, 15, 16, 16, 26, 15, 1, 14, 25, 26]
[7, 10, 26, 23, 2, 18, 10, 4, 15, 10, 17, 1, 27]

[2, 25, 18, 14, 20, 17, 12, 14, 23, 25, 2, 23, 13]
[16, 4, 3, 20, 5, 15, 0, 4, 21, 9, 27, 22, 15]
[7, 3, 10, 5, 11, 10, 4, 12, 1, 11, 19, 1, 0]
[19, 27, 5, 24, 26, 10, 2, 3, 19, 15, 5, 5, 19]
[18, 15, 14, 22, 17, 5, 6, 13, 21, 4, 18, 6, 16]
[12, 24, 3, 21, 12, 10, 20, 23, 20, 27, 11, 27, 23]
[17, 9, 25, 19, 23, 21, 14, 27, 15, 17, 25, 23, 25]
[25, 8, 26, 6, 20, 27, 10, 18, 15, 0, 25, 17, 9]
[9, 27, 21, 22, 16, 21, 14, 6, 19, 10, 7, 15, 20]
[13, 15, 6, 20, 2, 2, 20, 1, 12, 13, 17, 7, 26]
[12, 6, 17, 6, 6, 10, 6, 2, 19, 25, 12, 14, 4]
[18, 11, 14, 20, 13, 4, 15, 3, 15, 20, 12, 11, 14]
[17, 24, 3, 7, 10, 27, 13, 25, 14, 16, 15, 6, 21]
[10, 2, 15, 23, 16, 16, 27, 10, 26, 4, 4, 4, 19]
[20, 19, 10, 16, 6, 16, 22, 4, 0, 10, 23, 18, 5]
[27, 10, 20, 14, 24, 19, 12, 24, 2, 15, 27, 8, 11]
[13, 21, 3, 7, 1, 6, 23, 7, 27, 6, 26, 27, 5]
[20, 24, 12, 7, 11, 20, 20, 4, 1, 11, 14, 13, 18]
[1, 7, 27, 15, 17, 8, 24, 16, 4, 15, 14, 27, 11]
[22, 20, 3, 7, 8, 23, 26, 11, 16, 8, 20, 4, 22]
[13, 6, 27, 13, 10, 6, 18, 13, 8, 12, 22, 0, 11]
[4, 9, 17, 18, 13, 7, 20, 26, 7, 14, 19, 12, 11]
[26, 4, 7, 3, 19, 8, 1, 3, 5, 17, 26, 12, 27]
[21, 26, 5, 24, 3, 5, 21, 7, 1, 4, 13, 26, 1]
[14, 26, 2, 17, 15, 4, 9, 19, 18, 13, 19, 17, 3]
[16, 23, 9, 23, 9, 4, 23, 18, 3, 3, 0, 11, 10]
[24, 21, 5, 0, 17, 27, 27, 20, 13, 23, 14, 16, 18]
[4, 8, 24, 20, 27, 26, 16, 19, 16, 4, 5, 19, 15]
[10, 14, 21, 3, 17, 12, 15, 23, 20, 26, 13, 11, 22]
[14, 27, 21, 1, 1, 17, 20, 21, 21, 13, 12, 15, 13]
[18, 26, 3, 19, 12, 16, 9, 19, 26, 18, 17, 13, 23]
[25, 11, 26, 1, 8, 10, 24, 16, 27, 2, 4, 3, 10]
[26, 17, 19, 17, 20, 22, 11, 5, 20, 9, 5, 3, 17]
[15, 11, 17, 8, 7, 8, 25, 22, 12, 8, 13, 21, 22]
[5, 19, 5, 20, 24, 5, 11, 11, 2, 24, 26, 22, 15]
[11, 22, 13, 17, 14, 0, 1, 1, 8, 0, 11, 7, 5]
[14, 19, 18, 14, 15, 13, 19, 26, 4, 8, 10, 2, 15]
[6, 8, 11, 13, 11, 20, 10, 21, 19, 10, 25, 7, 15]
[0, 5, 27, 2, 10, 5, 27, 1, 15, 18, 0, 10, 19]
[18, 23, 3, 27, 6, 18, 8, 14, 10, 19, 22, 16, 25]
[14, 13, 3, 25, 19, 12, 9, 19, 27, 2, 1, 15, 0]
[25, 25, 6, 26, 27, 18, 4, 21, 26, 19, 5, 15, 1]
[25, 10, 9, 15, 22, 2, 4, 0, 14, 14, 6, 19, 15]
[1, 6, 18, 8, 26, 9, 16, 15, 12, 7, 13, 23, 5]
[8, 3, 27, 15, 18, 0, 8, 22, 2, 24, 11, 21, 7]
[23, 13, 3, 17, 7, 2, 1, 3, 18, 16, 19, 16, 18]
[4, 6, 17, 25, 10, 9, 11, 3, 2, 1, 15, 2, 23]
[10, 12, 15, 3, 1, 6, 12, 21, 3, 11, 24, 2, 21]
[6, 6, 12, 4, 9, 18, 10, 6, 17, 13, 17, 4, 23]
[5, 13, 9, 15, 13, 3, 6, 13, 14, 14, 3, 14, 22]
[7, 4, 2, 18, 23, 8, 6, 18, 24, 18, 14, 6, 20]
[2, 25, 1, 2, 20, 18, 24, 16, 4, 8, 14, 21, 25]
[11, 26, 25, 26, 12, 24, 9, 27, 20, 6, 24, 6, 26]
[20, 3, 9, 14, 19, 19, 18, 8, 11, 27, 18, 15, 21]
[13, 26, 25, 6, 18, 6, 17, 23, 9, 21, 9, 10, 5]
[27, 12, 27, 26, 13, 27, 10, 3, 1, 3, 11, 5, 27]
[14, 11, 23, 2, 9, 20, 27, 3, 27, 12, 15, 16, 12]
[18, 16, 11, 8, 9, 12, 15, 20, 10, 0, 13, 23, 14]
[9, 24, 0, 6, 12, 15, 22, 1, 0, 4, 5, 16, 21]
[1, 4, 16, 1, 17, 0, 12, 13, 10, 11, 23, 25, 0]
[14, 12, 24, 10, 0, 19, 24, 22, 17, 17, 21, 4, 7]
[22, 16, 5, 19, 9, 13, 16, 22, 11, 12, 27, 15, 2]
[8, 20, 10, 11, 24, 18, 12, 18, 20, 23, 25, 4, 6]
[11, 25, 12, 9, 25, 20, 24, 17, 14, 25, 9, 24, 2]
[21, 18, 2, 16, 4, 21, 25, 23, 12, 13, 7, 4, 15]
[0, 7, 7, 19, 14, 22, 22, 22, 25, 26, 5, 7, 22]
[11, 14, 21, 18, 12, 14, 16, 8, 0, 6, 8, 15, 0]
[5, 7, 14, 26, 10, 2, 8, 11, 5, 22, 26, 25, 2]
[21, 26, 19, 22, 20, 1, 15, 26, 16, 12, 6, 14, 12]
[13, 21, 12, 20, 26, 2, 23, 21, 22, 18, 19, 7, 26]
[13, 3, 13, 16, 15, 5, 21, 3, 26, 23, 22, 15, 17]

In [185]:
data_test.head()

    1   2   3   4   5   6   7   8   9  10  11  12  13
0   5  14  16   5  26  14  24  24  15  27  15  13  23
1  17   7  25  10  14   9   6  26   5  19  22  26  24
2  12   8  20   7   7   0  10  22   8  12  11   9   0
3   7  19  19   6  13   7  16  26  11   8   9  15  12
4  16  21   2  20  10   8   5  11  27  20  18   0   3

In [186]:
def category_signal_test(row,col):
    """

    :param row:
    :return:
    """
    if row["cat_"+str(col)][:5]=='BATT_':
        return 1
    elif row["cat_"+str(col)][:4]=='CAN_':
        return 2
    elif row["cat_"+str(col)][:6]=='CANFD_':
        return 3
    elif row["cat_"+str(col)][:4]=='GND_':
        return 4
    elif row["cat_"+str(col)][:9]=='GNDR_GND_':
        return 5
    elif row["cat_"+str(col)][:3]=='HV_':
        return 6
    else:
        return 7


def return_cat(row, col ,dicc_cat):
    cat=row[col]
    return dicc_cat[cat]

In [187]:
for col in data_test.columns:
    data_test["cat_"+str(col)]= data_test.apply(lambda row: return_cat(row, col ,dicc_13), axis=1)
    data_test[col]= data_test.apply(lambda row: category_signal_test(row, col ), axis=1)

In [188]:
data_test.tail()

,1,2,3,4,5,6,7,8,9,10,...,cat_4,cat_5,cat_6,cat_7,cat_8,cat_9,cat_10,cat_11,cat_12,cat_13
495,7,7,6,7,7,7,7,7,7,7,...,EQ_FUEL_PRESS_SSR_HI-TNGA_PR,SLD_MG_ECU_201,TW_CLEARANCE_SNR_ECU_056,EQ_FUEL_PRESS_SSR_HI-TNGA_VC,SLD_EFI_ECU-TNGA_KNOCK_SSR_101,EQ_NE_SSR-TNGA_NE-,SLD_MG_ECU_198,EQ_PDB_L_5,HV_ECU-HV_0025,SLD_MG_ECU_203
496,7,7,7,7,7,7,4,4,7,7,...,na,SLD_MG_ECU_199,SLD_MG_ECU_199,GND_BK_UP_LP_LH_E,GND_BK_UP_LP_LH_E,SLD_MG_ECU_199,SLD_MG_ECU_201,CLEARANCE_SNR_ECU_0890,CLEARANCE_SNR_ECU_0890,EQ_NE_SSR-TNGA_NE-
497,7,7,7,7,7,7,7,7,7,7,...,SLD_MG_ECU_200,TW_CLEARANCE_SNR_ECU_062,EQ_NE_SSR-TNGA_VCNE,SLD_EFI_ECU-TNGA_KNOCK_SSR_102,TW_CLEARANCE_SNR_ECU_055,SLD_MG_ECU_197,EQ_FUEL_PRESS_SSR_HI-TNGA_E2,SLD_MG_ECU_201,EQ_PDB_L_1,SLD_MG_ECU_198
498,7,7,7,7,7,7,7,7,6,7,...,TW_CLEARANCE_SNR_ECU_056,SLD_MG_ECU_202,EQ_FUEL_PRESS_SSR_HI-TNGA_E2,SLD_MG_ECU_203,CLEARANCE_SNR_ECU_0890,HV_ECU-HV_0025,EQ_NE_SSR-TNGA_NEP,SLD_EFI_ECU-TNGA_KNOCK_SSR_102,SLD_EFI_ECU-TNGA_KNOCK_SSR_101,SLD_EFI_ECU-TNGA_KNOCK_SSR_102
499,7,7,7,7,7,7,7,7,7,7,...,TW_CLEARANCE_SNR_ECU_056,na,TW_CLEARANCE_SNR_ECU_055,SLD_MG_ECU_200,TW_CLEARANCE_SNR_ECU_062,EQ_FUEL_PRESS_SSR_HI-TNGA_PR,EQ_FUEL_PRESS_SSR_HI-TNGA_PR,SLD_MG_ECU_201,TW_CLEARANCE_SNR_ECU_056,EQ_PDB_L_5

In [189]:
data_test.to_csv("data/data_test_13.csv", index=False)

In [211]:
def get_bin_10(n,bins10):
    """
    get bin index
    :param n:
    :param bins10:
    :return:
    """
    _bin=10
    for i in range(0,len(bins10)):
        if bins10[i]> n:
            _bin=i-1
            break
    return _bin

def get_pin_signal_test(sig_conn,i,signal_cat):
    """
    #1 number pins [0,Num_Pin_unique_max]
    #2 distance to center pin [0,11]bucket
    #3 number of neighbors[0,Num_Pin_unique_max-1]
    #4 internal/external[0,1]
    #5 mean_neighbors [0,11]bucket
    #6 distance centroide [0,11]bucket
    #7 signal category [0,7]
    #8 color wire categorical[0,max_color_categories]
    #9 thickness wire continuous[0,51]bucket
    #10 multicore yes/no [0,1]
    #11 number of internal pins [0,Num_Pin_unique_max//2]
    #12 nosignal [0,1]
    #13 ismulticore [0,1]
    #14 category multicore [0,max_multicore_categories]
    get observation from File
    :param sig_conn:
    :param i:
    :return:
    """
    # create bins
    bins_distance= np.linspace(sig_conn['1']['min_distance'], sig_conn['1']['max_distance'], 11)
    bins_thickness= np.linspace(sig_conn['1']['Wire_WireCSA_min'], sig_conn['1']['Wire_WireCSA_max'], 51)

    Num_Pins=sig_conn[str(i)]['Num_Pins']
    distance_to_center=get_bin_10(random.randint(0, 10), bins_distance)
    neighbors_length=sig_conn[str(i)]['neighbors_length']
    internal_pin = 1 if sig_conn[str(i)]['internal_pin'] =='True' else 0
    mean_neighbors=get_bin_10(random.randint(0, 10), bins_distance)
    centroide_distance=get_bin_10(sig_conn[str(i)]['centroide_distance'], bins_distance)
    signal_group= signal_cat # Signal Category for test
    Cat_Wire_WireColor=sig_conn[str(i)]['Cat_Wire_WireColor']
    WireCSA=get_bin_10(random.randint(0, 51), bins_thickness)
    is_multicore = 0 if sig_conn[str(i)]['is_multicore'] =='na' else 1
    number_internal_pin= sig_conn[str(i)]['number_internal_pin']
    nosignal = random.randint(0, 1)
    ismulticore= random.randint(0, 1)
    cat_multicore=sig_conn[str(i)]['multicore_same']
    return list([Num_Pins,distance_to_center,neighbors_length,internal_pin,mean_neighbors,
                 centroide_distance,signal_group,Cat_Wire_WireColor,WireCSA,is_multicore,
                 number_internal_pin,nosignal,ismulticore, cat_multicore])

In [216]:
from stable_baselines3.common.vec_env import DummyVecEnv
env_demo = DummyVecEnv([lambda: conn(Num_Pin_unique_max, max_color_categories, max_categories_multicore, Num_Pins)])

In [218]:
data_test['prediction']=0
for i, row in data_test.iterrows():
    env = conn(Num_Pin_unique_max, max_color_categories,max_categories_multicore, Num_Pins) 
    obs = env.reset()
    for key in connectors_dicc[connector].keys():
        if key != 'PartNumber':
    #for c in tcols:
            signalcat= data_test.loc[i, key]
            obs = np.array(get_pin_signal_test(connectors_dicc[connector],key, signalcat))
            action, _state = model.predict(obs, deterministic=False)
        
            obs, reward, done, info = env.step(action.astype(int))
            
            env.render()
            if done:
               obs = env.reset()
    
    print(reward)
    data_test.at[i,'prediction']=reward
#     if i > 2:
#         break

104
121
136
110
104
116
116
110
116
104
116
115
128
98
128
103
128
91
128
118
116
98
104
134
104
128
98
110
128
128
104
128
128
128
128
128
133
116
128
116
118
104
116
128
98
116
116
116
116
124
128
116
116
124
128
103
128
128
104
116
128
146
116
128
128
128
128
116
115
128
128
128
116
116
133
128
104
92
98
128
104
124
128
116
116
116
116
118
104
104
116
116
128
121
104
104
116
128
128
116
92
128
128
110
116
116
124
128
116
116
88
116
116
116
128
128
128
105
128
128
128
104
110
115
118
116
128
116
116
116
116
128
116
128
128
98
92
128
116
128
128
128
104
128
116
128
128
116
128
146
116
136
116
110
116
110
116
116
128
116
116
104
128
128
128
94
128
128
128
116
128
124
116
128
128
128
128
104
116
128
104
116
116
116
128
116
116
110
121
116
128
109
128
116
116
110
116
116
116
110
116
136
116
104
110
116
128
128
116
128
136
128
128
116
128
124
116
104
116
124
116
128
104
116
116
128
128
146
128
116
136
116
116
116
116
104
128
104
110
128
98
98
128
110
128
128
116
133
98
128
112
104
116
116
133
109
128
128
118
110
116
136
128
128
128
128
116
124
116
128
128
112
116
116
116
128
124
116
128
98
116
115
116
116
136
124
104
128
128
128
116
128
128
116
124
128
136
136
115
116
124
116
116
128
91
116
128
146
124
112
116
116
116
116
128
134
116
116
116
136
128
128
128
104
98
128
116
116
116
116
104
136
128
136
128
128
98
128
128
116
124
128
116
133
116
128
133
116
136
104
128
128
98
116
110
136
133
128
128
128
116
128
128
116
128
128
116
116
124
92
116
116
98
128
116
116
110
128
116
116
136
110
128
128
116
116
128
116
128
116
110
128
134
116
104
104
116
124
124
124
116
104
116
104
104
128
136
116
128
104
98
104
116
116
116
128
128
104
128
124
116
116
128
128
128
124
128
124
128
88
116
128
110
116
118
98
128
116
128
104
103
104
110
116
104
128
116
124
116
116
128
116
116
116
128
128
116
112
116
104
116
128
116
128
134
116
124
128
116
98
128
128
98
116
116
104
116
104
116
128
98
116
116
104
136
116
112
104
128
116
128
112
128
128
116
128
116
128
124
98

In [193]:
obs = env.reset()
for key in connectors_dicc[connector].keys():
    if key != 'PartNumber':
        obs = np.array(get_pin_signal(connectors_dicc[connector],key))
        action, _state = model.predict(obs, deterministic=True)
        
        obs, reward, done, info = env.step(action.astype(int))
        print(reward)
        env.render()
        if done:
           obs = env.reset()
print(reward)

18
18
17
17
22
22
41
41
48
48
55
55
74
74
81
81
82
82
89
89
96
96
103
103
110
110
110

In [214]:
data_test.head()

,1,2,3,4,5,6,7,8,9,10,...,cat_5,cat_6,cat_7,cat_8,cat_9,cat_10,cat_11,cat_12,cat_13,prediction
0,7,7,7,7,7,7,7,7,7,7,...,TW_CLEARANCE_SNR_ECU_062,SLD_EFI_ECU-TNGA_KNOCK_SSR_101,TW_CLEARANCE_SNR_ECU_056,TW_CLEARANCE_SNR_ECU_056,SLD_EFI_ECU-TNGA_KNOCK_SSR_102,na,SLD_EFI_ECU-TNGA_KNOCK_SSR_102,HV_ECU-HV_0025,TW_CLEARANCE_SNR_ECU_055,116
1,7,7,7,7,7,7,7,7,7,7,...,SLD_EFI_ECU-TNGA_KNOCK_SSR_101,EQ_PDB_L_2,EQ_NE_SSR-TNGA_NEP,TW_CLEARANCE_SNR_ECU_062,EQ_NE_SSR-TNGA_NE-,SLD_MG_ECU_200,SLD_MG_ECU_203,TW_CLEARANCE_SNR_ECU_062,TW_CLEARANCE_SNR_ECU_056,128
2,6,7,7,7,7,7,7,7,7,6,...,EQ_NE_SSR-TNGA_VCNE,CLEARANCE_SNR_ECU_0885,EQ_PDB_L_5,SLD_MG_ECU_203,EQ_PDB_L_1,HV_ECU-HV_0024,GND_BK_UP_LP_LH_E,EQ_PDB_L_2,CLEARANCE_SNR_ECU_0885,128
3,7,7,7,7,6,7,7,7,4,7,...,HV_ECU-HV_0025,EQ_NE_SSR-TNGA_VCNE,SLD_MG_ECU_197,TW_CLEARANCE_SNR_ECU_062,GND_BK_UP_LP_LH_E,EQ_PDB_L_1,EQ_PDB_L_2,SLD_EFI_ECU-TNGA_KNOCK_SSR_102,HV_ECU-HV_0024,110
4,7,7,7,7,7,7,7,4,7,7,...,EQ_PDB_L_5,EQ_PDB_L_1,EQ_NE_SSR-TNGA_NE-,GND_BK_UP_LP_LH_E,na,SLD_MG_ECU_201,SLD_MG_ECU_199,CLEARANCE_SNR_ECU_0885,EQ_FUEL_PRESS_SSR_HI-TNGA_PR,128

In [ ]:
print(env.observation_space)
print(env.action_space)
print(env.action_space.sample())

In [ ]:
n_steps = 1300
GO_LEFT=random.randint(0, max_categories )
for step in range(n_steps):
    #print("Step {}".format(step + 1))
    GO_LEFT=random.randint(0, max_categories )
    obs, reward, done, info = env.step(GO_LEFT)
    #print('obs=', obs, 'reward=', reward, 'done=', done)
    env.render()
    if done:
        print("Goal reached!", "reward=", reward)
        obs = env.reset()

In [ ]:
from stable_baselines3.common.vec_env import DummyVecEnv
env_train = DummyVecEnv([lambda: conn(connectors_dicc,list_signals ,connector ,len_test_conn, max_categories,state_space)])

In [ ]:
# 13 TO_161_RH_F/169_13P  TO_121_TNGA_F/219_13P

In [ ]:
env_train = DummyVecEnv([lambda: conn(connectors_dicc,list_signals ,connector ,len_test_conn, max_categories,state_space)])

In [ ]:
from stable_baselines3 import DQN, TD3

In [ ]:
from stable_baselines3 import DQN, TD3
model = DQN('MlpPolicy', env_train, verbose=2)

In [ ]:
#model = TD3('MlpPolicy', env_train, verbose=2)

In [ ]:
import time
time.time()

In [ ]:
import time
time1=time.time()
model.learn(10000)
time2=time.time()

print(time2-time1)

In [ ]:
obser=[6,7,8,4,3,5,0,1,2,8,8,8,8,]#'TO_121_TNGA_F/219_13P'
obser=[0,2,1] #TO_111_LH_F/143_3P
#obser=[14,15,27,6,5,7,2,3,4,27,27,27,27] #TO_121_TNGA_F/219_13P   TO_161_RH_F/169_13P 

obser=[13,18,18,21,27,27,12,18,16,22,20,27,27]

In [ ]:
new_observ=list(np.zeros(len(obser), dtype='int'))
reward=0
for x in range(0,len(obser)):
    new_observ[x]=obser[x]
    #print(new_observ)
    pred=model.predict(np.array(new_observ), deterministic= False)
    reward=reward+pred[0]
print(reward)

In [ ]:
model.env.reset()
model.env.observation_space

In [ ]:
model.save("")